### ISSUE TITLE
No Delete (Message Logger)

### ISSUE THREAD

**Issue by Lewko6702** [Aliucord/plugin-requests#10]
### Description
See users deleted messages/files

### More info
Be able to see users deleted messages, images, and files with the ability to download media

---

- [x] I checked if this plugin wasn't already requested.

**Comment by ShiroBlank** [comment]
@Juby210 is currently working on this, no ETA on release afaik.

**Comment by Juby210** [comment]
https://github.com/Juby210/Aliucord-plugins/raw/builds/MessageLogger.zip
