### ISSUE TITLE
amogus

### ISSUE THREAD

**Issue by rushiiMachine** [Aliucord/plugin-requests#1000]
### Plugin Description

Sends a random amogus gif with /amogus

### Go into more detail...

sussy wussy

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
https://user-images.githubusercontent.com/24845294/167277186-d5300d8f-812d-4f27-a3d0-38180d8c4427.mp4

**Comment by Dungeonscats** [comment]
:husk:

**Comment by taskylizard** [comment]
i'm making this

**Comment by taskylizard** [comment]
Done: https://github.com/mantikafasi/AliucordPlugins/blob/builds/Amog%E2%80%8C%E2%80%8Dus.zip
