### ISSUE TITLE
See deleted messages 

### ISSUE THREAD

**Issue by mellowfllow** [Aliucord/plugin-requests#1006]
### Plugin Description

A plugin that could allow to see any deleted messages. Or rather retain the data of the message so when it's deleted on another user's end the user with the plugin still has the ability to view it

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by WiBJDOGKINGZ** [comment]
This already exists 

MessageLogger

**Comment by mellowfllow** [comment]
Link?

**Comment by WiBJDOGKINGZ** [comment]
https://discord.com/channels/811255666990907402/811275162715553823/835554229484519484
