### ISSUE TITLE
Plugins export / Import (Backup / restore plugins)

### ISSUE THREAD

**Issue by ghost** [Aliucord/plugin-requests#1007]
### Discord Account

SexyYoda#1368

### Plugin Description

well, it makes a backup of all plugins and restores them after reinstallation of AliuCord 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ServOKio** [comment]
Maybe you should just copy `Aliucord` folder to sd card, and then back ?

**Comment by Sexy-Yoda** [comment]
> Aliucord

Oh, didn't think of that
but an option in the app would be easier tho

**Comment by ServOKio** [comment]
> be easier / better tho

What's the difference? Yes, it may be easier, but you still have to choose the path for the copy every time as if you did it manually.

**Comment by rushiiMachine** [comment]
just copy ~/Aliucord/plugins
