### ISSUE TITLE
Show sessions

### ISSUE THREAD

**Issue by rollingmoai** [Aliucord/plugin-requests#101]
### Discord Account

itsmeboy#3660

### Plugin Description

Port of ShowSessions for Aliucord.

BetterDiscord: https://betterdiscord.app/plugin/ShowSessions
Powercord: https://github.com/Oocrop/show-sessions

### Go into more detail...

Show your current sessions with `/sessions` or in the accounts panel.

![In accounts panel](https://betterdiscord.app/resources/thumbnails/633.png)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by thecprog** [comment]
@DiamondMiner88 you will finish this NOW

**Comment by DiamondMiner88** [comment]
i suck at ui lmao

**Comment by rushiiMachine** [comment]
wing did this
