### ISSUE TITLE
Export server member list

### ISSUE THREAD

**Issue by suckinsyn** [Aliucord/plugin-requests#1016]
### Plugin Description

A way to export the whole server member list along with their rich presence status.

### Go into more detail...

As above, but a bit more detailed:

data could be stored in a json format, something like:
"id":"nick#1234"
"alias":"newnick"
"status":"xyz"

"id":"nick#4321"
"alias":"newnick1"
"status":"in-game abc"

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by TymanWasTaken** [comment]
Just use a bot
I know Carl bot has a !dump command that will do this
