### ISSUE TITLE
Auto date

### ISSUE THREAD

**Issue by LostDread** [Aliucord/plugin-requests#1017]
### Discord Account

Dread#6352

### Plugin Description

I think a plugin that if i say {date} it's replace that with the middle European date in the European spelling
Sry if this was already there bc my github bugged

### Go into more detail...

Maybe some Features to change the spelling and whitch date 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
what? you mean date formatting?
aliucord does not have a way to read your mind of what date format you used
