### ISSUE TITLE
Force Embed failed emoji links (editing the same link)

### ISSUE THREAD

**Issue by AkaRaxxy** [Aliucord/plugin-requests#1018]
### Discord Account

Rax#3850

### Plugin Description

uh maybe a plugin that would force embed a failed emoji link, editing a failed link with same link text embeds it, so the plugin could check whether the emoji link was embedded or not, if not, it would edit it with same text until it embeds, ofc while checking whether the user has embeds perms.

(there was a similar request like this but it meant to delete failed links so i preferred making a new issue.)

### Go into more detail...

this could be added as an extension in nitro spoof plugin or smtg like that.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
if it embeds properly after editing that means it was a client sided issue and worked correctly for others anyway. If it doesn't, you simply don't have embeds perms
