### ISSUE TITLE
A plugin to copy links of any type of attachment.

### ISSUE THREAD

**Issue by rickdtc** [Aliucord/plugin-requests#102]
### Discord Account

PUTDEMKNOCK#2006

### Plugin Description

Discord only let's us copy image and video attacment links only,  a plugin to copy a link to any attachment of any file format would be nice.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by X1nto** [comment]
I'll take this

**Comment by rickdtc** [comment]
Sorry, this was already requested #67
