### ISSUE TITLE
Show username in brackets near nickname 

### ISSUE THREAD

**Issue by Minibus93** [Aliucord/plugin-requests#1021]
### Discord Account

MiniBus93#5946

### Plugin Description

A simple plugin that shows username near nickname of a user. 

For example, on server A I have, as nickname, XXXMyDongIsLongXXX, but my actual nickname is KingArthur.
The plugin would show something like
XXXMyDongIsLongXXX (KingArthur)

Would be very helpful is large server where people often change nicknames

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Minibus93** [comment]
Can you tell me of which request is this duplicate or what is the name of the plugin that already exists and does this?

I couldn't find it, only found "friendnicknames" but you have to manually set nicknames for users and it doesn't work as I described here

**Comment by WiBJDOGKINGZ** [comment]
> Can you tell me of which request is this duplicate or what is the name of the plugin that already exists and does this?
> 
> I couldn't find it, only found "friendnicknames" but you have to manually set nicknames for users and it doesn't work as I described here

It's called 
CustomNicknameFormat
