### ISSUE TITLE
Gelbooru

### ISSUE THREAD

**Issue by GoodMoaning** [Aliucord/plugin-requests#1022]
### Plugin Description

A Plugin with / Command to search up Gelbooru Images(?) and includes an Optional [Send] button.

Theres a Neko one.. and a Waifu plugin.
I don't see why there shouldnt be a Gelbooru plugin that does the same thing.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [x] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
finished 
but its safebooru not gelbooru 
https://github.com/OmegaSunkey/awesomeplugins/blob/builds/SafeBooru.zip?raw=true
