### ISSUE TITLE
Keep videos on screen when scrolling

### ISSUE THREAD

**Issue by Likver** [Aliucord/plugin-requests#1024]
### Plugin Description

So maybe add a plugin that makes videos go to pip when scrolling on chats, and even when u go to other srvr/channel it would still there in pip mode

### Go into more detail...

it could have a button to go to the msg, one to volume up or down (or just open the volume dialog) and one to pause/resume the video (plus the X button to close the pip)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by A-rhyna-H** [comment]
stop with pip requests when
