### ISSUE TITLE
Revert blurple color/old logos 

### ISSUE THREAD

**Issue by imapancake22** [Aliucord/plugin-requests#1026]
### Discord Account

taiwanisfake#4504

### Plugin Description

Basicly it makes discord look the way it did before the 2021 update. Instead of the new blue it the old purple blue and it has the old logo 

### Go into more detail...

Basicly it makes discord look the way it did before the 2021 update. Instead of the new blue it the old purple blue and it has the old logo 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [x] I did indeed check to make sure my plugin request is original!

**Comment by UsernameNotAvalible** [comment]
There are already themes for that
