### ISSUE TITLE
Some requests I think may be useful.

### ISSUE THREAD

**Issue by YAPPwikiaFANDOM** [Aliucord/plugin-requests#1029]
### Plugin Description

1. Make the message header to have multiple lines.
2. Make message colors for your messages and only yourself are different than others.

### Go into more detail...

1. Basically, the header (you know, name, tags, timestamps, etc.) could made to two lines or more. This way it can carry more information while in chat. QOL stuff. Example: https://media.discordapp.net/attachments/660877576276803584/977899935921995816/Screenshot_2022-05-22-18-44-50-80.jpg

It could be role icons, tags, and timestamps (and who knows, account badges and server badges) in the second line. But idk, up to ya'll i guess.

2. You basically set a color for your own messages, and set another color for everyone else's messages. And maybe another for blocked messages?

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by MeFinity** [comment]
one request per issue please
