### ISSUE TITLE
Activity Plugin

### ISSUE THREAD

**Issue by Defalt-svg** [Aliucord/plugin-requests#103]
### Discord Account

Kazutora#6779

### Plugin Description

A plugin that displays when a user on your friend list switches their activity status to offline, online, or dnd.

### Go into more detail...

When the user switches to invisible, a popup message/notification should appear that displays the user going offline.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
#194
