### ISSUE TITLE
Fart searcher

### ISSUE THREAD

**Issue by ItzOnlyAnimal** [Aliucord/plugin-requests#1032]
### Discord Account

nop

### Plugin Description

I think a plugin that does dedicated searching through members for a keyword like fart would be cool! Maybe if it could do show more than just using @ mention too?

### Go into more detail...

I think it should also do searching through roles, and the audit log too. I'd like it to use buttons and pages instead of commands as I think that would be more user friendly.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
done:
