### ISSUE TITLE
Spotify rich status

### ISSUE THREAD

**Issue by Croism** [Aliucord/plugin-requests#1035]
### Discord Account

Goos

### Plugin Description

I think Aliucord should have a plugin which implements  Spotify as a discord rich status. I've noticed that I cannot get Spotify to display as my activity status no matter what I do. 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by SevastianGit** [comment]
Can't you just use [Kizzy](https://github.com/dead8309/Kizzy)?

P.S.: Did you turn on "Device Broadcast Status" in Spotify settings?

**Comment by Juby210** [comment]
Kizzy is a selfbot don't use it.
![image](https://user-images.githubusercontent.com/31005896/236437134-822d6422-b157-4eae-9d9c-9d0c307447c0.png)

And this is a stock feature. You have to enable "Display Spotify as your status" in Discord Connections and "Device Broadcast Status" in Spotify settings and then try to pause/play or change song while using Discord.
