### ISSUE TITLE
Delete Embeds

### ISSUE THREAD

**Issue by void6670** [Aliucord/plugin-requests#1036]
### Plugin Description

It would be cool if we had the option to delete Embeds like on PC!

### Go into more detail...

when you send a message with embed and then you long click it it shows a button to delete Embeds

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by void6670** [comment]
actually you have other things to worry about so this isn't that Needed so it's fine

**Comment by SevastianGit** [comment]
This plugin already exists and works perfectly for me
https://github.com/c10udburst-discord/aliucord-plugins
