### ISSUE TITLE
New Discord Fonts

### ISSUE THREAD

**Issue by TermuxMonet** [Aliucord/plugin-requests#1038]
### Plugin Description

Replacing old Discord fonts with the ones from Latest Discord Releases, such as using GG Sans instead of Whitney.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
can't you just use Themer

**Comment by hmm-monke** [comment]
Yes, the only issue is that some text gets misaligned but that can just be ignored.
