### ISSUE TITLE
BetterRoleColor

### ISSUE THREAD

**Issue by Robiimadot** [Aliucord/plugin-requests#1039]
### Discord Account

Robi_imadot#7510

### Plugin Description

Adds users role colors everywhere it can.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
> I did indeed check to make sure my plugin request is original!

Already exists: https://github.com/zt64/aliucord-plugins/raw/builds/RoleColorEverywhere.zip
