### ISSUE TITLE
Play YT videos natively hehehe

### ISSUE THREAD

**Issue by cyan-2048** [Aliucord/plugin-requests#104]
### Discord Account

Cyan#0101

### Plugin Description

Play YT videos on the Aliucord app without leaving the app.... just like in Discord PC lol

### Go into more detail...

idk, i just don't want to open YouTube Vanced everytime someone sends me a YT video...

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ow0x** [comment]
this feature would be really useful honestly. +1.

**Comment by Vendicated** [comment]
Done. https://github.com/Vendicated/AliucordPlugins/blob/main/PlayableEmbeds/README.md
