### ISSUE TITLE
ANSI text viewer

### ISSUE THREAD

**Issue by GreenpeaceKT** [Aliucord/plugin-requests#1044]
### Discord Account

GreenpeaceKT#4042

### Plugin Description

A plugin that we can see ANSI codeblock color.

### Go into more detail...

Color the characters and the background of the characters like you would on a PC, and make the colors visible on Android.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
- #662
