### ISSUE TITLE
Play audio files without having to leave Aliucord app

### ISSUE THREAD

**Issue by cyan-2048** [Aliucord/plugin-requests#105]
### Discord Account

Cyan#0101

### Plugin Description

yeah the title, heck add support for txt files as well!

### Go into more detail...

some weirdo wont stop sending me voice messages on discord

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
@zt64 is on it

**Comment by jedenastka** [comment]
[AudioPlayer](https://discord.com/channels/811255666990907402/845784407846813696/982322262013280307) now exists.
