### ISSUE TITLE
A plugin that converts newer discord features to aliucord

### ISSUE THREAD

**Issue by Red4048** [Aliucord/plugin-requests#1051]
### Plugin Description

It would be cool if there was a plugin that converted the newer discord plugins into aliucord (which is made on a older discord version), i like the new discord but i hate the new ui on tablets, i want the old ui (which is on aliucord) on the new discord but i couldnt find anything for it so how about putting the new features on old discord?

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
this is a question not a plugin request

**Comment by hmm-monke** [comment]
The new tablet ui is actually how the tablet ui used to be on Android before tabs ruined it.
