### ISSUE TITLE
Add newer emojis such as 🫶 to aliucord

### ISSUE THREAD

**Issue by FangOnGitHub** [Aliucord/plugin-requests#1055]
### Discord Account

Fang#1401

### Plugin Description

Aliucord still uses the old discord emoji picker which doesn't have newer emojis such as 🫶🫴🫳🤲 and a bunch of other emojis.

The plugin request I want to make is to add these emojis to the old emoji picker, or import the new picker to aliucord.

And while you're at it, it would be dope if it is possible to add the new emoji icons as well. The old ones look quite ugly. Though this wouldn't be a priority.

### Request Agreement

- [x] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
Already exists, https://github.com/Juby210/Aliucord-plugins/raw/builds/NewEmojis.zip
