### ISSUE TITLE
Disable linked number

### ISSUE THREAD

**Issue by GreenpeaceKT** [Aliucord/plugin-requests#1057]
### Discord Account

GreenpeaceKT#4042

### Plugin Description

Prevent phone app from opening when pressing digits

### Go into more detail...

![Screenshot_20230514_225136](https://github.com/Aliucord/plugin-requests/assets/68542998/8f18cf27-4140-400e-90a3-2d5a9eed51df)
![Screenshot_20230514_171142](https://github.com/Aliucord/plugin-requests/assets/68542998/a94ca647-80ad-4bb9-9b7d-e90eae4ec56f)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
> I did indeed check to make sure my plugin request is original!

https://github.com/zt64/aliucord-plugins/raw/builds/NoLinkify.zip
