### ISSUE TITLE
Channel Permission Viewer

### ISSUE THREAD

**Issue by Komos63** [Aliucord/plugin-requests#1059]
### Discord Account

Komos#4608

### Plugin Description

I think a plugin which shows you which roles and members have access to a specific channel would be useful. A similar plugin already exists for BetterDiscord, it'd also be nice if it was compatible with the ShowHiddenChannels plugin.

### Go into more detail...

I think it should have an option when long-pressing on a channel which says something along the lines of "Permission Viewer" which opens a new GUI. This GUI could say something like "Allowed Users: Komos#4608, Allowed Roles: Admins".

This would be very useful in combination with the ShowHiddenChannels plugin.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by mantikafasi** [comment]
already exists

https://github.com/wingio/plugins/raw/builds/ShowPerms.zip
