### ISSUE TITLE
Chat GPT API

### ISSUE THREAD

**Issue by luhvmelody** [Aliucord/plugin-requests#1061]
### Discord Account

mintpuddle#9847

### Plugin Description

A plugin to add a chat gpt-linked client bot for quick information! 

### Go into more detail...

I know theres already an API bot, but we all know chatgpt is pretty cool. Just make it to where you can do like /chatgpt and ask a question or smnthn. Itd be pretty cool.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
future ref: https://github.com/xtekky/gpt4free

**Comment by WitherredAway** [comment]
maybe clyde support will be a better idea

**Comment by OmegaSunkey** [comment]
duplicate of #1034
