### ISSUE TITLE
Open discord links in Aliucord

### ISSUE THREAD

**Issue by NotJustKan** [Aliucord/plugin-requests#1062]
### Discord Account

JustKan #6801 

### Plugin Description

It would allow aliucord users to stay in discord when clicking a discord message/channel link, thats it.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
change the link handler for discord urls in system settings

**Comment by hmm-monke** [comment]
Set your system settings correctly
