### ISSUE TITLE
Export/Import favo(u)rite emojis

### ISSUE THREAD

**Issue by kissingboys** [Aliucord/plugin-requests#1068]
### Plugin Description

With this plugin You can export/impoert favorite/favourite emojis, you can export favorite/favourite emojis as json maybe and other mod like Vendetta would have a counterpart so you can import favorite/favourite emojis from Aliucord to other mod.

### Go into more detail...

Someone suggested a plugin on Vendetta server to backup or restore favorite/favourite emojis meant to allow other mods to backup or restore favorite/favourite emojis from other mods, if you do this first on aliucord you can do it first then they'd follow they'd make a counterpart I think

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
EmojiUtility
