### ISSUE TITLE
UseePFP?

### ISSUE THREAD

**Issue by MarddleDoo12** [Aliucord/plugin-requests#1072]
### Discord Account

Marddle(Simp de Yuri)#3021

### Plugin Description

It would be a good idea to have a plugin that is literally like UserBG but for profile photos, and I know it's useless, BUT IT IS AESTHETICLY BEAUTIFUL.

### Go into more detail...

You can do the same as with UserBG, only changing it to PFP

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by MarddleDoo12** [comment]
UserPFP* jejeje

**Comment by OmegaSunkey** [comment]
https://github.com/OmegaSunkey/awesomeplugins/raw/builds/UserPFP.zip done
