### ISSUE TITLE
@everyone ping

### ISSUE THREAD

**Issue by OLD-H28EVR** [Aliucord/plugin-requests#1073]
### Discord Account

StefanS#2614

### Plugin Description

It should be a plugin that takes every single persons name in a server and individually pings them. So like a @everyone but without perms.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by void6670** [comment]
that abuses the api and it's also not a great plugin so it's safe to say it won't be added (next time read the rules)

**Comment by OLD-H28EVR** [comment]
> that abuses the api and it's also not a great plugin so it's safe to say it won't be added (next time read the rules)

Finee
