### ISSUE TITLE
Hide blocked user 

### ISSUE THREAD

**Issue by Kursted** [Aliucord/plugin-requests#1074]
### Plugin Description

I think a lot of people would benefit from a plugin that completely hides a individual when they get blocked especially in the server list. I personally don't want to see someone online that I blocked I don't want to see them at all! 

### Go into more detail...

Hide blocked user profile from showing in channel list

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by wingio** [comment]
> I did indeed check to make sure my plugin request is original!

https://github.com/lexisother/AliucordPlugins/raw/builds/HideBlockedMessages.zip

**Comment by Kursted** [comment]
> > I did indeed check to make sure my plugin request is original!
> 
> https://github.com/lexisother/AliucordPlugins/raw/builds/HideBlockedMessages.zip

and this is messages not server list
**> > I did indeed check to make sure my plugin request is original!
**
