### ISSUE TITLE
Auto-Translator

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [Aliucord/plugin-requests#1076]
### Discord Account

ALMIGHTY#9013

### Plugin Description

i think a plugin which automatically translates the language when we scroll. We can input that if the text isnt in the selected language it will auto translate it when we scroll. For example i gone into a russian server i checked a channel as the whole chat is russian it will auto translate new messages when types and old will be translated when we will scroll

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by StupidRepo** [comment]
~~Will attempt to make~~ (not)

**Comment by rushiiMachine** [comment]
Could be pr'd into the existing Translate plugin instead (the auto part)
