### ISSUE TITLE
Discords new markdown support

### ISSUE THREAD

**Issue by VenomousSteam81** [Aliucord/plugin-requests#1077]
### Discord Account

VenomousSteam81#7772

### Plugin Description

A plugin that displays Discords new markdown support.

### Go into more detail...

Example:

\# Hello

Should show

# Hello

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Poopooracoocoo** [comment]
Duplicate of #1071
