### ISSUE TITLE
customizable welcome message password lock for discord

### ISSUE THREAD

**Issue by FunfettyOnYt** [Aliucord/plugin-requests#1078]
### Discord Account

Funfetty#8288

### Plugin Description

A NEW customizable password lock to unlock discord so your secret egirl servers that you in dont get leaked to the public... Subscribe to FunfettyYT

### Go into more detail...

maybe with optional settings like tap the screen 3 times to be able to see the type password text and if you dont tap 3 times you would be able to see anything and it will show a black screen (so people think discord just does not work for the person) and if you dont get the password that you set open it will close your app (make everything customizable even if the password button will be in top right or middle or bottom etc. the length of your password can be chosen, maybe maybe make it so you have put your Gmail in or a number combo something like that) also you could add custom text that say put in password or anything you type

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [x] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
#92
