### ISSUE TITLE
Add sed support

### ISSUE THREAD

**Issue by WitherredAway** [Aliucord/plugin-requests#1079]
### Discord Account

wit#5417

### Plugin Description

Discord has a neat little easter egg where it supports sed substitution on PC and the new DiscordRN mobile client. Where you can send `s/<from>/<to>` to quickly edit the last message and replace `<from>` to `<to>`
A plugin that adds this support to aliucord would be beyond awesome

### Go into more detail...

Here is an example of sed substitution on DRN:
https://github.com/Aliucord/plugin-requests/assets/81734495/88acc7d3-89c9-415f-a34e-d6d6d3c6132e

Unfortunately the old client used by aliucord does not. It's such a cool useful feature, i hope its support is added to aliucord <3

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by WitherredAway** [comment]
For anyone seeing this thru the channel, it didn't render parts of the issue because github syntax, so pls open the issue💀💀💀

**Comment by WitherredAway** [comment]
rushii supremacy

**Comment by WitherredAway** [comment]
not to put too much pressure on you because implementing as is would already be super awesome, but would it be possible to implement full sed support with regex, flags, etc?

**Comment by WitherredAway** [comment]
ok, I'm happy with just the base support 👍

**Comment by WitherredAway** [comment]
> https://discord.com/channels/811255666990907402/811275334342541353/1111593320678948865
@ mantikafasi#4444

bro it's useful and fun af man idc about txnor sex hacks. i hyperfixated on this so hard that i made an entire guide on it:

# Sed substitution
## Quickly amending your last message

You can edit/amend your last message INSTANTLY using a discord feature called sed substitution. It's super underrated, and most people don't even know about it even though it's been in discord since the beginning!

## Syntax
`s/<from>/<to>`

## How to use?
To use this, just send a message complying with the syntax! Change `<from>` to anything you want to replace and `<to>` to anything you want to replace to! **This will instantly edit your last message and replace the first occurence of `<from>` to `<to>`!** See the attached videos for examples.

## Tips & Tricks
- It only replaces the first occurence of `<from>`!
- Yes, you can keep `<to>` empty to REMOVE `<from>`! But `<from>` can't be empty. *See 2nd attachment!*
- To replace `/`, you have to escape it using `\`. 
    - e.g. `i love cats / dogs` -> **`s/\/and`** -> `i love cats and dogs`. *See 3rd attachment!*
- You can replace newlines, but there must be a character before the line break otherwise it wont work. *See 4th attachment!*
- You can DELETE the last message entirely, just use `s/<entire content of last message>/`. *See 5th attachment!*

## Important
- It does NOT work on the old android client! Update your discord if it isn't working for you!

## Examples
https://media.discordapp.net/attachments/1111005653612376165/1111418787825209404/VID_20230526_034938.mp4
https://cdn.discordapp.com/attachments/780212446509006868/1111424106798252112/VID_20230526_034955.mp4
https://cdn.discordapp.com/attachments/780212446509006868/1111424107205115944/VID_20230526_035011.mp4
https://cdn.discordapp.com/attachments/780212446509006868/1111424108752814110/VID_20230526_035028.mp4
https://cdn.discordapp.com/attachments/780212446509006868/1111424109289676872/VID_20230526_035042.mp4

**Comment by WitherredAway** [comment]
pls i beg ty <3

**Comment by showierdata9978** [comment]
+1, i just tried to use sed and, surprisingly it failed! Sed is just easier then editing sometimes

**Comment by WitherredAway** [comment]
ily \@grzesiek11

**Comment by jedenastka** [comment]
Recently done as part of [my Sed plugin](https://gitlab.com/Grzesiek11/sed-aliucord-plugin) ([#plugins-list](https://discord.com/channels/811255666990907402/811275162715553823/1208205954949062778)).

**Comment by jedenastka** [comment]
> not to put too much pressure on you because implementing as is would already be super awesome, but would it be possible to implement full sed support with regex, flags, etc?

This is planned for v1.1 btw (at least the `g` flag and regex)

**Comment by WitherredAway** [comment]
> > not to put too much pressure on you because implementing as is would already be super awesome, but would it be possible to implement full sed support with regex, flags, etc?
> 
> This is planned for v1.1 btw (at least the `g` flag and regex)

Omfg that would be awesome

**Comment by TheGamer1002** [comment]
Hate to necro, but was this dropped? It seems to be missing as of the latest commit (adf80a8).

**Comment by OasisVee** [comment]
> Hate to necro, but was this dropped? It seems to be missing as of the latest commit (adf80a8).

exists now https://discord.com/channels/811255666990907402/845784407846813696/1208374558311317584

**Comment by TheGamer1002** [comment]
Perfect, thank you!
