### ISSUE TITLE
Add new markdown support 

### ISSUE THREAD

**Issue by 0xBanditt** [Aliucord/plugin-requests#1088]
### Discord Account

BigBootyBandit#9140

### Plugin Description

A plugin that shows and support Discord's new markdown.
Like 
# biggest text
### more smaller
- this should be a point
![IMG_20230530_222739](https://github.com/Aliucord/plugin-requests/assets/92172811/4e9ee7fa-e2e5-4270-aa5d-4a3469ea462a)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
>  I did indeed check to make sure my plugin request is original!

**Comment by 0xBanditt** [comment]
> > I did indeed check to make sure my plugin request is original!

Boii you're fast asf
