### ISSUE TITLE
Sync light/dark mode based on system 

### ISSUE THREAD

**Issue by Rosentti** [Aliucord/plugin-requests#1089]
### What is it that you'd like to see?

The old app doesn't have a function to sync the currently active theme by system. I use dark mode with a timer, so I would like it if aliucord could sync with the system. The new discord mobile app does do it, but it runs horribly and the text stays white when switching to light mode.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by ghost** [comment]
I +1 This. It's a really cool idea! Someone do take this up!

**Comment by sergolon** [comment]
I have the same problem. I hope someone create that plugin

**Comment by rushiiMachine** [comment]
- #386
