### ISSUE TITLE
Use Android Emojis instead of discord 

### ISSUE THREAD

**Issue by SOUL1INFINITY0** [Aliucord/plugin-requests#1090]
### Discord Account

!  Ray#5898

### Plugin Description

Title Explains it pretty well

### Go into more detail...
Details? like in iOS discord uses iOS emojis not Discord's (Discord emojis suck ngl)
ㅤㅤㅤ

### Request Agreement

- [ ] I have made sure my plugin is possible and abides by the rules!

### ​

- [ ] I did indeed check to make sure my plugin request is original!

**Comment by SOUL1INFINITY0** [comment]
Updates???

**Comment by SOUL1INFINITY0** [comment]
...

**Comment by Reinified** [comment]
soo.. #200 requests the same thing.

**Comment by SOUL1INFINITY0** [comment]
why is this closed???

**Comment by rushiiMachine** [comment]
maybe try reading the last comment
