### ISSUE TITLE
No useless buttons

### ISSUE THREAD

**Issue by ghost** [Aliucord/plugin-requests#1091]
### Discord Account

s5_5#4051

### Plugin Description

I think it would be very useful if someone could remove these useless buttons from the chatbox like the gift button and the new thread button(like in the image).
![RDT_20230601_092431521336386232131300](https://github.com/Aliucord/plugin-requests/assets/78297551/308ddb03-71fb-4785-822c-66c78fe522a9)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by void6670** [comment]
https://github.com/X1nto/AliucordPlugins/blob/master/plugins/LayoutController
