### ISSUE TITLE
Better Copying

### ISSUE THREAD

**Issue by void6670** [Aliucord/plugin-requests#1092]
### Discord Account

! Voidii#2870

### Plugin Description

So i have been having this 'issue' well not really an issue but it's annoying. so when you copy something on discord for example emojis it copies just the name without the ':' and other text for example with text like 
**hello** it copies it as hello without the ** i wish there was a plugin to fix this it would be useful 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by TymanWasTaken** [comment]
https://github.com/Juby210/Aliucord-plugins#viewraw already exists
