### ISSUE TITLE
Restore Codeblock functionality

### ISSUE THREAD

**Issue by ghost** [Aliucord/plugin-requests#1093]
### Discord Account

TGP#4846

### Plugin Description

A plugin that restores the intended Codeblock function would be cool.

### Go into more detail...

Since yesterday codeblocks display as if I used ` instead of ```. That seems to happen on other unofficial clients as well suddenly, but still works on official.  So I guess discord changed something that needs to be backported from a official discord.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
Nothing has changed, especially on Aliucord as markdown is rendered client side (obviously)

**Comment by ghost** [comment]
Hmm I just tested a bit further, I have to format like this to get a codeblock: 
```
Text
```

However it worked previously without the gap. Should I change the plugin request or close this one and make a new, where I request a plugin that makes Codeblocks work with just ``` without the gap?
Edit: I'll attach a screenshot, because GitHub puts my explanation in a codeblock
![Screenshot_20230604-223415_Chrome](https://github.com/Aliucord/plugin-requests/assets/86961834/e6f4f715-3cc2-4cc1-9d39-e28a55188e73)

**Comment by rushiiMachine** [comment]
Newlines between \`\`\` is required to form a full size codeblock and is correct.
Discord desktop appears to not require it however it isn't standard markdown, so no this won't be fixed in core and I don't see the point of this as a plugin

**Comment by ghost** [comment]
The official discord client on mobile also seems to not require it. If users on official clients write a Codeblock without the gap, it looks fine to them, but doesn't on Aliucord. So I'd say the point of a plugin for this would be to ensure that message formatting stays the same between clients

**Comment by rushiiMachine** [comment]
ig @wingio add to that simpleast plugin then

**Comment by wingio** [comment]
https://github.com/Juby210/Aliucord-plugins#bettercodeblocks fixes that
