### ISSUE TITLE
RAM Reducer Plugin

### ISSUE THREAD

**Issue by Curtesy** [Aliucord/plugin-requests#1098]
### Discord Account

Curtis#2795

### Plugin Description

The plugin would reduce ram usage on aliucord which is more convenient for Phone Gamers because ram is sometimes a issue to most phones. (Aliucord wastes around 300-500 mbs of ram or 100-300 mbs of ram it depends)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hmm-monke** [comment]
Use OpenCord
![troll-troll-face](https://github.com/Aliucord/plugin-requests/assets/60791542/dc83ddb3-3780-4506-8eb2-a7bcef04c3bd)

**Comment by rushiiMachine** [comment]
![Screenshot_20230608-064830](https://github.com/Aliucord/plugin-requests/assets/33725716/b0d940ac-a06d-496a-bd2f-8c6d8a00f8e5)

**Comment by Curtesy** [comment]
Okay
