### ISSUE TITLE
plugin suggestion - Disables automatically getting kicked from a DM voice call after 5 minutes.

### ISSUE THREAD

**Issue by Jshimkus99** [Aliucord/plugin-requests#1099]
### Plugin Description

a plugin like vencord where it disables the dm call idle kick timer  if you are alone , i think its currently like 5 mins alone but with vencord it disables that altogether and figured id suggest that for here as well.

### Go into more detail...

its a bit more convenient if i can call my s/o and wait for them to join or if the call drops randomly which happens alot they wont need to spam me with calls to get one going again they can just wait without being kicked.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
I already tested this; the idle disconnect does not exist on discordkt

**Comment by Maleficent-Magik** [comment]
This only exists on PC, you are automatically kicked after 12 or 24 hours of voice.  I was live on Discord streaming music on youtube and the next day I was disconnected...
