### ISSUE TITLE
Remove Call and Video buttons in profile

### ISSUE THREAD

**Issue by GangsterFox** [Aliucord/plugin-requests#11]
### Description
Self-explanatory plugin, just removes call and video buttons from the user profile
### More info
Just, remove the call and video button.

---

- [x] I checked if this plugin wasn't already requested.

**Comment by Swishilicous** [comment]
CallConfirmationDialog was created for this reason. You can use that for the time being.

**Comment by GangsterFox** [comment]
I can use that but I really just want the buttons gone as my friend also doesn't like them. Its in a way a better form of CallConfirmationDialog by just removing the buttons on profiles entirely

**Comment by Juby210** [comment]
It is a feature of [HideBloat](https://github.com/X1nto/AliucordPlugins/raw/builds/HideBloat.zip)
