### ISSUE TITLE
Video filters/backgrounds and inapp voice changer 

### ISSUE THREAD

**Issue by rickdtc** [Aliucord/plugin-requests#110]
### Discord Account

PUTDEMKNOCK#2006

### Plugin Description

A plugin that enables us to apply video backgrounds like zoom or just filters like black and white, sepia, etc. and a voice changer.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
Audio & Video processing are done by libdiscord, a native (C) library, so a plugin can not do this. Additionally, Discord teased video backgrounds themselves so this plugin would be pretty obsolete
