### ISSUE TITLE
Experimental flags

### ISSUE THREAD

**Issue by madonchik123** [Aliucord/plugin-requests#1100]
### Discord Account

madonchik123#6466 

### Plugin Description

It's gonna be like betterdiscord plugin or what It was that let's you turn on and off experimental flags like the super reactions folders and etc

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
experiments plugin already exists

**Comment by madonchik123** [comment]
Hmm I didn't see it in plugins list could you please say it's name

**Comment by Fuzuki785** [comment]
https://github.com/Juby210/Aliucord-plugins/raw/builds/Experiments.zip
