### ISSUE TITLE
BetterUpdateClient

### ISSUE THREAD

**Issue by joeyoropesa-dev** [Aliucord/plugin-requests#1104]
### Plugin Description

The plugin that basically in some way building a new Discord version and it's features in the kotlin-based version of Discord.

### Go into more detail...

The old type of plugin for current supported Aliucord client that can implement some of new features from the latest Discord like ability to open "id:customize" and "id:browse" and some other features that is available on react-native based latest Discord and in the future update (if it's possible) to add new features from react-native based latest Discord to this old-kotlin-based Aliucord currently supported latest client version.

Most servers are moved to those features so selecting roles is not anymore possible without an PC or Website Web App/Latest Discord react-native based client apk

If this also requires that Aliucord apk must to patch more features like react-native framework support without replacing kotlin framework support, that could be done too - if that can be written once in the code, every next time when Discord releases an update can be patched very easly 🥰 - if you need a better explanations, feel free to ping me.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by void6670** [comment]
they will be added eventually people have asked for those features

**Comment by joeyoropesa-dev** [comment]
> they will be added eventually people have asked for those features

I don't hurry devs for this - let's this be done when it's done

Speaking from myself perspective, I would even give any money for this to happen - this plugin with the Aliucord team can make the future of Discord experience in Aliucord.

So everything the user have in the latest Discord React-Native we can have it using this Aliucord plugin and the future updated patch for Aliucord and Aliucord itself 🥰🥰🥰

I can wait as long as I need just to see this to happen one day.

**Comment by neko-astolfo-uwu** [comment]
Would be real stupit to add those features as a separate plugin. Core functionality gets added into the core part of Aliucord. Like display names, for me it works now.

**Comment by joeyoropesa-dev** [comment]
> Would be real stupit to add those features as a separate plugin. Core functionality gets added into the core part of Aliucord. Like display names, for me it works now.

Well, if Aliucord can and want to add all those features we have on latest Discord React Native like UI and similar features, well I would love to see that but I have a feeling that they don't want to do that for some reason so I hope at least someone can do it via plugin.

**Comment by void6670** [comment]
they most likely will be core features, also lets not text here anymore

**Comment by joeyoropesa-dev** [comment]
> they most likely will be core features, also lets not text here anymore

If they want it to add it as a core features - if they don't want, well we can't do nothing expect to some dev use thjs request and make those core changes by himself/herself/theirself.


Anyway, we're now closing this talk here.

**Comment by rushiiMachine** [comment]
Make separate plugin requests for each feature instead one global one with little details (lots of requests have already been made)

> If this also requires that Aliucord apk must to patch more features like react-native framework support without replacing kotlin framework support

This is not how patching works, we dropped the rewrite to support react native precisely because it's react native

**Comment by joeyoropesa-dev** [comment]
> Make separate plugin requests for each feature instead one global one with little details (lots of requests have already been made)
> 
> > If this also requires that Aliucord apk must to patch more features like react-native framework support without replacing kotlin framework support
> 
> This is not how patching works, we dropped the rewrite to support react native precisely because it's react native 

Just do kotlin core rewrite and add feature by feature from latest Discord React Native to the Kotlin-based base and use that as the base that will be used for future patching to the Aliucord instead of just injecting Aliucord. In Aliucord Core you can add many API and many features that exist in Discord


But the problem can be that devs don't want to work Discord job to add all features manually to the kotlin version of the app.

**Comment by neko-astolfo-uwu** [comment]
Please actually look into what Aliucord developers are doing and stop spamming a stupid github issue. If you want to communicate join the Discord server.

**Comment by joeyoropesa-dev** [comment]
So, instead of AliucordRN (React-Native), we can have modified Aliucord Kotlin-based core to have everything what latest Discord from react native have. If this is planned and it's in work progress, please let me know so I don't need to worry about this plugin rejection.

**Comment by Vendicated** [comment]
please read what was said.
