### ISSUE TITLE
Auto turn off the ping when replying

### ISSUE THREAD

**Issue by EnderNon** [Aliucord/plugin-requests#1105]
### Plugin Description

when you reply there's a function that lets you turn off pinging the person being replied. it says "@ on" or "@ off". it's default set to pings being on, and I'd like a plugin that will automatically set it to off. 

### Go into more detail...

make the ping set to be off by default

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by EnderNon** [comment]
yes i know its not original, however the last activity i could find on another issue page about this was nearly half a year ago

**Comment by kiriya-aoi** [comment]
Of course it's not original, `NoAutoReplyMention` exists already.

**Comment by EnderNon** [comment]
> Of course it's not original, `NoAutoReplyMention` exists already.

can't seem to find it anywhere w though

**Comment by EnderNon** [comment]
nevermind found it
