### ISSUE TITLE
AlwaysOnlineDiscord

### ISSUE THREAD

**Issue by JoseEncode** [Aliucord/plugin-requests#1106]
### Discord Account

Faz#6969

### Plugin Description

Just a simple plugin, it'll let you to stay online on the app even when you close it from the recent histories.

### Request Agreement

- [x] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
not possible
