### ISSUE TITLE
Auto Follow

### ISSUE THREAD

**Issue by Cojayca** [Aliucord/plugin-requests#1115]
### Discord Account

jake5743

### Plugin Description

I would like a plugin makes it possible to automatically follow people you marked by right clicking the user and also be able to deactivate it even when the user has left the server

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
you are creepy
