### ISSUE TITLE
Update adding friends thing

### ISSUE THREAD

**Issue by shovellergaming** [Aliucord/plugin-requests#1120]
### Plugin Description

since alot of people have the new usernames its impossible to friend them unless your in a server with them, so make it compatible with new usernames

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Infisreal** [comment]
https://github.com/Aliucord/plugin-requests/issues/1238

**Comment by jedenastka** [comment]
Tracked at https://github.com/Aliucord/Aliucord/issues/471.
