### ISSUE TITLE
Hide selected channels in servers

### ISSUE THREAD

**Issue by thecatontheceiling** [Aliucord/plugin-requests#1121]
### Discord Account

Lyssa#2721

### Plugin Description

a plugin that can hide any channel in a server that I want would be awesome, something like this already exists on RN and on desktop but not on aliucord
if anyone makes this I love you

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by neko-astolfo-uwu** [comment]
Or just mute the channel then turn on the option to hide muted channels.

**Comment by thecatontheceiling** [comment]
option to hide muted channels...?

**Comment by neko-astolfo-uwu** [comment]
Bultin Discord feature.
[Like this](https://media.discordapp.net/attachments/811263527239024640/1123896029696233573/Screenshot_20230629_103958.png)

**Comment by thecatontheceiling** [comment]
thanks astolfo, I have now confirmed I'm a dumbass

**Comment by thecatontheceiling** [comment]
@neko-astolfo-uwu I was thinking of something more like a list of channels that u just click and then be done with, manually muting them is so fricking tedious

**Comment by thecatontheceiling** [comment]
that also doesn't work on voice channels
