### ISSUE TITLE
Better Forum

### ISSUE THREAD

**Issue by MarddleDoo12** [Aliucord/plugin-requests#1122]
### Discord Account

Marddle(Simp de Yuri)

### Plugin Description

You know what I mean:
Functional forums for kotlin, since RN when putting the tags bugs Kotlin, causing them to not be able to create forums.

### Go into more detail...

I don't know how it could be done, but I suppose that simply having the labels as in RN would solve the problem 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
> I did indeed check to make sure my plugin request is original!

#1081
