### ISSUE TITLE
Selfbot

### ISSUE THREAD

**Issue by TheScriptShowcaser** [Aliucord/plugin-requests#1124]
### Plugin Description

Makes yourself into a bot, prefix would be changeable and here are some command ideas

,help
,credits
,kick
,ban
,spam [Number] [Text]
,prefix
,settings

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
We do not support selfbots, it is against our rules and Discord ToS as well.
