### ISSUE TITLE
Always typing

### ISSUE THREAD

**Issue by defautluser0** [Aliucord/plugin-requests#1125]
### Discord Account

zorro_no

### Plugin Description

A plugin that makes you always type would be cool.

### Go into more detail...

It would be a / command(e.g. /type) and it would just send typing requests every like 8000ms to discord.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
Automating requests to Discord API is considered as selfbotting.

**Comment by defautluser0** [comment]
Well tell that to the like 1500 youtubers that say it's safe

**Comment by TymanWasTaken** [comment]
Because youtubers are the most reliable source of information
Besides, that would just be annoying to literally everyone, what's the point

**Comment by defautluser0** [comment]
Idk, I can do that on pc, why not on mobile

**Comment by rushiiMachine** [comment]
1. Your phone is not on 24/7
2. Android kills background apps
3. It is dumb
