### ISSUE TITLE
Inspect element.

### ISSUE THREAD

**Issue by defautluser0** [Aliucord/plugin-requests#1129]
### Plugin Description

It would be cool to have inspect element in discord mobile.

### Go into more detail...

You would press a button in the ui and it would open inspect element to change stuff(like in pc with ctrl+shift+I). It would also have the console and all that stuff like in pc.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
https://play.google.com/store/apps/details?id=com.appsisle.developerassistant&hl=en_US&gl=US
