### ISSUE TITLE
Always make gifs playing

### ISSUE THREAD

**Issue by Federico-IT** [Aliucord/plugin-requests#113]
### Discord Account

MaxData77#2131

### Plugin Description

A simple plugin that make always the gifs playing (animated server logo, animated pfp, etc...). And maybe add an option that allows to disable a specific gif, for example disable always animated pfp, but not the animated server logo. (Sorry for my bad english)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by NatSepruko** [comment]
Duplicate of #25
