### ISSUE TITLE
New Discord

### ISSUE THREAD

**Issue by qwertysucks** [Aliucord/plugin-requests#1135]
### Discord Account

axolotls70#0000

### Plugin Description

So basically, new Discord features in 126.21! Should be easy..
- Pronouns
- New badges such as Active Dev and "Originally called name#0001"
- Display Name
- New message embeds
- New image system (the multiple image thing)
- Remixing Images
- Activities
- Nitro Basic
More soon once I find them out lol

### Go into more detail...

Definitly good lol

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by C10udburst** [comment]
> Should be easy

💀

**Comment by Vendicated** [comment]
duplicates + stick to one request per issue
