### ISSUE TITLE
Grammar Correction Button

### ISSUE THREAD

**Issue by Saulildo** [Aliucord/plugin-requests#1136]
### Discord Account

noobpiayer

### Plugin Description

I suggest developing a Discord plugin that introduces a button adjacent to the emoji on the keyboard. This feature would enable users to forward their message to OpenAI's AI for grammar correction, subsequently replacing the original message with the AI's revised version.

### Go into more detail...

Advantages:
1. User-friendly: Leveraging OpenAI's AI for grammar rectification is far more straightforward than manually cross-referencing keywords or constructing tables.
2. Enhanced grammar quality: The AI's corrections are likely to result in superior grammar compared to manual adjustments.

Points to ponder:
1. Expense: To alleviate potential worries about costs, it would be advantageous to offer an option for users to enter their own API key. This allows users to decide whether they wish to pay for the service.
2. Unsuitable content: It's crucial to remember that the AI will not correct the grammar of a message containing inappropriate content.

The task of implementing this plugin should not be excessively difficult. I advise using the gpt-3.5-turbo model for grammar correction.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
make your own gboard
