### ISSUE TITLE
Emoji Replace

### ISSUE THREAD

**Issue by xinra69** [Aliucord/plugin-requests#1137]
### Discord Account

noriuko#0000

### Plugin Description

A plug-in that replaces the standard discord emojis to look like iPhone ones (or optional, as other brands like Google, Samsung etc) (such a plugin already exists for BD on pc). 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ragxxv** [comment]
You will be redirected here #22

**Comment by Patty014** [comment]
nice
