### ISSUE TITLE
SearchGoogle

### ISSUE THREAD

**Issue by blank85** [Aliucord/plugin-requests#1138]
### Discord Account

blan.k

### Plugin Description

A plugin with command like if you put /SearchGoogle and you put a word to search it will sewrc5on google

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by blank85** [comment]
I mean "search" not "sewrc5on" sorry :trolley:

**Comment by Vendicated** [comment]
aliucord already has this built in:
1. press the home button
2. open your browser
3. enter in searchbar
