### ISSUE TITLE
edit someone appearance

### ISSUE THREAD

**Issue by GabrielGreenWolf** [Aliucord/plugin-requests#1139]
### Discord Account

GabrielGreenWolf

### Plugin Description
EDITED: I think I have provided unclear details.

any plugin that I could hide someone without blocking.

Or I could edit someone appearance into invisible. You can edit locally someone appearance.

I need that plugin

### Go into more detail...

Click someone pfp where you could see his profile then click on the three dots. You can change their appearance.

Profile picture (Pfp)
Username
Banner
Message color (change the color of the letters)
About Me

But for me, I actually want to make them transparent because personally, I don't want to see someone with a weird appearance. You can edit the appearance of your friends. For example, you can change my username to "Gaybriel" and my profile picture to a femboy pfp. I hope this plugin is useful.

You can't change roles or tags.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
If you want to hide someone's messages you can block them + use hideblockedmessages 

and I don't believe that type of plugin would be allowed ever since some incidents lol
