### ISSUE TITLE
A plugin to enable to sort messages by new or old in message search

### ISSUE THREAD

**Issue by rickdtc** [Aliucord/plugin-requests#114]
### Discord Account

PUTDEMKNOCK#2006

### Plugin Description

A plugin that helps us to sort messages by new or old in message search like in desktop.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
#72  
You didnt check

**Comment by Reinified** [comment]
copy of #72
close when

**Comment by rickdtc** [comment]
close now
