### ISSUE TITLE
Plugin that shows total call time for dms

### ISSUE THREAD

**Issue by Daniel36191** [Aliucord/plugin-requests#1140]
### Discord Account

daniel3619

### Plugin Description

Would track total hours that have been done in dms.
Like steam total play time.

### Go into more detail...

This should be possible because the total call time for part calls are shown.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
just request your data package in discord settings and it'll contain it
