### ISSUE TITLE
Replace any message containing tiktok.com with tiktxk.com

### ISSUE THREAD

**Issue by OnMyChown** [Aliucord/plugin-requests#1151]
### Plugin Description

Made the mistake of posting js code earlier for this request. Makes it seem more complicated than it is.

All it does is looks to see if any message you're about to send contains tiktok.com and replaces it with tiktxk.com, which gives better embedding in discord.

Code is still below if it helps:
https://raw.githubusercontent.com/spinfal/enmity-plugins/master/dist/BetterTiktokEmbeds.js

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
you can use the TextReplace plugin to replace tiktok.com with whatever you need
