### ISSUE TITLE
A slash command which deletes the most recent message you sent

### ISSUE THREAD

**Issue by ISMAILTRO** [Aliucord/plugin-requests#1153]
### Discord Account

Ismailtro#0000

### Plugin Description

So just a slash command that deletes your most recent sent message in a server, sounds total BULLCRAP right? Well this will be pretty useful at certain times, when you say something bad and you want to quickly delete it, just type /delete, will be a pretty cool feature, please👍.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
long press the message and click delete....
