### ISSUE TITLE
Locally change/hide server/guild icon

### ISSUE THREAD

**Issue by JapanYoshi** [Aliucord/plugin-requests#1156]
### Plugin Description

Use case: You’re in a Discord server, but they have an annoying server icon (e.g. fake notification dot, fake voice chat dot, colors that are too vivid). You don’t want to leave the server, but don’t want to see that icon either.

Function: When you long press a server, the context menu will let you locally change the server icon or revert it to the default alphabetical one.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by void6670** [comment]
https://github.com/mantikafasi/AliucordPlugins/blob/builds/EditServersLocally.zip
