### ISSUE TITLE
Mute/block/censor words (word blocklist)

### ISSUE THREAD

**Issue by JapanYoshi** [Aliucord/plugin-requests#1157]
### Plugin Description

**Use case:** You want to avoid all mentions of a certain key word (e.g. a meme you hate, a slur, people who are dead to you) on Discord.

**Behavior:** A plugin could do one of these:

1. replace the text using a text or RegEx replacement
2. hide messages containing banned words as if they were from blocked users
3. spoiler any banned words

### Go into more detail...

This is based on the functionality of blocked words on Xkit, an extension suite for Tumblr.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by void6670** [comment]
just use the text replace plugin

**Comment by JapanYoshi** [comment]
The RegEx part seems not to be working though.
