### ISSUE TITLE
Avatar Mention

### ISSUE THREAD

**Issue by Cynosphere** [Aliucord/plugin-requests#116]
### Plugin Description

Tapping user's avatar mentions them instead of opening profile. Long press still opens profile. Feature from way older Discord Android versions.

cutthecord patch for reference: https://gitdab.com/distok/cutthecord/src/commit/44cd92fcdc5bddf525cf4c11429ac68d3741e9fb/patches/profilemention/1371.patch

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
I'm gonna make this

**Comment by zt64** [comment]
Done, https://github.com/zt64/aliucord-plugins/raw/builds/AvatarMention.zip
