### ISSUE TITLE
User Tracker

### ISSUE THREAD

**Issue by gzgmg4** [Aliucord/plugin-requests#1161]
### Plugin Description

Simple plugin which tracks a specific user's status and when it switches every minute (online, idle, dnd, offline)

### Go into more detail...

This can also possibly turn the status data into a visual graph to give you a general idea of when that user is online. It might be a little confusing for users who aren't familiar to look at something like "user#1234 went online on 2023-07-08T01:52:03:056" I was gonna suggest that it would also take the timestamps of that user's messages, but API abuse yadda yadda and whatnot

I believe this plugin can be possible as long as you keep Aliucord open, where it can scan a user's profile on the app every minute to check what their status is.

It can be very helpful against raiders or something.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [x] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
stop being weird
