### ISSUE TITLE
CustomRPC

### ISSUE THREAD

**Issue by RejectedSmile** [Aliucord/plugin-requests#1163]
### Discord Account

rejectedsm

### Plugin Description

CustomRPC would be a plug-in that would allow the user to has a custom "playing game" in the profile that people could see and I would have options to put buttons that send you to certain social media or server or even a image of a dog idk I'll put a Link for a better description 

https://youtu.be/0_pAg_gV6Kw?t=579

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
rpc is not possible on mobile

**Comment by RejectedSmile** [comment]
> 

I saw in the server that it definitely was possible so can this be opened back up please
