### ISSUE TITLE
Text selection like on pc

### ISSUE THREAD

**Issue by SteveeTheCreeper** [Aliucord/plugin-requests#1164]
### Discord Account

stevethecreeper

### Plugin Description

So, there is this problem on mobile when when you want to only copy a small sentence or a word from someone's message you end up copying the whole thing, so maybe make a plugin that can be used to copy only something that you select?

### Go into more detail...

For an example, on websites if you want to copy something you can just select what you want to copy
Maybe make the same for mobile

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by neko-astolfo-uwu** [comment]
Use ViewRaw

**Comment by SteveeTheCreeper** [comment]
Alright thanks
