### ISSUE TITLE
PDF Viewer

### ISSUE THREAD

**Issue by kirjorjos** [Aliucord/plugin-requests#1165]
### Discord Account

kirjorjos#0

### Plugin Description

When you tap on a pdf attachment, it allows you to preview/open it without having to download it, then find and open it.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
kind of like a pdf viewer?
