### ISSUE TITLE
Escape Emojis

### ISSUE THREAD

**Issue by StupidRepo** [Aliucord/plugin-requests#1166]
### Requestor
Username: `unbeknownst_to_you`
Display Name: `Brad`
Discord UID: `1098644984875450488`

### Plugin Description

I feel like there should be a plugin that, upon sending a message, will add a backslash before all default emojis to escape them.

### Go into more detail...

I feel as though it'd be helpful so that then you can install an emoji font locally and have different default emojis, and so that discord can render the emojis as Unicode.

### Request Agreement

- [x] I have made sure my plugin is possible and abides by the rules!

### 

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
I'm fairly certain you can use TextReplace to match emojis with a regex and replace it with a backslash + matched content

**Comment by StupidRepo** [comment]
Thanks. Regardless of that, I'm going to see if i can make my own version
of this in a few hours.

**Comment by rushiiMachine** [comment]
textreplace or https://discord.com/channels/811255666990907402/861935147272110100/1141109437256445982

**Comment by StupidRepo** [comment]
Afaik, text replace can't add characters and keep the original match :)
