### ISSUE TITLE
HideUtils

### ISSUE THREAD

**Issue by GabrielGreenWolf** [Aliucord/plugin-requests#1169]
### Plugin Description

"A plugin designed to enable the hiding of individual users, channels, and/or servers," created by Arashiryuu for BetterDiscord.

### Go into more detail...

This special tool made by Arashiryuu for BetterDiscord helps you have more control over how you use Discord. It's like having a cool remote control for Discord.

With this tool, you can hide things you don't want to see on Discord. It's like making stuff disappear with a magic trick! You can hide certain people, chat groups, and even whole clubs.

Imagine you only want to see things on Discord that make you happy. You can use this tool to hide stuff you don't like, like chat rooms that are boring or people who bother you. It's also great if you want to focus and not get distracted.

Using this tool is really easy. It's like tidying up your toys and putting them in different boxes. You can organize your Discord just the way you like it.

And I'm begging you.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
All of this is essentially implemented either as a stock feature or a combination of plugins
users: block + HideBlockedMessages plugin
channels: mute + "Hide Muted Channels" option
servers: just leave

**Comment by GabrielGreenWolf** [comment]
> All of this is essentially implemented either as a stock feature or a combination of plugins users: block + HideBlockedMessages plugin channels: mute + "Hide Muted Channels" option servers: just leave

Lol, negative. People will notice if you block someone or leave the server. 😂

**Comment by rushiiMachine** [comment]
if you need to play physiological tricks I feel like there's something more important

**Comment by GabrielGreenWolf** [comment]
> if you need to play physiological tricks I feel like there's something more important

If someone has to use psychological tricks, there might be something more important going on.

As for your point, this suggestion is mainly meant for those who need to keep things hidden from others. It's helpful for various reasons. About your recent reply to the post, asking 'why' isn't really necessary

**Comment by NINJAA300** [comment]
.
