### ISSUE TITLE
Embed all images on Twitter gallery links

### ISSUE THREAD

**Issue by Delphox** [Aliucord/plugin-requests#117]
### Plugin Description

It's already done on [version 9.8.8 of Discord app](https://www.apkmirror.com/apk/discord-inc/discord-chat-for-gamers/discord-chat-for-gamers-9-8-8-hotfix-release/discord-chat-for-gamers-9-8-8-hotfix-android-apk-download/) (which is also the last version to still support android 4.4) and still works if you install it right now, but was subsequently removed in newer version and never brought back. Would be nice to be reimplemented as a plugin!

Here's an attached video of how it works on Discord app version 9.8.8
https://user-images.githubusercontent.com/5883538/127790020-868037fa-fd48-4581-83b5-493080ceded4.mp4

The tweet gallery example used in the video: https://twitter.com/chocomint_null/status/1343933066759135232

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
https://github.com/TaiAurori/mtega Seems a similar concept to this oowercord plugin

**Comment by Delphox** [comment]
This has been just made a reality by @RhythmLunatic [here](https://github.com/RhythmLunatic/aliucord-plugins)! Thanks a lot!!
