### ISSUE TITLE
Plugin that shows the "Moderator" and "Admin" Icons next to names in servers

### ISSUE THREAD

**Issue by Bikoil** [Aliucord/plugin-requests#1171]
### Discord Account

bikoil

### Plugin Description

![image-4](https://github.com/Aliucord/plugin-requests/assets/139659047/22553988-526a-4b62-a7d7-b85b7f5af681)
This is an example (yes kinda weird name) and basically it will show the icon next to the username "Admin" or "Owner" etc

### Go into more detail...

there isn't really anything other than that! it would be really cool!

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by void6670** [comment]
https://github.com/c10udburst-discord/aliucord-plugins/tree/master/MoreTags
