### ISSUE TITLE
Server Icon Downloader

### ISSUE THREAD

**Issue by TheNOGUy** [Aliucord/plugin-requests#1172]
### Discord Account

@land of scripts

### Plugin Description

It just download server icon

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by void6670** [comment]
https://github.com/Vendicated/AliucordPlugins/blob/builds/ViewProfileImages.zip
and check the plugins channel before asking plssss
