### ISSUE TITLE
NoFormatting

### ISSUE THREAD

**Issue by bunget** [Aliucord/plugin-requests#1173]
### Plugin Description

a plugin that shows messages without any formatting.

### Go into more detail...

example: if a message says "• word",with this plugin it should say "- word". same with all the other formatting (including **,***,~~,`,```,__ and any others)

and yes i know theres a plugin that lets you COPY messages in a formatting-less form,but this is different

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
use view raw.
