### ISSUE TITLE
Make text show at the bottom instead of the top when sharing media (gif, image, video, links)

### ISSUE THREAD

**Issue by No1syB0y** [Aliucord/plugin-requests#1175]
### Plugin Description

Whenever you share an image, video, etc., and include a message, that message will always appear at the top of the shared content. It would be nice to have the message appear at the bottom since text at the top can be easily missed due to how close it is to the sender's username or confused when sending links.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
no need for a plugin as any user can easily send a message after sending the attachment
