### ISSUE TITLE
Official Pronouns

### ISSUE THREAD

**Issue by viridianknight7** [Aliucord/plugin-requests#1178]
### Discord Account

viridianknight7

### Plugin Description

It may not be easy to make however the concept is simple

A plugin that renders your discord pronouns beneath your username (in the profile popout)

### Go into more detail...

I don't really know what else it would do, it's just a bit of text. (Also, I know this isn't original as at least 2? people have asked for this before, however their requests were ignored for different reasons)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Reinified** [comment]
most people use updated discord, so if you add your pronouns there than they can see it. Also, you can just put your pronouns in your 'About Me' section.

**Comment by ThatOneCalculator** [comment]
Possibly closed by https://github.com/Aliucord/Aliucord/commit/c221f4be19c3605703818c05338cfb101554dff0 ?
