### ISSUE TITLE
Message as webhook/bot

### ISSUE THREAD

**Issue by ghost** [Aliucord/plugin-requests#1179]
### Discord Account

invalid_247#0000

### Plugin Description

So when we use first message plugin it shows user's First msg but sends on chat with our account picture and name but with exception that it has webhook/bot tag

I want a plugin which can let me use a single command and msg as webhook/bot like that without having control over webhook/bot on that server

### Go into more detail...

It should have a simple command like /send
And must have the webhook/bot tag after name
It mustn't require webhook/bot management permission 

But if you can add option to customize profile pic and name of that webhook/bot it would be really cool

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
are you stupid
