### ISSUE TITLE
convert all twitter embeds to fxtwitter

### ISSUE THREAD

**Issue by hjroh0315** [Aliucord/plugin-requests#118]
### Discord Account

CrO4 2-#0010

### Plugin Description

change all twitter links' embeds (with a video preferrably) to their fxtwitter counterparts.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by bred-frontend** [comment]
For me, fxtwitter doesn't even actually embed in Discord either.

**Comment by Vendicated** [comment]
I'm not sure how useful this plugin would be because discord mobile actually can not play embedded videos, clicking play just opens it in browser which defeats the whole point of this plugin. 

So to make this useful you would also have to 'fix' video embeds

**Comment by abUwUser** [comment]
#127 

> I'm not sure how useful this plugin would be because discord mobile actually can not play embedded videos, clicking play just opens it in browser which defeats the whole point of this plugin.
> 
> So to make this useful you would also have to 'fix' video embeds

#127 if you wanna also fix video embeds

**Comment by C10udburst** [comment]
https://github.com/C10udburst/aliucord-plugins/raw/builds/LinkReplace.zip does more or less that
