### ISSUE TITLE
Fake Discord Rich

### ISSUE THREAD

**Issue by TayMcKenzieNZ** [Aliucord/plugin-requests#1182]
### Plugin Description

A plugin that emulates discord rich presence, but is completely fake. 

### Go into more detail...

This could be anything from faking that you are watching a live stream which leads to being Rick Rolled, to playing a game that doesn't exist, (GTA 6 beta build?) to anything in general.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by void6670** [comment]
use an external app for this, but it's probably against ToS depending on which app you'll use
