### ISSUE TITLE
last.fm rich presence

### ISSUE THREAD

**Issue by Urbexed** [Aliucord/plugin-requests#1183]
### Discord Account

urbexed

### Plugin Description

this would be a plugin that uses the official last.fm api to set the status of the music we're currently listening to if we've made sure that last.fm detects it.

I don't know if I explained myself well but a similar plugin exists on BetterDiscord, it's called "LastFMRichPresence" and was made by dimden#9999 and dzshn#1312

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
discord does not run in the background
