### ISSUE TITLE
Message and User Apps

### ISSUE THREAD

**Issue by NotBillybomb2** [Aliucord/plugin-requests#1186]
### Discord Account

notbillybomb2#0000

### Plugin Description

A plugin that will allow us to access the user and message apps that is on pc clients and the new version of discord on mobile.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
#1049 is the same request
