### ISSUE TITLE
Default emojis on discord

### ISSUE THREAD

**Issue by KRON4X** [Aliucord/plugin-requests#1187]
### Discord Account

KRON#4534

### Plugin Description

A plugin that replaces the discord emojis for the default emojis of the phone

### Go into more detail...

Instead of using the default emojis discord uses this plugin would replace the default emojis with the emojis of the phone being used kind of how it works on iphones, if the user is using a pixel phone then the discord emojis will be converted to google emojis etc.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
#22 exists
