### ISSUE TITLE
Quick delete button next to your messages

### ISSUE THREAD

**Issue by arushenst** [Aliucord/plugin-requests#1188]
### Discord Account

@reekychees

### Plugin Description

A red basket button appears next to the message, or something like that, when pressed, the message is immediately deleted without confirmation, it would be convenient if you need to quickly delete messages

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
#560 essentially the same
