### ISSUE TITLE
Plugin request searcher plugin

### ISSUE THREAD

**Issue by rickdtc** [Aliucord/plugin-requests#119]
### Discord Account

PUTDEMKNOCK#2006

### Plugin Description

A plugin that helps you search plugin requests and check if a plugin has been requested or not.
It would be handy for people like me who mess up in this situation. 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by NatSepruko** [comment]
GitHub has this really neat feature that allows you to search through issues, you should give it a try some time!

![image](https://user-images.githubusercontent.com/33651534/127993122-355de4e0-f648-416d-bc71-8ed81e606d72.png)
