### ISSUE TITLE
A plug in to make aliucord look very similar to discord

### ISSUE THREAD

**Issue by Desktopvibez** [Aliucord/plugin-requests#1190]
### Discord Account

nsxzzy

### Plugin Description

I think a plugin that makes aliucord look alot like discord would be really cool. 

### Go into more detail...

Making it look like discord would make it alot more user friendly since its going to be basically the same as regular discord

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
> aliucord look alot like discord 

it does, it's just the old version
rewriting the entire ui to fit modern discord is not possible

**Comment by BlueColdBoi** [comment]
I recommend you guys to add the animation plugin just add it even if you can't customize like myself , I just like the smooth animations . Regardings 
_BlueColdBoi
