### ISSUE TITLE
quick access to reply

### ISSUE THREAD

**Issue by MateElPepitoQuerido** [Aliucord/plugin-requests#1192]
### Discord Account

@mate.el.pepito.querido

### Plugin Description

that there is a quick access to reply to the message next to the user's name
![46 sin título_20230914193547](https://github.com/Aliucord/plugin-requests/assets/142197531/3d80e88d-9664-4550-8ca3-d452e413c9b9)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by TymanWasTaken** [comment]
Just use TapTap: https://github.com/Vendicated/AliucordPlugins/tree/main/TapTap

**Comment by MateElPepitoQuerido** [comment]
sorry
