### ISSUE TITLE
If It's Possible Making Animated Pfp

### ISSUE THREAD

**Issue by RandomUser69420F** [Aliucord/plugin-requests#1195]
### Discord Account

dai

### Plugin Description

If The Devs Could Somehow Make Animated Pfps and Banners Something Like Better Discord It Would Be Cool It May Very Well Not Be Possible So Yeah 

### Go into more detail...

I Know That It's Not Really Possible To Show People Who Don't Use Aliucord The Animated Pfps So Maybe Only We Can See The Animated Pfps And I Don't Expect Anything More

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
https://github.com/OmegaSunkey/awesomeplugins/raw/builds/UserPFP.zip yop its possible
