### ISSUE TITLE
Plugin downloader

### ISSUE THREAD

**Issue by abUwUser** [Aliucord/plugin-requests#12]
### Description
Sometimes users are too lazy to download the zip plugin file, open the file explorer, go to the downloads folder, copy or cut the zip, go to the aliucord folder, go to plugins, and paste it. So my soluiton is to make a plugin that automatically downloads aliucord plugins

### More info
It's simple: it'll have an item in the message context menu that when clicked it'll download the zip inside the plugins folder automatically. Note that this item will only show if you're on the #plugin-links-update due to #plugin-links not having a direct way to download the plugin specifically (unless you find a way to download it)

---

- [x] I checked if this plugin wasn't already requested.

**Comment by GangsterFox** [comment]
This is getting worked on in the installer. When it will finish no one knows

**Comment by abUwUser** [comment]
This will be something temporary. It'll be only used before the plugin store is relased

**Comment by vy-storm** [comment]
> This will be something temporary. It'll be only used before the plugin store is relased

Out of curiosity will any and all plugins be available on the store/downloader or will it have similar rules to the Discord server?  I'd get if it did and all, just curious.  Would be nice if risky ones could be uploaded and maybe just marked as such, but GitHub still exists if not.

**Comment by WinstonSepruko** [comment]
> > This will be something temporary. It'll be only used before the plugin store is relased
> 
> Out of curiosity will any and all plugins be available on the store/downloader or will it have similar rules to the Discord server?  I'd get if it did and all, just curious.  Would be nice if risky ones could be uploaded and maybe just marked as such, but GitHub still exists if not.

I know the userbase has hope for something like F-Droid, where you have a few included repos but can add custom ones at any time.

However, there is no ETA on its arrival nor any definite confirmation as to how it will operate. Perhaps @Juby210 can shed some light?

**Comment by Vendicated** [comment]
I'll make this plugin

**Comment by Juby210** [comment]
https://github.com/Vendicated/AliucordPlugins/raw/builds/PluginDownloader.zip
