### ISSUE TITLE
Aliucord port for WhoReacted from BetterDiscord

### ISSUE THREAD

**Issue by KaKi87** [Aliucord/plugin-requests#120]
### Discord Account

KaKi87#2368

### Plugin Description

This plugin shows the avatars of the users who reacted to a message.
![Preview](https://i.imgur.com/Gg56Z1v.png)
[Source](https://github.com/jaimeadf/BetterDiscordPlugins/tree/release/src/WhoReacted)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by js6pak** [comment]
https://github.com/js6pak/aliucord-plugins/blob/main/WhoReacted/README.md
