### ISSUE TITLE
Change Aliucord's icon

### ISSUE THREAD

**Issue by i8x3** [Aliucord/plugin-requests#1204]
### Discord Account

rsbh

### Plugin Description

As there is a new Discord feature where you can change Discord's icon on mobile, I believe that there should be a **built-in** way for Aliucord to do this with a plugin. You'd be able to upload an image (that fits certain requirements), and that would change the icon.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
https://github.com/Aliucord/AliucordManager/issues/42
