### ISSUE TITLE
Go in to every  channale regarding the rolls requrired

### ISSUE THREAD

**Issue by Hyperspace123ddd** [Aliucord/plugin-requests#1207]
### Plugin Description

Ecseese every channale

### Go into more detail...

Go into any channale in a server regarding the rolls

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
This doesnt abide by the rules.
