### ISSUE TITLE
a plugin to access an account only with the phone number

### ISSUE THREAD

**Issue by DeypelRebuild** [Aliucord/plugin-requests#1214]
### Discord Account

dsi.1#0000

### Plugin Description

 is to forget my Gmail and Password

### Go into more detail...

Please

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
not possible, contact discord support instead
