### ISSUE TITLE
Port new "sparkle" discord UI to aliucord 

### ISSUE THREAD

**Issue by tamsyn548** [Aliucord/plugin-requests#1215]
### Plugin Description

Port the sparkle new UI from the official client into aliucord 

### Go into more detail...

Ya know that thing in the official client and vendetta where if you hold on the sparkle, the UI becomes cursed? Yeah. I'm personally a huge fan. Let's move it to Aliucord too :33

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
tabs v2 is not coming to aliu
