### ISSUE TITLE
Plug-in to stop discord from compressing images

### ISSUE THREAD

**Issue by tamsyn548** [Aliucord/plugin-requests#1216]
### Plugin Description

A plug-in that will prevent Discord from compressing images, thus taking full advantage of nitro upload size

### Go into more detail...

Vendetta has a plug-in to stop discord from compressing images. I'd love it in aliucord too 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
You can just disable compression in `Text & Images` settings on the version aliucord uses.
