### ISSUE TITLE
View file: .txt, .json, .xml and more

### ISSUE THREAD

**Issue by ZeyFoxOFF** [Aliucord/plugin-requests#1220]
### Discord Account

zeyfoxoff and my id: 693135745925382166

### Plugin Description

Make it possible to previsualize files: txt json xml html css php ad more without downloading the file

### Go into more detail...

By clicking on a button to quote the file

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
TextFilePreview

**Comment by ZeyFoxOFF** [comment]
Yes I know it but it does nothing. Anyway for me ca preview nothing. Send me in dm what it should give with the plugin
