### ISSUE TITLE
fake nitro

### ISSUE THREAD

**Issue by mmw1984** [Aliucord/plugin-requests#1221]
### Discord Account

mmw1984

### Plugin Description

I want a plug-in called fake nitro that can use server emoji everywhere

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by void6670** [comment]
its already a thing it's called nitrospoof

**Comment by mmw1984** [comment]
sorry….
