### ISSUE TITLE
Masked Links support for Aliucord

### ISSUE THREAD

**Issue by TamimplayzDev** [Aliucord/plugin-requests#1222]
### Discord Account

ubnjnqmbza#0

### Plugin Description

Right now, the new Masked Links (`[Mask](Link)`) in regular messages are displayed very ugly in Aliucord. Some sort of support for these links would be amazing as we don't want to open up Vendetta (or regular Discord) just to view those links.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
use morehighlight
