### ISSUE TITLE
Edit hider

### ISSUE THREAD

**Issue by Alan879pro** [Aliucord/plugin-requests#1223]
### Discord Account

alan879.#7478

### Plugin Description

Hello can someone make a plugin where when i edit a message no one can see that it's edited like that would be really really cool 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
doesn't abide by the rules
