### ISSUE TITLE
Export / import config file

### ISSUE THREAD

**Issue by FrostyNick** [Aliucord/plugin-requests#1224]
### Discord Account

frostynick

### Plugin Description

Export and import a "dotfiles" or configuration file with themes and plugins, optionally excluding settings to prevent personal information being leaked. Your current plugins and themes could be easily be loaded to your next phone or shared anyone with Aliucord from an easy to read format.

### Go into more detail...

Don't wanna lose my 50ish plugins in the future, this would help me and others. Currently it wouldn't be recommended to just send the data files from Aliucord probably. It would be very useful and interesting to just have everything fetched and install from a single file. If it could be copy and pasted into a file that would be good for me, but for the average person it would probably make more sense to have an import / export button built-in to the UI somewhere; maybe in the settings?

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by wingio** [comment]
I think it'd be better to just zip the ~/Aliucord folder

**Comment by FrostyNick** [comment]
> I think it'd be better to just zip the ~/Aliucord folder

Yeah, I just checked the Aliucord files it's a lot organized than I thought. Probably not that important to add.
