### ISSUE TITLE
@silent backport

### ISSUE THREAD

**Issue by headassbtw** [Aliucord/plugin-requests#1226]
### Discord Account

headassbtw

### Plugin Description

discord rolled out a feature that disables audio/notifs for a ping or DM but still pings/DMs them if you preface the message with `@silent`

this would be nice to have, notably/exclusively the no push notifs part (maybe mark as silent in android? idk if that's possible) but idk how feasible that is (idk how android apps handle notifications)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
Duplicate of #1054.
