### ISSUE TITLE
Saucenao

### ISSUE THREAD

**Issue by Drhype2580** [Aliucord/plugin-requests#1228]
### Discord Account

drhype_

### Plugin Description

A option to search the img on saucenao, on the top right corner of a embedded img near the down and share icon

### Go into more detail...

It would be more cool if there's more features like Google image search and trace .moe 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
https://discord.com/channels/811255666990907402/845784407846813696/909622825239859242

**Comment by Drhype2580** [comment]
Sorry 😔 i only searched saucenao. When it didn't came up i made a request. I very sorry for my stupidity
