### ISSUE TITLE
Fix @invaliduser tag

### ISSUE THREAD

**Issue by MemLiveOn** [Aliucord/plugin-requests#123]
### Discord Account

Kat System 😸#0001

### Plugin Description

There is a plugin for Better Discord or Powercord that fixes pings or mentions of a user that left the server/group. On mobile, it's surprisingly common, even when the user is still in the guild because user IDs aren't cached the same way as desktop does.

### Go into more detail...

![Screenshot_2021-08-03_23-07-36](https://user-images.githubusercontent.com/68362669/128132177-9dcd4f21-2a39-4974-8681-601d1aafa837.png)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by js6pak** [comment]
second on the "annoys me perosnally" list - grab

**Comment by js6pak** [comment]
https://github.com/js6pak/aliucord-plugins/blob/main/ValidUser/README.md

**Comment by awes956** [comment]
> https://github.com/js6pak/aliucord-plugins/blob/main/ValidUser/README.md

404 not found

**Comment by js6pak** [comment]
@awes956
> > [js6pak/aliucord-plugins@`main`/ValidUser/README.md](https://github.com/js6pak/aliucord-plugins/blob/main/ValidUser/README.md?rgh-link-date=2025-06-14T10%3A09%3A15.000Z)
> 
> 404 not found

https://github.com/js6pak/ValidUser
