### ISSUE TITLE
Splitmessagesinfinite

### ISSUE THREAD

**Issue by TheBandit729** [Aliucord/plugin-requests#1231]
### Discord Account

the.bandit

### Plugin Description

I know that there already is a split messages plugin but can someone make one that is infinite or at least a very high number. I think it would also be necessary to have an emergency stop button just in case it gets out of hand.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
What kind of messages do you send that exceed 14 000 characters...?

@rushiiMachine I looked at the code of SplitMessages, and I see the limit of 7 messages is hardcoded. What is the reasoning behind it? I'd imagine you didn't just put it there for fun. Also, personal question, doesn't that plugin kinda count as selfbotting anyways...?

EDIT: Reposting related messages from Discord:

![obraz](https://github.com/Aliucord/plugin-requests/assets/33988779/6f32df88-9035-49a8-b51e-9fe8aedf20f8)
![obraz](https://github.com/Aliucord/plugin-requests/assets/33988779/1c49e852-b510-4941-82a7-b18412853d6a)

**Comment by rushiiMachine** [comment]
i put it there cause there's little delay between requests so it's unlikely you'd stop it in time
\+ people definitely use it for spam (ie. stacktraces in chat)
yes, it's kinda spambotty but it's limited and trigged by a physical user action so ig 🤷 


7*2000 = 14,000 chars
do you really need more than that?
