### ISSUE TITLE
Disable Discord's file compression

### ISSUE THREAD

**Issue by ghost** [Aliucord/plugin-requests#1237]
### Plugin Description

A plugin that disables Discord's shitty file compression so we can upload files faster, with higher quality and smaller size.
It is possible because other Discord clients gave that.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
this is already a stock option in settings
