### ISSUE TITLE
do not disturb

### ISSUE THREAD

**Issue by Saulildo** [Aliucord/plugin-requests#1239]
### Plugin Description

plugin that replaces your current message with unicodes and then you can bypass discord chat filter

### Go into more detail...

this is the best plugin suggestion out there and it is extremely easy to do. If the devs don't do this then this thing is definitely dead

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
i guess we are definitely dead
