### ISSUE TITLE
Party Mode plugin

### ISSUE THREAD

**Issue by Fr33styl31471** [Aliucord/plugin-requests#1246]
### Discord Account

.hurts2poo__

### Plugin Description

Discord Party Mode is an experimental feature that was introduced in 2022 for a limited time in celebration of Discord's birthday. It was a fun and interactive way to use the Discord client, adding a variety of visual effects and sounds to the typing experience.

### Go into more detail...

I really wanted to have the party mode in Aliucord because it was a fun plugin, seeing confetties whenever you chat, the chatbox shakes whenever you type very fast and very long, combos of each time you enter and whatnot. People yelling as background when you reach combo x7 and 20 achievements.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

edit: I forgot to put my discord user

**Comment by ThatOneCalculator** [comment]
Party mode was only ever in the react native version of Discord. Backporting those effects to Kotlin would be far more work than it's worth.

**Comment by zt64** [comment]
Adding particle effects like party mode would perhaps require the use of external libraries for the graphical effects 
It would be more effort than it's worth
