### ISSUE TITLE
req: NSFWLockBypass

### ISSUE THREAD

**Issue by Art3mLapa** [Aliucord/plugin-requests#1247]
### Discord Account

art3mkalapichka

### Plugin Description

a simple plugin to bypass restrictions in NSFW channels (if u silly and put age below 18)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
exists, nsfwgatebypass

**Comment by Art3mLapa** [comment]
my bad, i cant find this*
