### ISSUE TITLE
webhooks

### ISSUE THREAD

**Issue by FenixProGamer** [Aliucord/plugin-requests#125]
### Discord Account

Fatalityツ#4411

### Plugin Description

Now you have to go on browser to make webhooks it would be amazing if this is possible in app

### Go into more detail...

we can select channel we want webhook in and then button webhook where we can make webhooks for our server

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by C10udburst** [comment]
https://github.com/C10udburst/aliucord-plugins

**Comment by FenixProGamer** [comment]
thanks for amazing plugin
