### ISSUE TITLE
Plugin for discord message links

### ISSUE THREAD

**Issue by echerwrecker** [Aliucord/plugin-requests#1251]
### Discord Account

echerwreckerr

### Plugin Description

Plugin that makes discord message links NOT send you to chrome or whatever browser OR original discord app?

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
This is not an aliucord issue, change your default handler for discord.com urls in system settings
