### ISSUE TITLE
[Backport] Tap Message Links to go to the Original Message

### ISSUE THREAD

**Issue by AvianGeneticist** [Aliucord/plugin-requests#1255]
### Discord Account

Zoura3025

### Plugin Description

Modern discord has a feature where links to messages can be tapped on to immediately send you to the message; currently, tapping links tries to open the discord website rather than just using the app directly.

### Go into more detail...

While the primary functionality is the main concern of this request, a nice secondary feature would be being able to see what the linked message actually says without clicking on the link (perhaps as part of a togglable embed).

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
this is already a feature
change your default link handler for discord.com links in your system settings
