### ISSUE TITLE
Old mobile discord UI 

### ISSUE THREAD

**Issue by RonaldDoubts** [Aliucord/plugin-requests#1256]
### Discord Account

Deweysan

### Plugin Description

As much as I would like to believe with enough people complaining, they will revert the discord mobile UI but I doubt they will back down. I would like a plug-in that reverts the layout of the mobile app back to the way it was and prevent it from updating again into the new UI

### Go into more detail...

I think I pretty much explained everything the new UI sucks. The old one is better and it's not sluggish

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
you are on aliucord....
this version is so old its physically impossible to enable the new ui...
