### ISSUE TITLE
【PLUGIN REQUEST】 LoveFemboys 🌸

### ISSUE THREAD

**Issue by kissingboys** [Aliucord/plugin-requests#1257]
### Discord Account

https://vd-plugins.github.io/proxy/vendetta.sdh.gay/LoveFemboys/

### Plugin Description

# PLUGIN REQUEST
LoveFemboys (like Vendetta plugin (LoveFemboys Vendetta Plugin)[https://vd-plugins.github.io/proxy/vendetta.sdh.gay/LoveFemboys/]
This plugin send a femboy in chat with a command.

- [x] I have made sure my plugin is posible and abide by the rules
- [x] I did indeed check to make sure my plugin request is original

### Go into more detail...

# Into more detail:
This are the plugin setting:
- **NSFW Warning**: Warn when sending an NSFW image in a non NSFW channel.
- Best/New/Hot/Controversial (This is like Reddit)
# It adds the command:
- **/femboy**: Get an image of a femboy

# [⚠️](https://emojipedia.org/warning) IMPORTANT -- ADD NSFW OPTION

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by kissingboys** [comment]
Here is Vendetta plugin link btw https://vd-plugins.github.io/proxy/vendetta.sdh.gay/LoveFemboys/

**Comment by kissingboys** [comment]
i installed vendetta i install aliucord again when femboy plugin

**Comment by totaltommygun** [comment]
what the fart
