### ISSUE TITLE
invite unlimited members

### ISSUE THREAD

**Issue by DHOT112233** [Aliucord/plugin-requests#1262]
### Discord Account

Dhottdhott

### Plugin Description

Invite members without limits, to make it easier for us to invite friends to our discord server

### Go into more detail...

Invite members without limits, to make it easier for us to invite friends to our discord server

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
invite links with unlimited uses are already a thing
