### ISSUE TITLE
Super reactions?

### ISSUE THREAD

**Issue by echerwrecker** [Aliucord/plugin-requests#1264]
### Plugin Description

Super reactions could be cool

### Go into more detail...

I'm sure you guys can find a way to make this work, maybe even add the animations from base discord?

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by echerwrecker** [comment]
discord* autocorrect

**Comment by jedenastka** [comment]
Duplicate of #1219.
