### ISSUE TITLE
Copy role

### ISSUE THREAD

**Issue by DHOT112233** [Aliucord/plugin-requests#1267]
### Discord Account

Dhotdhot

### Plugin Description

Please, bro, add a copyrole plugin like the channel copy plugin so that it's easy if you want to create a lot of roles 

### Go into more detail...

Please, bro, add a copyrole plugin like the channel copy plugin so that it's easy if you want to create a lot of roles 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
Duplicate of #885.
