### ISSUE TITLE
Clear chat history with someone

### ISSUE THREAD

**Issue by Table-Hater** [Aliucord/plugin-requests#1269]
### Discord Account

blank_headed

### Plugin Description

I personally believe a plugin that deletes all chat history with someone in a single button is going to be usefull. All it has to do is delete the users messages. It doesn't need to (neither do I believe it can) delete the person who is not the user's texts. The main reason I want this plugin is to delete my chat history with someone I hate. I really believe this plugin can be usefull for people other than me too. 

### Go into more detail...

I think that the plugin should also allow you to leave some messages from a certain time period not deleted. Therefore it would be more usefull. Thank you. 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
abusing the API is not supported by aliucord
