### ISSUE TITLE
Visualize videos in embeds

### ISSUE THREAD

**Issue by abUwUser** [Aliucord/plugin-requests#127]
### Discord Account

A user#8169

### Plugin Description

Sometimes its annoying to open videos in embeds. Instead of playing inside discord, it opens the respective link.

This idea is simmilar to #104

### Go into more detail...

Well, since the player is in a separated view, i guess it'll be an easier task than what would be in desktop.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by resucutie** [comment]
Due to Aliucord being slowly replaced by other mods that support the RN version, I'll close this issue
