### ISSUE TITLE
Auto convert vm.tiktok links into vxtiktok links

### ISSUE THREAD

**Issue by Kezzers** [Aliucord/plugin-requests#1270]
### Discord Account

kezzers

### Plugin Description

People (sadly) seem to use TikTok a lot. I hate the app with a burning passion and always die of cringe whenever I click on a funny video a friend sent me and I get autoredirected to the appstore to download TikTok.

I'd love to see a plugin that auto converts links from the normal share that people use (example: https://www.tiktok.com/@officialswaggie/video/7310269666922990880 on Desktop or https://vm.tiktok.com/ZGeLuJ3wQ/ on mobile to the vxtiktok (embed video) version so I don't have to go open my Browser App and get spammed by TikTok to download their app every click, but instead get a convenient embed that's playable on Discord.

This shouldn't be against TOS, as the FixTwitterEmbeds Plugin basically does the same thing (I think, feel free to correct me if I'm wrong)

Thanks for reading, hope someone will do this! <3

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Use TextReplace plugin https://github.com/c10udburst-discord/aliucord-plugins
