### ISSUE TITLE
Spoiler images 

### ISSUE THREAD

**Issue by SkyeTheFoxyFox** [Aliucord/plugin-requests#1273]
### Discord Account

skyethefoxyfox 

### Plugin Description

Allows you to mark uploaded images with spoilers, just like modern discord 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItsFandi** [comment]
Read #common-issues in the Discord server, it's already supported
