### ISSUE TITLE
HideMessages

### ISSUE THREAD

**Issue by xNeoTron** [Aliucord/plugin-requests#1275]
### Discord Account

neo_tron

### Plugin Description

A plugin that lets you hide a certain message. The message would just disappear from your view. 

### Go into more detail...

The way it would work is, pretty much you go into the message, there would be an additional button that allows you to hide the single message you tapped on. This is to prevent the reciever from seeing a certain thing, whilst not blocking the person who sent said message. Any form of encrypting would work, as long as the message is not visible. 
This plugin would hide someone sending some certain things, whilst not blocking/muting them entirely.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by void6670** [comment]
already a plugin. it's called HideMessages, please check before submitting plugin req's
