### ISSUE TITLE
SOUNBOARD (Like voicemod!)

### ISSUE THREAD

**Issue by kanture** [Aliucord/plugin-requests#1278]
### Plugin Description

It would have a silly little toggle button at the top right of the vc screen or something. Or have a toggle for the soundboard incase you were recording a video and wanted to play a sound effect. 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
Duplicate of #1225.
