### ISSUE TITLE
Disable link warning popups

### ISSUE THREAD

**Issue by jjumbc** [Aliucord/plugin-requests#1283]
### Discord Account

wonderboy

### Plugin Description

I would like to be able to disable the popups that appear when clicking links in Aliucord. My web browser doesn't do this and I don't need Discord to do it either.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
Already part of [&Xinto's LayoutController plugin](https://github.com/X1nto/AliucordPlugins/tree/master/plugins/LayoutController) ([#plugins-list](https://discord.com/channels/811255666990907402/811275162715553823/845348833142505544)).
