### ISSUE TITLE
Monsoon speech copypasta

### ISSUE THREAD

**Issue by ChaosPhantom76** [Aliucord/plugin-requests#1284]
### Discord Account

MorayWinsAgain#1139

### Plugin Description

Since there's a plugin for Senator Armstrong's speech, I think it would be really cool to have Monsoon's philosophy speech as a copypasta plugin as well. Basically, you type "/denver" or something like that, and it pastes his speech.

### Go into more detail...

If possible, make it named "WELCOME TO DENVER!" Here's the speech you can use: Feasting on the insides of your enemies. How easily you ignore the loss of life when it suits your convenience. So tell me: who saves the weak from the man who saves the weak?

Kill or be killed, Jack. Phnom Penh taught me that.

Yes, you aren't the only one to grow up on the killing fields. War is a cruel parent, but an effective teacher. Its final lesson is carved deep in my psyche: that this world, and all of its people, are diseased.

Free will is a myth. Religion is a joke. We are all pawns, controlled by something greater: Memes, the DNA of the soul. They shape our will. They are the culture. They are everything we pass on.

Expose someone to anger long enough, they will learn to hate. They become a carrier. Envy, greed, despair: all memes, all passed on.

You can't fight nature, Jack. Wind blows, rain falls, and the strong prey upon the weak.

Sam tells me you see your weapon as a "tool": something that saves lives, a means of justice. Now, there's a pretty meme! Exquisite! It spared you the burden of all the lives you've taken, absolved you of guilt when you enjoyed it.

That is, until the illusion was broken. Don't be ashamed. It's only nature running its course. You have no choices to make. Nothing to answer for. You can die with a clear conscience.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
If you actually want to send this copypasta to people, [Juby210's Tags plugin](https://github.com/Juby210/Aliucord-plugins/tree/main/Tags) ([#plugins-list](https://discord.com/channels/811255666990907402/811275162715553823/835554229484519484)) could be of use. If it's supposed to just be a simple easteregg-esque thing then whatever.
