### ISSUE TITLE
Ping count fixer

### ISSUE THREAD

**Issue by MasterCraft6969** [Aliucord/plugin-requests#1286]
### Discord Account

mastercraft_48

### Plugin Description

There is a small problem with the ping counter at the top when it passes 1k pings. The numbers break the borders and are very small and barely readable. My idea is to make a toggle to show 1k+ if it passes 1k pings. 
![Screenshot_20240110_201442](https://github.com/Aliucord/plugin-requests/assets/127258883/e5107ecc-40e6-4ac0-bbd4-496cd66f093c)

### Go into more detail...

Maybe it could be a fix to the numbers itself so that they can fit within the intended space

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by MasterCraft6969** [comment]
I assume it'll get worse once the ping counter gets higher

**Comment by rushiiMachine** [comment]
NoPingWidthLimit

**Comment by MasterCraft6969** [comment]
> NoPingWidthLimit

My apologies. Thank you. Have a nice day
