### ISSUE TITLE
Pull Tab - Tabs V2 UI

### ISSUE THREAD

**Issue by KaiRoman** [Aliucord/plugin-requests#1288]
### Discord Account

MrXewrath

### Plugin Description

Tabs V2 Pull Tab, backport or something similar like that.

### Go into more detail...

I hate the new UIs performance, if it wasn't for the terrible lag I would use it, but alas it is laggy so I'm sticking with Aliucord and the old UI (thank you).

However one of the features I liked alot from the new update was the Pull Tab in the Advanced Section 
![Screenshot_20240112-163252](https://github.com/Aliucord/plugin-requests/assets/58362568/3d5c9d1b-5f2e-4e80-826a-46d7c0a288e4)
This feature is a little overlay tab on the right side of the app that pops out a quick access and search menu that I personally thing, power users or right handed people with big phones would or do greatly appreciate and like. 

This plugin request would be for someone to either make something like this or to backport the feature so that we can use it without having to torture ourselves with that shitty ass spaghetti coded update they call Discord now. 
![Screenshot_20240112-163114](https://github.com/Aliucord/plugin-requests/assets/58362568/f1fc075d-d65d-46ec-8bac-6fd36d2dd842)
![Screenshot_20240112-163110](https://github.com/Aliucord/plugin-requests/assets/58362568/e449be0b-e0cb-48e8-bb4f-9c556c92b1dc)
![Screenshot_20240112-163035](https://github.com/Aliucord/plugin-requests/assets/58362568/8fb8367b-df4a-4c83-8708-d2d6e137bf0a)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
Tabs V2 is not going to be ported to Aliucord

**Comment by KaiRoman** [comment]
Not Tabs V2 itself just launchpad (I only recently learned of its name) Pull tab
