### ISSUE TITLE
message length

### ISSUE THREAD

**Issue by carlacolon3** [Aliucord/plugin-requests#1289]
### Plugin Description

a plugin that just shows message length at all times

### Go into more detail...

could be very useful for people like me, who like to know their message length. copying a message to something else to check is a drag on mobile

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by the-unfunniest-lynx** [comment]
already exists

**Comment by carlacolon3** [comment]
> already exists

where?? i couldnt find it when i tried looking at all, i spent quite a while trying to find it

**Comment by rushiiMachine** [comment]
CharCounter
