### ISSUE TITLE
Desktop Settings

### ISSUE THREAD

**Issue by DarkmoonOnDiscord** [Aliucord/plugin-requests#1291]
### Discord Account

supraxp_

### Plugin Description

Make a plugin that would bring back all server modifications that are only available on pc back to mobile

### Request Agreement

- [x] I have made sure my plugin is possible and abides by the rules!

### ​

- [x] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
such as?

**Comment by DarkmoonOnDiscord** [comment]
wow i did not expect you to anwser, Look, i have no idea. sorry ☠️ i forgor
