### ISSUE TITLE
Revert Message Search to Before Mobile UI update

### ISSUE THREAD

**Issue by Klick-404** [Aliucord/plugin-requests#1295]
### Discord Account

Klick404

### Plugin Description

I'm sure this has been asked before, but I'd like a plugin for that reverts the search function back to before the UI update. The main thing would be searching across all channels, which was the biggest advantage of the search function

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
Aliucord does not support Tabs V2, the new ui doesn't exist
