### ISSUE TITLE
DisableCallIdle

### ISSUE THREAD

**Issue by outmaneuver** [Aliucord/plugin-requests#1298]
### Discord Account

was.

### Plugin Description

Disables automatically getting kicked from a DM voice call after 3 minutes and being moved to an AFK voice channel.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [x] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
This doesn't exist on Aliucord

**Comment by outmaneuver** [comment]
> This doesn't exist on Aliucord

what? isn't this supposed to be "requests" bruh? what's the point of this then?

**Comment by Juby210** [comment]
This kick doesn't exist at all on Aliucord so what plugin you want to be made

**Comment by rushiiMachine** [comment]
mfw i make an empty plugin that does nothing (your problem is already solved)
