### ISSUE TITLE
Hide Invite Members Button in Members Pane

### ISSUE THREAD

**Issue by TheOddGarlic** [Aliucord/plugin-requests#13]
### Description
A plugin that hides the invite members button in the members pane. 

### More info
Should **NOT** hide the button in group DMs as they don't have guild profile popouts.

The button: ![the button](https://cdn.discordapp.com/attachments/811275334342541353/845660294273433641/Screenshot_2021-05-22-16-52-00-72.jpg)

---

- [x] I checked if this plugin wasn't already requested.

**Comment by TheOddGarlic** [comment]
@X1nto maybe add this to #7?

**Comment by X1nto** [comment]
> @X1nto maybe add this to #7?

Sure

**Comment by X1nto** [comment]
Done, plugin was updated
