### ISSUE TITLE
Automatically patch media.discordapp.net urls

### ISSUE THREAD

**Issue by luphoria** [Aliucord/plugin-requests#130]
### Discord Account

luphoria#7398

### Plugin Description

This plugin would fix links to videos coming from media.discordapp.net so that they play in-app.

### Go into more detail...

When sending links of videos to other people via the mobile app, they will copy as a media.discordapp.net link, which does not play in app. They only play when the link is under cdn.discordapp.com. This theoretical plugin would simply load the video from cdn.discordapp.com (and also perhaps fix the link it provides when you try to share an existing video)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by terabyte25** [comment]
Partially fixed with https://github.com/terabyte25/plugins/blob/builds/VideoEmbedPatch.zip
