### ISSUE TITLE
Automatic theme backport

### ISSUE THREAD

**Issue by someone2026** [Aliucord/plugin-requests#1301]
### Plugin Description

Add support for Discord's automatic light/dark mode to match with system theme

### Go into more detail...

Would make it easy to sync the current state of light/dark mode with phone theme so I don't get flashbanged by light mode at 3am

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Done, you can download here: https://github.com/zt64/aliucord-plugins/raw/builds/SystemTheme.zip
It is incompatible with the Themer plugin for the time being

**Comment by sudoshindo** [comment]
> Done, you can download here: https://github.com/zt64/aliucord-plugins/raw/builds/SystemTheme.zip It is incompatible with the Themer plugin for the time being

Install steps?
