### ISSUE TITLE
Forum Fixer

### ISSUE THREAD

**Issue by ghost** [Aliucord/plugin-requests#1305]
### Plugin Description

I'd really appreciate a plugin that backports the forum features from later versions of Discord!

### Go into more detail...

While the version of Discord that Aliucord runs on supports Forums, it _doesn't_ have support for creating or modifying tags. I'd like a plugin that restores the functionality for this feature.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
Duplicate of #1081.
