### ISSUE TITLE
No Maximum for video

### ISSUE THREAD

**Issue by ClydeisCool** [Aliucord/plugin-requests#1308]
### Discord Account

bestofyou_

### Plugin Description

The plugin would make any video file size be sended and have no maximum

### Go into more detail...

Make 25 mb not only supported for video file size but also above 25 mb

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
Not possible.
