### ISSUE TITLE
Ai For Discord

### ISSUE THREAD

**Issue by ClydeisCool** [Aliucord/plugin-requests#1310]
### Discord Account

bestofyou_

### Plugin Description

I think that this plugin would do something like adding an ai for discord! To open the ai its next to the image send logo +. This ai would be helpful if your in a situation

### Go into more detail...

I think it should also do useful responses what to reply to the person, if your in a fight and you dont wanna fight ask the ai what to say to the person

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ragxxv** [comment]
Safe to say this plugin would be very laborious and is quite superficial at this point to begin with, just get some keyboard with AI to uh, fight with others..?

**Comment by ClydeisCool** [comment]
No tell the ai what to do and it must not fight
