### ISSUE TITLE
Emoji's to images

### ISSUE THREAD

**Issue by ghost** [Aliucord/plugin-requests#1312]
### Discord Account

Funfettyyt

### Plugin Description

Just converts an emoji you send and it turns into a image

### Go into more detail...

Sends the emoji as an image or gif

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
[NitroSpoof](https://discord.com/channels/811255666990907402/845784407846813696/927607021023404044) exists.
