### ISSUE TITLE
Embedded Messaging Link for React Backport

### ISSUE THREAD

**Issue by NernKat** [Aliucord/plugin-requests#1314]
### Discord Account

NernKat 

### Plugin Description

Coming from Vendetta which has some of the more recent updates for Discord(being on React), Discord has this really nice function where you can copy the link to a message and paste it in another discord. 
![Screenshot_20240228_095007](https://github.com/Aliucord/plugin-requests/assets/30741943/c1f31c28-3544-4250-b1b1-b232c583853b)

As you can see in the screenshot, it has information like the server it was in. Very useful and looks cleaner than what Aliucord currently shows (a wall of text link).

I'm not sure if this type of Backport is possible? If it's not please feel to take this down :)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
EmbedMessageLinks kind of does that. The channel and server is shown in the embed but the url is not transformed into that.
