### ISSUE TITLE
See deleted messages

### ISSUE THREAD

**Issue by Agenttt1028** [Aliucord/plugin-requests#1316]
### Discord Account

agent0402

### Plugin Description

I would love to have a plugin that lets you see deleted messages like in betterdiscord

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
Already exists.

**Comment by RTND7** [comment]
> ### Discord Account
> agent0402
> 
> ### Plugin Description
> I would love to have a plugin that lets you see deleted messages like in betterdiscord
> 
> ### Go into more detail...
> _No response_
> 
> ### Request Agreement
> * [x]  I have made sure my plugin is possible and abides by the rules!
> 
> ### ​
> * [x]  I did indeed check to make sure my plugin request is original!
