### ISSUE TITLE
Access account only with name and password

### ISSUE THREAD

**Issue by DeypelRebuild** [Aliucord/plugin-requests#1317]
### Discord Account

deypelrebuild_

### Plugin Description

Be able to access an account with only the account name and password, I lost the email of some of my accounts and I need to recover it 

### Go into more detail...

There are enough details

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
Not possible.
