### ISSUE TITLE
Ignore airplane mode

### ISSUE THREAD

**Issue by seacat17** [Aliucord/plugin-requests#1318]
### Discord Account

seacat17

### Plugin Description

The idea is simple. Right now if I'll enable airplane mode and try to open Aliucord it will refuse to work no matter what. I wish there was a way to make it ignore the airplane mode presence and rely on the internet connection possibility instead.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
Airplane mode is literally supposed to be a way to cut out *all* radio connectivity, and it delivers on that. This is not possible, and I have no idea why would you want that. Just... don't use airplane mode.
