### ISSUE TITLE
Embed sender (like rauf)

### ISSUE THREAD

**Issue by 777Vincent** [Aliucord/plugin-requests#1319]
### Discord Account

zanderthelegend#0000

### Plugin Description

A plugin that sends a custom embed without requiring you to use a bot, look at rauf's embed sender, it's perfect but extremely outdated and no longer in service, but I would love to use it!!

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Sending embeds as a user is self botting and against ToS

**Comment by rushiiMachine** [comment]
This used to be possible but isn't even possible anymore
