### ISSUE TITLE
:3nizer 

### ISSUE THREAD

**Issue by Kipe69420** [Aliucord/plugin-requests#1320]
### Discord Account

__username.txt

### Plugin Description

It adds ":3" at the end of every message you send... and... that's it :3

### Go into more detail...

and it always adds a space too so it won't end up like "Hello World:3", it should look like "Hellow World :3"

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OasisVee** [comment]
![Screenshot_20240308-213417](https://github.com/Aliucord/plugin-requests/assets/131408227/0e2949c8-b687-422c-8f56-9d1b50361a5a)
textreplace plugin can do this, already talked about it in plugin-support just putting this here
