### ISSUE TITLE
Old new UI

### ISSUE THREAD

**Issue by claymorwan** [Aliucord/plugin-requests#1322]
### Plugin Description

Basically a Plugin that adds the old new UI

### Go into more detail...

![Screenshot_2024-03-15-11-58-34-72_99c04817c0de5652397fc8b56c3b3817](https://github.com/Aliucord/plugin-requests/assets/86072589/2e78e3d4-d388-4f22-a842-d447295ddba9) This one if you're wondering (yoinked that screenshot from a video on yt). 
Idk if it's actually possible, I checked the impossible request and it doesn't seems to be there so mayhaps, that would be cool 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
> Idk if it's actually possible, I checked the impossible request and it doesn't seems to be there so mayhaps, that would be cool

Possible, sure, but very hard. The new layout doesn't really have any advantages over the old one either.

**Comment by claymorwan** [comment]
> > Idk if it's actually possible, I checked the impossible request and it doesn't seems to be there so mayhaps, that would be cool
> 
> Possible, sure, but very hard. The new layout doesn't really have any advantages over the old one either.

I mostly like it cuz it gives more mobile vibes, I liked it when it was available. But yeah I understand it's probably hard, so imma just let the idea there in case someone's crazy enough to do it

**Comment by void6670** [comment]
even if someone was willing to do it, this wouldn't be a great thing to add unless it had a switch where you could choose to have it enabled or not since most people using Aliucord hate the new ui i would assume

**Comment by claymorwan** [comment]
> even if someone was willing to do it, this wouldn't be a great thing to add unless it had a switch where you could choose to have it enabled or not since most people using Aliucord hate the new ui i would assume 

Ye ofc with a switch, it would be weird if it doesn't have one

**Comment by tiagomps** [comment]
any updates?

**Comment by rushiiMachine** [comment]
new ui isn't coming to aliu
