### ISSUE TITLE
Cannot see blocked messages

### ISSUE THREAD

**Issue by ClydeisCool** [Aliucord/plugin-requests#1325]
### Discord Account

Bestofyou

### Plugin Description

If u are curious ehat u blocked just say in the server well dont worry this plugin would help you! U can not see the blocked messages if u use tjis plugin

### Go into more detail...

I tjink it should also do its own settings that if u wanna see blocked messages or not

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
I assume you just want a plugin to hide blocked messages. That already exists as [HideBlockedMessages](https://github.com/lexisother/AliucordPlugins/tree/master/HideBlockedMessages) ([#plugins-list](https://discord.com/channels/811255666990907402/811275162715553823/852275710256611328)).
