### ISSUE TITLE
MessagesCount

### ISSUE THREAD

**Issue by ClydeisCool** [Aliucord/plugin-requests#1326]
### Discord Account

Bestofyou

### Plugin Description

After many failed request I have hope for this thing.
A plugin tht let's you see how many messages I typed or how many messages others typed. 

### Go into more detail...

I think it should be activated by this command
/count messages and it should say user and type what user and now we can see how many

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
the search functionality is built into discord
