### ISSUE TITLE
Add polls to Aliucord

### ISSUE THREAD

**Issue by rednixch** [Aliucord/plugin-requests#1327]
### Discord Account

rednix.ch

### Plugin Description

I think of a plugin that would allow us to see [polls](https://support.discord.com/hc/en-us/articles/22163184112407-Polls-FAQ) and interact with them (and create them? lol)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
Already tracked at https://github.com/Aliucord/Aliucord/issues/442.
