### ISSUE TITLE
Make a show Hidden channels plugin!

### ISSUE THREAD

**Issue by Scorpion7162** [Aliucord/plugin-requests#1329]
### Discord Account

scorpionong

### Plugin Description

A plugin that can show you hidden / locked out channels would be great! Include the roles that would be able to access it and if it is a call see who's in it!

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
Already exists as [ShowHiddenChannels](https://github.com/X1nto/AliucordPlugins/tree/master/plugins/ShowHiddenChannels) ([#plugins-list](https://discord.com/channels/811255666990907402/811275162715553823/845348833142505544)).
