### ISSUE TITLE
StickerUtility

### ISSUE THREAD

**Issue by MatadorProBr** [Aliucord/plugin-requests#133]
### Discord Account

```Matador#0069```

### Plugin Description

Literally a [EmojiUtility](https://github.com/Vendicated/AliucordPlugins/tree/main/EmojiUtility) but for Stickers, like a StickersUtility

### Go into more detail...

It would be more cool if the EmojiUtility plugin came with stickers support too instead of making another plugin for it and if that happens I think will need also have to change the plugin name, like EmojiStickerUtility?

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
https://github.com/Vendicated/AliucordPlugins/issues Make a github issue here for a feature request for emojiutil
