### ISSUE TITLE
Delete messages in DM

### ISSUE THREAD

**Issue by MAKGAMEROFFICIAL** [Aliucord/plugin-requests#1330]
.

**Comment by jedenastka** [comment]
> I have made sure my plugin is possible and abides by the rules!

> Examples of disallowed plugins
> - Selfbot behavior: Sending embeds, **delete all my messages**, AFK messages / auto reply, animated (auto changing) custom status

**Comment by MAKGAMEROFFICIAL** [comment]
You can set limits per delete and cool down
As This plugin is very helpful and discord is also working on apps in DM

**Comment by jedenastka** [comment]
> You can set limits per delete and cool down

So what?

>  As This plugin is very helpful and discord is also working on apps in DM

So what? User bots are not able to delete messages if that's what you mean.
