### ISSUE TITLE
status online 24/7

### ISSUE THREAD

**Issue by Deustru** [Aliucord/plugin-requests#1336]
### Discord Account

luberube

### Plugin Description

makes your status appear online 24/7

### Go into more detail...

I like having a status so I can type a funny joke there but I'm always invisible because I prefer when people dont know when Im online. sometimes i take time to reply and i feel rude when someone knows im probably online and not answering them right away. so a plugin that makes you appear online at all times would hit 2 stones with one rock! 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
not possible without constant connection to gateway which would drain battery a lot and would require the app to run in background
