### ISSUE TITLE
AnonymiseFileNames

### ISSUE THREAD

**Issue by Crisp-Casper** [Aliucord/plugin-requests#1337]
### Plugin Description

When you upload a file randomize the name before uploading has been done already for vencord

### Go into more detail...

Vencord version https://vencord.dev/plugins/AnonymiseFileNames

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Crisp-Casper** [comment]
There is code at this link idk if the import would be easy https://github.com/Vendicated/Vencord/blob/main/src/plugins/anonymiseFileNames/index.tsx

**Comment by jedenastka** [comment]
Duplicate of #1127.
