### ISSUE TITLE
Default reply ping to off

### ISSUE THREAD

**Issue by DaveyL2013** [Aliucord/plugin-requests#1339]
### Discord Account

@DaveyL2013

### Plugin Description

I'd like a plugin that sets the reply ping to off by default instead of on by default, similar to the one on Vencord

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
already exists
![image](https://github.com/Aliucord/plugin-requests/assets/31005896/072c6aab-751c-4510-a797-e8531c5970e8)

**Comment by DaveyL2013** [comment]
Oh I'm dumb I couldn't find it lol
