### ISSUE TITLE
Plugin to edit picture  

### ISSUE THREAD

**Issue by Lastlyfera** [Aliucord/plugin-requests#1345]
### Plugin Description

I think the plugin that does (Crop, draw on it, put sticker, emote, filter ECT) on a pic before sending it. Looks really cool if you have that

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
use your system markup tool or an external one

**Comment by Lastlyfera** [comment]
Damn instant rejection and also low quality/dumb?

How? When latest discord has those feature? Once again guess my superior brain is blockaded by the inferior thoughts 😩
