### ISSUE TITLE
LeftRightMessages

### ISSUE THREAD

**Issue by oSumAtrIX** [Aliucord/plugin-requests#135]
### Discord Account

[oSumAtrIX#7606](https://osumatrix.me/#discord)
### Plugin Description

Messaging services like Telegram, Messenger or WhatsApp follow a design style which involves messages being aligned to the left or right based on who the sender is. Your messages are aligned on the right, others messages are on the left. On a big screen this would make it difficult to read messages, since aligning them to the left and right would increase the distance between them a lot. On a mobile screen, perfectly suitable for Aliucord, this would work just fine and be useful to those who prefer the „left right“ messages design.

### Go into more detail...

Customization should be the focus here. Let the user choose, if he wants his or others messages to be aligned to the left or right, paddings and groupings should also be considered. 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hjroh0315** [comment]
funny solution: add rtl override to select messages

**Comment by C10udburst** [comment]
https://github.com/C10udburst/aliucord-plugins

<a href="https://github.com/C10udburst/aliucord-plugins"><img src="https://user-images.githubusercontent.com/18114966/136654276-635fd3a5-714b-4e12-b8d8-5752487d42e8.png" width="40%"></a>

It does look a bit weird in some circumstances (eg. replies)
