### ISSUE TITLE
i just want a plugin like /nanomachines, but it does the message from the beginning of p3

### ISSUE THREAD

**Issue by DavetrapCourier6** [Aliucord/plugin-requests#1350]
### Discord Account

DavetrapCourier6

### Plugin Description

I want it to work like /nanomachines, but instead of it sending senator armstrongs speech, it sends this:
Time never waits.
	It delivers all equally to the same end.

You, who wish to safeguard the future,
	however limited it may be...

You will be given one year;

go forth without falter,
	with your heart as your guide...

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
If you actually want to send this copypasta to people, [Juby210's Tags plugin](https://github.com/Juby210/Aliucord-plugins/tree/main/Tags) ([#plugins-list](https://discord.com/channels/811255666990907402/811275162715553823/835554229484519484)) could be of use. If it's supposed to just be a simple easteregg-esque thing then whatever.
