### ISSUE TITLE
One Ping Per DM/Channel

### ISSUE THREAD

**Issue by marcmy** [Aliucord/plugin-requests#1351]
### Discord Account

marcus1259

### Plugin Description

I would love to have a plugin that disables additional notification pings for DMs and channels. i.e. if I get a DM or a message in a channel that I get notifications in, it won't ping/notify me of additional DMs from that user or channel's messages until I've caught up. I have a similar plugin on my desktop client (though I think it only does DMs). Let me know if there's any extra info that I can assist with. (I would try and code this myself but I haven't quite gotten that far yet in my coding skills)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
Not entirely possible - we can't control notifications outside of Discord with plugins (it's technically possible to do but would require pretty major changes to Aliucord itself). We can control notifications *inside* Discord, but that's pretty limited compared to the functionality you want.

**Comment by marcmy** [comment]
Ah, I see. Thank you.
