### ISSUE TITLE
BetterMentions /BetterSearch

### ISSUE THREAD

**Issue by SomeStupidPerson** [Aliucord/plugin-requests#1354]
### Plugin Description

A plugin that makes the mentions feature in search in Discord better.Instead of having to accurately remember what someone said 3 months ago. 

### Go into more detail...

For example, someone said "Hey I do not condone this or allow this", and I searched "mentions: I don't condone this nor do I allow it" Normally, nothing would come up as I didn't accurately remember what Anon said, this plugin would get the sentence closest to what I just said. It would view every word I searched and try to find a sentence that contains most of the words that i searched, sorting them from having the most words to containing the least words from the search I did

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
Not possible. Discord search is server-side, we can't alter what results it returns.

**Comment by SomeStupidPerson** [comment]
Ah alr, gotcha thxs for your time
