### ISSUE TITLE
Custom Ringtone Changer

### ISSUE THREAD

**Issue by ChaosToon** [Aliucord/plugin-requests#1359]
### Discord Account

chaos_jr.#0000

### Plugin Description

I would like to change the discord call sound. 

### Go into more detail...

If you could make it so that it can also create a pop-up no matter if you're in an app or not to join or decline when playing the sound I choose.

Please consider this, and if so, if this is possible, can you dm me the plugin?

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
Themer can do this
