### ISSUE TITLE
Text React

### ISSUE THREAD

**Issue by DevOldboy** [Aliucord/plugin-requests#136]
### Discord Account

Oldboy#2021

### Plugin Description

I think a plugin that automatically adds reactions on a message you choose would be great. Also if you could select the emotes you want on the message i.e the letter emojis spelling out something of your choice.

### Go into more detail...

Using the reply feature with a / command would be a nice way to use this. 

### Request Agreement

- [x] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
So a port of powercords https://github.com/Juby210/text-react

**Comment by DevOldboy** [comment]
> So a port of powercords https://github.com/Juby210/text-react

Ooh yeah it seems like that's what I'm looking for. How do I add it to my plugins? I don't see the build branch to download the file. Sorry for bothering.

**Comment by NatSepruko** [comment]
> > So a port of powercords https://github.com/Juby210/text-react
> 
> Ooh yeah it seems like that's what I'm looking for. How do I add it to my plugins? I don't see the build branch to download the file. Sorry for bothering.

It is a Powercord plugin, it won't work on Aliucord.

**Comment by ArjixWasTaken** [comment]
> Using the reply feature with a / command would be a nice way to use this.

Or even better having the option in the menu that opens when you long tap on a message.

**Comment by ArjixWasTaken** [comment]
I finally did it!
https://github.com/ArjixWasTaken/aliucord-plugins

It's pretty barebones tho.
