### ISSUE TITLE
Nintendo Switch Connect

### ISSUE THREAD

**Issue by ChaosToon** [Aliucord/plugin-requests#1360]
### Discord Account

chaos_jr.#0000

### Plugin Description

Make it so I can use the nintendo ip to stream the game I'm playing. Can it also work so people on Vanilla Discord can watch it?

### Go into more detail...

Also, could you make it show what game I'm playing?

Please consider this, and if so, if this is possible, can you dm me the plugin?

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
altering screensharing sources is not possible
