### ISSUE TITLE
Markdown for #, ##, and ###

### ISSUE THREAD

**Issue by Thick9035** [Aliucord/plugin-requests#1362]
### Discord Account

deathbaby_.31

### Plugin Description

A plugin that allows you to see the text sizes of #, ##, and ###

### Go into more detail...

Aliucord doesn't allow the usage of #, ##, and ###, so this would be a cool feature to see in a plugin.

### Request Agreement

- [x] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by PiRhoRAMPAGE** [comment]
Also for -#

**Comment by jedenastka** [comment]
Duplicate of #1071.
