### ISSUE TITLE
SMS & MMS

### ISSUE THREAD

**Issue by Radiin91** [Aliucord/plugin-requests#1367]
### Plugin Description

now idk if this is actually possible or not to do this but I would adore a plugin letting me MMS and SMS IN discord. like I could imagine me messaging my cousin through SMS and MMS in discord (quick note I say MMS everytime I say SMS because I think some people are dumb enough to just make SMS and forget MMS)

### Go into more detail...

it should be on the down of the screen (where settings, friends, servers and etc are) and function like the normal discord chat. now here's where it gets a little tricky for devs (I think so) show a burple (discords original color) circle at the top of the chat (near the name) if both of the people messaging are messaging in discord (using the same plugin). benefits are custom (and non custom) emojis, sticker and etc. but if people are messaging outside of Discord to this plugin, then a color the dev likes (any color of the devs choice) or just no circles. I wouldn't be surprised if this plugin cannot be made.

>

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
why

**Comment by Radiin91** [comment]
> why

I find it cool to have a all in one messaging app. I also find it annoying switching between apps and would love custom emojis in SMS and MMS so... yeah. also anyone wanting to make this probably agrees with the idea (that's why they make it hopefully)

**Comment by jedenastka** [comment]
> and would love custom emojis in SMS and MMS

You know this is not possible right.

I still fail to see why not simply use a dedicated text program for texts, but I guess you are the kind of person who uses Discord as a backup service, password manager, notes program etc. (essentially an OS on top of your existing OS).

**Comment by TymanWasTaken** [comment]
> > why
> 
> I find it cool to have a all in one messaging app. I also find it annoying switching between apps and would love custom emojis in SMS and MMS so... yeah. also anyone wanting to make this probably agrees with the idea (that's why they make it hopefully)

That's called [beeper](https://beeper.com). Discord mods are not the way to make a universal messaging app, and universal messaging apps aren't that great of an idea anyways, as different apps often serve different purposes (see: signal removing sms support)

**Comment by Radiin91** [comment]
oh. I see. ok. thanks for telling me yall.
