### ISSUE TITLE
LocalPins

### ISSUE THREAD

**Issue by Ketsuyumi** [Aliucord/plugin-requests#1373]
### Plugin Description

Plugin to locally pin messages.

### Go into more detail...

As you would pin a message, merging the local pins with the server pins, putting them above, ordered by date.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
favorite messages can achieve the same goal

**Comment by OmegaSunkey** [comment]
except for merging with server pins obviously
