### ISSUE TITLE
Less Image Compression

### ISSUE THREAD

**Issue by sryanttza** [Aliucord/plugin-requests#1378]
### Discord Account

bucketslayer

### Plugin Description

A plugin that could disable or reduce the image compression when uploading an image

### Go into more detail...

If possible, a plugin that could disable or reduce image compression would be nice. I think they added that as a nitro feature a while ago, but then disabled it. Either just reducing/disabling the compression all together could work, or maybe upscaling the image as you send it so when it compresses it compresses closer to the original image. This would help to make most photos uploaded look better and less pixelated.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
this is a stock option
