### ISSUE TITLE
Metadata Stripper

### ISSUE THREAD

**Issue by Chuleta63** [Aliucord/plugin-requests#1384]
### Discord Account

mentalmentesano666

### Plugin Description

A plugin that gets rid of all metadata in send files / photos instead of having it to delete it manually.

### Go into more detail...

You send the photo like normal and it strips all metadata in the photo and then sends the stripped file instead of having it carry all the info. Could be a tick in the spoiler section to have the option of sending or not to trusted users. 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
Metadata is stripped by default.
![Screenshot_20240523-114846_MiXplorer](https://github.com/Aliucord/plugin-requests/assets/94485936/039c07e4-3b53-4ea8-b09c-c0504a9afdbb)
![Screenshot_20240523-114904_MiXplorer](https://github.com/Aliucord/plugin-requests/assets/94485936/75c1d897-6943-46d3-b932-d00fa75af6fc)

First is metadata made up in a photo editor.
Second is picture downloaded from discord.
