### ISSUE TITLE
Favorite channel button

### ISSUE THREAD

**Issue by AdazPadaz** [Aliucord/plugin-requests#1387]
### Discord Account

SinNombre4301

### Plugin Description

A plugin that let's you favourite channels, already a feature in discord and other clients like vendetta. 

### Go into more detail...

Pretty self explanatory, appears at the top of the server so if you only use/need a couple channels then it's way easier to use them. 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by AdazPadaz** [comment]
Any update for this? Would like this to be a plugin or the experiments plugin fixed as I know it had an experiment that partially implemented favourite channel button but most default experiments got wiped.

**Comment by PeterKW** [comment]
Does anyone else know of any way of doing this? It would be extremely useful.

**Comment by zt64** [comment]
Done. Download here: https://github.com/zt64/aliucord-plugins/raw/builds/FavoriteChannels.zip
