### ISSUE TITLE
Gif with text

### ISSUE THREAD

**Issue by SomeStupidPerson** [Aliucord/plugin-requests#1388]
### Plugin Description

A plugin that enables you to add texts with gifs

### Go into more detail...

A pretty simple yet needed, to choose a gif then instead of discord sending it, it'll have it selected. Then you can just add your text then send the text with the gif altogether 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
AppendGifAsUrl exists already.
