### ISSUE TITLE
enable staging

### ISSUE THREAD

**Issue by z2w7** [Aliucord/plugin-requests#1389]
### Plugin Description

i think a u plugin that enable staging like the one on enmity would be pretty useful

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
staging does not exist on discordkt

**Comment by z2w7** [comment]
why could i do it on enmity then?

**Comment by rushiiMachine** [comment]
enmity is not based on discordkt, its the new rna app

**Comment by z2w7** [comment]
ohh sorry mb im new in this
