### ISSUE TITLE
Collapse Sidebar

### ISSUE THREAD

**Issue by Niru2169** [Aliucord/plugin-requests#1393]
### Discord Account

tokiyasu_tatsumi

### Plugin Description

Allow user to collapse/hide the sidebar (channel list & friends list) either on demand or automatically.

https://github.com/Aliucord/plugin-requests/assets/66010447/0ef9d1c0-cf1a-4ada-b683-d51b01ab594c

### Go into more detail...

(There are two firefox plugins, one chrome plugin that can do this and betterdiscord has one as well iirc. I'm not sure if I'm allowed to post those links here; )

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
you realize this is a mobile client right
