### ISSUE TITLE
Actual discord notification sound

### ISSUE THREAD

**Issue by reviandtobi** [Aliucord/plugin-requests#1398]
### Discord Account

.revintobi

### Plugin Description

I would like a plugin that changes the notification sound to the actual discord notification sound, because discord haven't done it yet :]

### Go into more detail...

All it does is change the push notification sound to the discord web app notification sound. I'm not sure if this is possible, but it would be cool :] ((yes I did check the possible/impossible but I didn't find anything like this--

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
In-app notification sounds: NoticeSound
Android notification sounds: Change it within settings app
