### ISSUE TITLE
No Scrollbar

### ISSUE THREAD

**Issue by Alastor-Kaneki** [Aliucord/plugin-requests#1399]
### Discord Account

k4n3k1.5287

### Plugin Description

The plugin would remove the unfunctional scroll bar from the screen, since the bar is useless and don't work at all. 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [x] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
functionality provided by WiderScrollbar

**Comment by ghost** [comment]
Hi

**Comment by ghost** [comment]
.canery.#0 can you pls unban me 😭

**Comment by ghost** [comment]
> Come on. I just wanna use a discord client because I got banned from all modded clients server :(

**Comment by ghost** [comment]
Servers*

**Comment by ghost** [comment]
Ok Grammarly broke,

@grammarAI pls help Grammarly servers are down
