### ISSUE TITLE
Quick Star in Message Context Menu

### ISSUE THREAD

**Issue by TheOddGarlic** [Aliucord/plugin-requests#14]
### Description
A plugin that adds a button that adds a star reaction to the message context menu.

### More info
Should NOT add the button if the user doesn't have the permission to react.

---

- [x] I checked if this plugin wasn't already requested.

**Comment by Litleck** [comment]
Working on it

**Comment by Litleck** [comment]
Done, you can download it from https://github.com/litleck/aliucord-plugins/raw/builds/QuickStar.zip
