### ISSUE TITLE
Server Clone 

### ISSUE THREAD

**Issue by TheError-RUS** [Aliucord/plugin-requests#1403]
### Discord Account

.glicht

### Plugin Description

That there be the possibility that someone with administrator permissions on a Discord server can clone both Text Channels, Voice, Forums and Etc. so much so that the roles can also be cloned. And permissions for each role and channel

### Go into more detail...

That when you want to make a backup server with this plugin you can do it quickly without delay

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ragxxv** [comment]
Create a server template and use it.

**Comment by jedenastka** [comment]
> **Examples of disallowed plugins:**
> [...]
> - Copying or Transferring servers
