### ISSUE TITLE
Message Content Replacer

### ISSUE THREAD

**Issue by seerified** [Aliucord/plugin-requests#1404]
### Plugin Description

Basically a plugin that allows you to blacklist certain words you do not wanna see sent by other users, i.e slurs, deadnames, etc.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OasisVee** [comment]
you can use the plugin textreplace to make a rule to censor it

something like this works fine but you would need to create separate rules for every single word you want to not see
![Screenshot_20240612-114047](https://github.com/Aliucord/plugin-requests/assets/131408227/55034163-0415-4c83-9945-dd0bf3190972)
