### ISSUE TITLE
Bot Login

### ISSUE THREAD

**Issue by Aragasu** [Aliucord/plugin-requests#1405]
### Discord Account

aragash

### Plugin Description

A login screen but instead of the email and password you need a bot token

### Go into more detail...

Like if you go into settings -> plugins and click settings on the bot login plugin you can change from your account to a bot account and back. just wanna chat as my bot

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Aragasu** [comment]
sry my username is not aragash but aragasu i had a typo

**Comment by OmegaSunkey** [comment]
nop
