### ISSUE TITLE
MessageSendSecond

### ISSUE THREAD

**Issue by i-am-unknown-81514525** [Aliucord/plugin-requests#1411]
### Discord Account

deleted.user0

### Plugin Description

A plugin that can show the message send time precise to second (i.e. Today 18:22:04 instead of Today 18:22)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OasisVee** [comment]
exists, CustomTimestamps
![Screenshot_20240720-131741](https://github.com/user-attachments/assets/970bb355-ea36-4a55-ba09-18228d645da1)
![ResizedImage_2024-07-20_13-20-37_2028](https://github.com/user-attachments/assets/525d3542-b59c-4251-af2c-d155f9fc3621)

**Comment by i-am-unknown-81514525** [comment]
Thx
