### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by Radiin91** [Aliucord/plugin-requests#1412]
### Plugin Description

Proxy connection would be great for anyone wanting more security or is unfortunately in a country where discord isn't allowed.

### Go into more detail...

Thats ok with vpns, right? V2rayNG dosent have proxy support. if theres any other app, I confess I'm dumb.
 How should it work?
  you enter the secret key, boom you got a proxy connection with a on and off button.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
You should rather use a VPN/proxy system wide or with split tunneling for Discord only. Making a plugin with that purpose just duplicates other apps that already do their job great. Also a plugin will most likely load too late after first requests to Discord.

I can recommend you https://mullvad.net/en if you are able to afford it, it does work in China, so should also in other countries with censorship.
