### ISSUE TITLE
Can you make this below plugin?

### ISSUE THREAD

**Issue by Duder-driod** [Aliucord/plugin-requests#1413]
### Discord Account

duder0930

### Plugin Description

Can you make a plugin thats make a cool banner in your profile without nitro (also if you can too do pfp gif)

### Go into more detail...

Probaly there isnt a plugin like that but also plz make it

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by shuvmaybe** [comment]
no way this real 😭

https://github.com/OmegaSunkey/awesomeplugins/tree/main/UserPFP
https://github.com/OmegaSunkey/awesomeplugins/tree/main/UserBG

**Comment by Duder-driod** [comment]
> no way this real 😭
> 
> https://github.com/OmegaSunkey/awesomeplugins/tree/main/UserPFP https://github.com/OmegaSunkey/awesomeplugins/tree/main/UserBG

Bro thoose dosent works anymore ask staff
