### ISSUE TITLE
GUYS THERE IS NO PLUGIN SINCE 2024 START

### ISSUE THREAD

**Issue by Duder-driod** [Aliucord/plugin-requests#1419]
### Discord Account

duder0930_

### Plugin Description

JUST MAKE OUR PLUGINS DONT CLOSE IT.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
stop spamming issues

**Comment by Duder-driod** [comment]
> stop spamming issues

Okay 😡
