### ISSUE TITLE
Copy part of the message

### ISSUE THREAD

**Issue by YaikaRace** [Aliucord/plugin-requests#142]
### Discord Account

YaiYai💮#3333

### Plugin Description

a plugin that allows you to copy part of a message instead of copying everything

### Go into more detail...

It could be an option in the contextual menu that allows you to open a window to select and copy part of the text, because discord only has the option to copy everything

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Wolfkid200444** [comment]
Theres already a plugin that does this is copy raw by Juby
u can find it in here 
https://github.com/Juby210/Aliucord-plugins
