### ISSUE TITLE
Desktop ui request

### ISSUE THREAD

**Issue by Sonoilprim** [Aliucord/plugin-requests#1423]
### Plugin Description

Hello.
Can an plugin be created for turn the phone ui to desktop based ui (like discord stock ui for tablet)
![20240808_192928](https://github.com/user-attachments/assets/4879f49b-de5a-46a1-a4f1-00ca87768b0d)
(Example)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Sonoilprim** [comment]
I forgot blur one of names 
Ops

**Comment by ghost** [comment]
I question how exactly you want this to fit on screen. Most phones don't have enough space to display all that without squishing the messages to the point they're unreadable.

**Comment by rushiiMachine** [comment]
if you want to try desktop ui on mobile just use web or vendroid
it's pretty terrible
