### ISSUE TITLE
Delete all messages sent by person from specific dm/server.

### ISSUE THREAD

**Issue by Gorkido** [Aliucord/plugin-requests#1426]
### Plugin Description

If we were able to use slash commands to delete the last **?** messages or all of it with a simple command, that would be great. thanks.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OasisVee** [comment]
self-botting (for self message deletion) and impossible for other peoples messages (it is possible if you are staff and the server has a moderation bot)
