### ISSUE TITLE
Favorite channels

### ISSUE THREAD

**Issue by Ketsuyumi** [Aliucord/plugin-requests#1439]
### Plugin Description

Favorite channels to show up before other channels.

### Go into more detail...

The same way it works on stable discord versions that are newer
Select to favorite, and then it would show up first on channels list

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OasisVee** [comment]
exists, have you not checked the [#new-plugins](https://discord.com/channels/811255666990907402/845784407846813696) channel

**Comment by Ketsuyumi** [comment]
I checked plugin repo
