### ISSUE TITLE
Show Forwarded Messages

### ISSUE THREAD

**Issue by IoIxD** [Aliucord/plugin-requests#1440]
### Plugin Description

Show Forwarded Messages

### Go into more detail...

I will take the bare minimum, I just want to be able to see them

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Oreo-Kuuki** [comment]
# MessageLinkEmbeds - [Download](https://github.com/Vendicated/AliucordPlugins/blob/builds/MessageLinkEmbeds.zip?raw=true)

Embeds discord message links

### https://github.com/Vendicated/AliucordPlugins

**Comment by TymanWasTaken** [comment]
MessageLinkEmbeds does not have support for forwarded messages

However, support has already been requested in Aliucord/Aliucord#470, as generally important backports like this are made as inbuilt coreplugins and thus should go in the main repository

**Comment by IoIxD** [comment]
> as generally important backports like this are made as inbuilt coreplugins and thus should go in the main repository

I swore I saw somebody saying that this being backported was a "maybe". Good to see its getting added in.
