### ISSUE TITLE
Fix settings

### ISSUE THREAD

**Issue by Ketsuyumi** [Aliucord/plugin-requests#1447]
### Plugin Description

plugin that makes settings without a blank space, which appears by default on aliucord, as shown in the image
![380426728-28a4aaff-8075-455e-b6f7-a790fc402088](https://github.com/user-attachments/assets/f5412d4b-6514-436b-bf3a-f30dfbbd9e2d)

### Go into more detail...

I would love to have settings look normal, without that space in the shared image, which isn't a plugin issue, just a plugin request I long wanted to ask.
If it's not easy to do, I appreciate reading this anyway, I won't ask for the impossible, would just love if this plugin existed.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
this is a known bug with the themer plugin
