### ISSUE TITLE
Fix Crashes of Aliucord Commands

### ISSUE THREAD

**Issue by awes956** [Aliucord/plugin-requests#1448]
### Discord Account

Awes955

### Plugin Description

A "Plugin" that changes something on the backend to **Prevent** Crashes/Freezes when using a custom _Aliucord_ Command, _**Keep it Up For Grab, maybe someone finds it and it's a big "W" to everyone**_ Pls

### Go into more detail...

Fixes Aliucord Crash during using custom Aliucord Commands "Keep it Up for Grab, maybe someone finds a way for it?"

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
If you are using plugins that crash, then report that to the plugin author.

Even if someone were to implement such a fallback, it'd probably be less hacky if it was a core feature.

**Comment by awes956** [comment]
nope it's universal to all plugins

**Comment by awes956** [comment]
Every plugin using chat functions, like "command" can crash or freeze due to depreciate Api handling

**Comment by awes956** [comment]
it's unfixable for The Aliucord Devs

**Comment by awes956** [comment]
let the community do it :)

**Comment by jedenastka** [comment]
> Every plugin using chat functions, like "command" can crash or freeze due to depreciate Api handling

What. No. If a plugin crashes during a command it's the plugin's fault. I never crashed Aliucord with a plugin command, and I imagine most other users can attest to that.

> it's unfixable for The Aliucord Devs

If it's not possible to fix in core then it's not possible to fix in a plugin.

Anyways I took a look at the core, and there's already a fallback in case a plugin command crashes in a recoverable manner. If it crashes anyways, it means something exceptionally wrong happened, which is not a common scenario, and you should report it to the plugin author.

**Comment by jedenastka** [comment]
![obraz](https://github.com/user-attachments/assets/858f7a3d-cd4a-4d7f-b483-b26301e2996c)

Assuming this is what you mean, fixing this is unrealistic, and plain impossible with a plugin.
