### ISSUE TITLE
my TapTap Issue

### ISSUE THREAD

**Issue by Honza572** [Aliucord/plugin-requests#1452]
### Discord Account

honza572

### Plugin Description

My simple issue is that I can't easiy reply to my own messages, I'd appreciate someone making a plugin that would work with TapTap (or even an entirely new plugin if that would be better, idk) That would reply when taptap, and you could edit your own messages with sliding from right to left or left to right (option in settings) or Maybe make it even more customizable with choosing more actions with more gestures, idk, all I need is taptap->reply and swipe->edit

### Go into more detail...

_null_

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by neko-astolfo-uwu** [comment]
![Screenshot_20241119_210114](https://github.com/user-attachments/assets/c8e602e9-77b0-46d0-b481-e832e0055475)

**Comment by Honza572** [comment]
@neko-astolfo-uwu yeah I found that later, still missing an option to edit with swipe :(

**Comment by jedenastka** [comment]
> still missing an option to edit with swipe :(

#1402
