### ISSUE TITLE
Message Links

### ISSUE THREAD

**Issue by Alii192** [Aliucord/plugin-requests#1457]
### Discord Account

poweringwarcriminals 

### Plugin Description

Not more of a plugin,but a backport of one of the best discord features;copying a message link/opening one would be GREAT and i havent seen one yet,hopefully this gets published!

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
MessageLinkContext plugin exists
as for opening message links, it's already built in
