### ISSUE TITLE
Automatically change Twitter/BlueSky/etc. links to their fx/vx alternatives to properly embed them.

### ISSUE THREAD

**Issue by PhenexFlame** [Aliucord/plugin-requests#1462]
### Discord Account

thevpblade

### Plugin Description

Similar to BetterDiscord's "SocialMediaLinkConverter" plugin, this would automatically transform a copied Twitter/BlueSky (or other similar platforms that have alternative embed links) to their alternatives since Discord still doesn't have proper embeds of these.

### Go into more detail...

Basically just give it similar functionality to [https://github.com/RoyRiv3r/SocialMediaLinkConverter.plugin.js](this) if possible.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
Please make a TextReplace rule instead.

**Comment by OasisVee** [comment]
here made a regex for it

from: https:\/\/(bsky\.app|(?:twitter|x)\.com)\/(.+?)(\s|$)
to: https://fx$1/$2

for settings:
regex: on
case insensitive: on
match unsent: on
match sent: optional if you want links people send to be rendered as the fx variant
match embeds: optional aswell

**Comment by OasisVee** [comment]
> here made a regex for it
> 
> from: https://(bsky.app|(?:twitter|x).com)/(.+?)(\s|$) to: https://fx$1/$2
> 
> for settings: regex: on case insensitive: on match unsent: on match sent: optional if you want links people send to be rendered as the fx variant match embeds: optional aswell

actually wait. x.com links will be broken with that regex

two rules both have same settings (tried to make it one rule, but i couldnt get it to work with the regex version textreplace uses)

rule 1 (bluesky and twitter):
find: https://(bsky\.app|twitter\.com)/(.*)
replace: https://fx$1/$2

rule 2 (x):
find: https:\/\/(x)\.com\/([^\s\)\]\}]+)
replace: https://vxtwitter.com/$2
