### ISSUE TITLE
VPN plugin for disabled countries

### ISSUE THREAD

**Issue by phoenixtriat** [Aliucord/plugin-requests#1464]
### Discord Account

Phoenixtriat

### Plugin Description

Hello 
This plugin is for discord disabled countries the plugin gonna open VPN when aluicord is opened I don't know how to make it i think anyone can help me

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
plugins cannot modify other apps
turn on the vpn yourself
