### ISSUE TITLE
Change the syrian flag to the free syria flag

### ISSUE THREAD

**Issue by ayman52O** [Aliucord/plugin-requests#1465]
### Discord Account

.ayman520.

### Plugin Description

Change the syrian flag from the dictatorship flag to the new free one
May God bless Syria

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
use an apk editor tool (for example [apktool](https://apktool.org/)) to replace the emoji png in the res folder with the png you want

and this repository isn't for political messages
