### ISSUE TITLE
New Discord UI

### ISSUE THREAD

**Issue by GlitchBruxo** [Aliucord/plugin-requests#1466]
### Discord Account

glitchbruxo

### Plugin Description

I love the old Discord interface, the one Aliucord currently uses. However, I—and likely many others—who have tried the new Discord interface often miss certain features when using Aliucord. 

Here are some examples:  
- **Replying by swiping**, similar to WhatsApp.  
- **Editing messages by swiping and holding**, which streamlines the process.  
- **Access to the app icon for bot systems**—as someone who works with bots, I find this particularly frustrating.  

Additionally, there are some bugs that make the experience less enjoyable. For instance:  
- When opening the server settings, one panel overlaps the other.  
![BugOnServerSettings](https://github.com/user-attachments/assets/77e436e1-b1fc-4eff-9c85-8412f37dcae1)

- Slash commands (`/`) don’t display properly, making it harder to use commands effectively. 
![BugOnSlashCommands](https://github.com/user-attachments/assets/9c01326f-e159-4e38-8a0e-477eeeb8464f)

While I appreciate the nostalgia of the old interface, these limitations and missing features can be inconvenient.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
Tabs V2 is not possible on Aliucord https://github.com/Aliucord/plugin-requests/issues/1322

If you want a RNA client mod then look at https://github.com/bunny-mod/Bunny (in mantinence-only)

Slash commands are currently being developed. As for the other features, feel free to make separate plugin requests if they do not already exist.

**Comment by OasisVee** [comment]
for swiping to reply and editing, check out the TapTap plugin. double tap for both
