### ISSUE TITLE
In-app theme editor

### ISSUE THREAD

**Issue by hjroh0315** [Aliucord/plugin-requests#148]
### Discord Account

CrO4 2-#0010

### Plugin Description

four base commands

/thshow - show current themer changes
/thapply (resource name) (value) - changes the resource to the value and restart app (values are saved in a separate file)
/thclear (resource name) - reverts the resource to default by removing it from the file
/thwrite (theme name) - writes the currently applied resources to an external file. opens the file manager ui if possible

make it possible to edit and make a theme inside aliucord with these 4 commands

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
Themes are not aliucord standard feature, request Themer features in Ven's Aliucord Plugins repo.
