### ISSUE TITLE
Copy raw text button

### ISSUE THREAD

**Issue by Vendicated** [Aliucord/plugin-requests#15]
### Description

Currently if you copy the text of a message, it copies the human readable version which makes it so that you can't copy paste any form of formatted content (mentions, emotes, codeblocks etc) 

this plugin should add a copy raw button that copies the raw content so that you can copy paste it and still keep emotes and such intact 

### More info

perhaps it could be useful to have a toggle between the following two copy methods:
- emotes are copied as :emotename: and mentions are copied as @​Ven#8810
- full raw copy: emotes are copied as <:emotename:3839273922> and mentions as <@37393839393902>

---

- [X] I checked if this plugin wasn't already requested.

**Comment by Juby210** [comment]
Suggestion for view raw and not for separate plugin.
