### ISSUE TITLE
Un-highlight "phone" numbers

### ISSUE THREAD

**Issue by Seb-135** [Aliucord/plugin-requests#152]
### Discord Account

Seb135#6817

### Plugin Description

Any string of numbers longer than 3 digits gets highlighted. Tapping it opens the phone app in an attempt to dial the number. 

![Screenshot_20210814_112021](https://user-images.githubusercontent.com/76539951/129443041-9030a65b-493c-4361-9cc7-0e850e2bba88.jpg)

Needless to say, nobody sends phone numbers over discord. A plugin to disable this behaviour would be neat, it messes with aesthetics.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
I will attempt this

**Comment by hjroh0315** [comment]
I think this is impossible - its likely OS behavior, unrelated to aliucord

**Comment by Seb-135** [comment]
Surely there has to be a way - the message timestamp isn't highlighted. 
I'm not sure about the specifics of the internals of mobile discord, but surely changing the properties of the message textbox to match those of the timestamp would work? It's not like the OS can go after *every* single textbox.

**Comment by zt64** [comment]
Pretty sure that its just some method that checks if it should highlight, ill look into it

**Comment by hjroh0315** [comment]
yeah I know, but this behaviour is found in several other messaging apps also, and **do note that the phone numbers do not use discord's accent color.** they use a separate color of blue which is fixed regardless of themeing and this is why I suspect that it's the OS's fault.

**Comment by zt64** [comment]
Completed, you can download it at from https://github.com/zt64/aliucord-plugins/raw/builds/NoLinkify.zip
