### ISSUE TITLE
favorite gifs

### ISSUE THREAD

**Issue by hjroh0315** [Aliucord/plugin-requests#153]
### Discord Account

CrO4 2-#0010

### Plugin Description

its a feature in desktop iirc pls port it to mobile

### Go into more detail...

u know that star button

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
[zt64/aliucord-plugins@builds/Frecents.zip (raw)](https://github.com/zt64/aliucord-plugins/raw/builds/Frecents.zip)

**Comment by KingOfStrangeness** [comment]
Dead..

**Comment by yutaplug** [comment]
https://github.com/zt64/aliucord-plugins/raw/builds/Frecents.zip
