### ISSUE TITLE
Alternate Report Button

### ISSUE THREAD

**Issue by Snare-Hawk** [Aliucord/plugin-requests#155]
### Discord Account

Snare-Hawk#6331

### Plugin Description

I was thinking of a plugin that either adds a button to the message context menu or replaces the current "Report" button with one that will send you to [Discord's "Submit a request" page](https://support.discord.com/hc/en-us/requests/new). The page would then launch like any other link one could open based on their chat behavior settings.

### Go into more detail...

The only thing other thing I can think of to add on would be that it also simultaneously copies the message link as well as open the page.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
Completed
https://github.com/DiamondMiner88/aliucord-plugins/raw/builds/AlternateReport.zip
