### ISSUE TITLE
Replace Dashes on Channel Name to Space

### ISSUE THREAD

**Issue by nattadasu** [Aliucord/plugin-requests#156]
### Discord Account

nattadasu#3867

### Plugin Description

As the title suggest, the plugin will replace (visually) the dashes on channel name to whitespace/nbsp as it wouldn't look like a mess. 

### Go into more detail...

* Basically a port of [`DashToSpaceInChannelName`](https://betterdiscord.app/plugin?id=278) BetterDiscord plugin by Niemiets.
* If possible, automatically change channel case to Title Case would look better, in my opinion.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by fym35** [comment]
This already exists
( https://github.com/NatSepruko/aliucord-plugins )

**Comment by nattadasu** [comment]
Welp, it seems NatSepruko made the [Dashless plugin](https://github.com/NatSepruko/aliucord-plugins#dashless) on Sep 3 (whilst I requested the plugin on Aug 16) but they didn't send any feedback to this issue **and** PluginDownloader didn't listed the plugin somehow.

I'll close this issue as it is working as I requested.
