### ISSUE TITLE
ServerSearch

### ISSUE THREAD

**Issue by MaciejK2** [Aliucord/plugin-requests#161]
### Discord Account

MaciejK2#2514

### Plugin Description

Add a server search in the search box (currently shows servers as a slider, the search would be faster than scrolling/searching for it on server list). Something like ctrl + k on desktop.
![file1](https://user-images.githubusercontent.com/75207983/129764374-87320d09-08fb-44ed-8b05-7f16a9161131.png)

### Go into more detail...

It would be nice if it was assigned to double-tapping the discord logo on top.
![file2](https://user-images.githubusercontent.com/75207983/129764621-aadb815e-122b-4629-8973-d5248f5bdd59.png)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Masterjoona** [comment]
Already a Discord feature
![Screenshot_20210817-194526](https://user-images.githubusercontent.com/69722179/129767037-dc6fd5f5-0332-479b-a582-d02c748e24bf.jpg)

**Comment by MaciejK2** [comment]
I know, but it shows only server channels, not servers itself (when searching)

**Comment by Masterjoona** [comment]
You can sort them from the top right button or adding * to the start like *Aliucord
