### ISSUE TITLE
No Bandwidth Kick

### ISSUE THREAD

**Issue by rollingmoai** [Aliucord/plugin-requests#166]
### Discord Account

itsmeboy#3660

### Plugin Description

Stops discord from disconnecting you when you're in a call alone for more than 5 minutes.

### Go into more detail...

Port of [NoBandwidthKick](https://github.com/slow/better-discord-plugins/tree/master/NoBandwidthKick) for Aliucord.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
I could not reproduce the kick on mobile (but that's just me)
