### ISSUE TITLE
Port of Powercord's webhook tags.

### ISSUE THREAD

**Issue by MemLiveOn** [Aliucord/plugin-requests#168]
### Discord Account

Kat System 😸#0001

### Plugin Description

shows when a bot tag is actually a webhook. Doesn't effect other user/bot/system tags.

### Go into more detail...

https://github.com/BenSegal855/webhook-tag

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by NatSepruko** [comment]
Hiya, [here you go](https://raw.githubusercontent.com/NatSepruko/aliucord-plugins/builds/WebhookTag.zip)!
