### ISSUE TITLE
Better message links

### ISSUE THREAD

**Issue by dmack6464** [Aliucord/plugin-requests#169]
### Discord Account

D Mack#4481

### Plugin Description

Instead of using an Android intent, tapping on message links should just jump to the message.
![Screenshot_20210820-154511_Android System](https://user-images.githubusercontent.com/29574547/130186103-6e358e4f-5bcd-4f55-b083-12961e4b8ecd.jpg)

### Go into more detail...

The FavouriteMessages plugin already does it, so all message links should be able to do this. (Perhaps even domain aliases? (xyz.discord.com/channels...)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Turtleb01** [comment]
This is implemented in [MessageLinkEmbeds](https://github.com/Vendicated/AliucordPlugins/tree/main/MessageLinkEmbeds), thanks @Vendicated
