### ISSUE TITLE
Fixing ghost unreads

### ISSUE THREAD

**Issue by Seb-135** [Aliucord/plugin-requests#170]
### Plugin Description

When a user sends and deletes a message, discord will keep the channel and server marked as unread until you click on the channel to see that nothing is there.
The plugin should mark the channel as read if the unread message(s) have been deleted.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
not possible without copious amounts of api spam
