### ISSUE TITLE
Custom badges

### ISSUE THREAD

**Issue by fym35** [Aliucord/plugin-requests#171]
### Discord Account

KongCz#7863

### Plugin Description

Plugin that allows you to locally assign the normal and custom badges to any user

### Go into more detail...

Plugin that will allow you to assign badges to any user ( nitro , hypesquad etc.) but also make a custom ones which you could also assign (something like betterdiscord's assign badges plugin or powercord's badges from pateron)

### Request Agreement

- [x] I did indeed check to make sure my plugin request is original!

**Comment by fym35** [comment]
forgot to write this : the badges will be assigned localy so only you will see them

**Comment by wingio** [comment]
ill take this

**Comment by hairyfred** [comment]
https://github.com/wingio/plugins/raw/builds/CustomBadges.zip
