### ISSUE TITLE
Spoiler Tagging Images

### ISSUE THREAD

**Issue by Cataku** [Aliucord/plugin-requests#175]
### Discord Account

Cataku

### Plugin Description

Couldn't see it in open suggestions, think it would be possible to enable us to spoiler tag images uploaded on mobile like you can on desktop? Couldn't find it in existing plugins either

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
It's already a feature of [MoreSlashCommands](https://github.com/Juby210/Aliucord-plugins/raw/builds/MoreSlashCommands.zip) as `/spoilerfiles` command.
