### ISSUE TITLE
Keyword Notifications

### ISSUE THREAD

**Issue by ellaxx16** [Aliucord/plugin-requests#179]
### Discord Account

🍓いちごミルク🥛#0999

### Plugin Description

Notifies you when someone says a keyword you set

### Go into more detail...

it would need a settings page or a slash command to set/remove/list keywords and push notifications if that's possible otherwise just in app notifs

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by wingio** [comment]
Done: https://github.com/wingio/plugins/raw/builds/KeywordAlerts.zip
