### ISSUE TITLE
Auto-Rename Sent Media

### ISSUE THREAD

**Issue by D3C0D3R5** [Aliucord/plugin-requests#18]
### Description
When you send an image or video, it will be automatically renamed.

### More info
It would be able to be customly renamed from "Plugin Settings" and by default when the plugin is enabled, it auto-renames images to "image0.png" and videos to "video0.mp4" (obviously if its a .jpg or an .mov or something else, it'll keep its original file format). If multiple images or videos are sent at the same time, it'll change the 0 to a 1-9 following the order of how its uploaded.

---

- [x] I checked if this plugin wasn't already requested.

**Comment by Swishilicous** [comment]
i'll take this one

**Comment by Swishilicous** [comment]
https://github.com/swishs-client-mod-plugins/aliucord-plugins/blob/builds/CustomFileFormat.zip?raw=true
