### ISSUE TITLE
Plugin idea

### ISSUE THREAD

**Issue by SyCzOfficialYT** [Aliucord/plugin-requests#181]
### Discord Account

SyCz # 4722

### Plugin Description

I think we would all be happy with a new nitro plugin. 

### Go into more detail...

I am aware that there is currently a plugin with the name ,,NitroSpoof" Exists. BUT a new plugin maybe "Nitro +" would be really cool. This plugin contains the Nitro features of the screen transmission. Which I would like very much if the 1080p 60 fps funktion would be usable. 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
Request features on the Nitro Spoof github instead of requesting a new plugin
