### ISSUE TITLE
Client Side Message Delete

### ISSUE THREAD

**Issue by 12brendon34** [Aliucord/plugin-requests#183]
### Discord Account

12brendon34#8636

### Plugin Description

Kinda self explanatory but it lets you delete any messages on the client only then replaces it with a small button or just text that says unremove message

### Request Agreement

- [x] I did indeed check to make sure my plugin request is original!

**Comment by Reinified** [comment]
[HideMessages](https://github.com/DiamondMiner88/aliucord-plugins/raw/builds/HideMessages.zip) does this.
