### ISSUE TITLE
Friend username history and search

### ISSUE THREAD

**Issue by KonozDOD** [Aliucord/plugin-requests#184]
### Discord Account

Konoz#5715

### Plugin Description

Ever have that on person on your friends list that randomly changes their name that has characters that you can't even type on your keyboard.

Well with this plug-in you can search your friends username ID history, so you know who is who, maybe you can a custom nick name to them so you don't forget them

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
I'm not sure if the username history is possible because I don't think discord stores the history

**Comment by rushiiMachine** [comment]
username history doesnt exist, friend nicknames is now a stock feature
