### ISSUE TITLE
Image Search Plugin

### ISSUE THREAD

**Issue by ChaoticMonkey** [Aliucord/plugin-requests#186]
### Discord Account

ThatOneMonke#1810

### Plugin Description

A plugin that allows you to long press on a particular image and give you the option of searching for it automatically via tools such as GoogleImage, TinyEye, etc and providing a link to the results

### Go into more detail...

An image searcher plugin which allows you to long press on an image and give you the option of searching for it using various image searching tools and then providing a link to the results.

Main use case would be searching for manga, memes, and such

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
A plugin that I'm working on includes this functionality

**Comment by ChaoticMonkey** [comment]
> You dont need to close it, close it after the plugin is finished/linked here

Very well

**Comment by Vendicated** [comment]
> A plugin that I'm working on includes this functionality

What plugin? I think it should be part of @X1nto's AttachmentUtils when you long press images

**Comment by Reinified** [comment]
> 
> 
> > A plugin that I'm working on includes this functionality
> > @zt64
> 
> What plugin? I think it should be part of @X1nto's AttachmentUtils when you long press images

https://github.com/zt64/aliucord-plugins/blob/builds/BetterMediaViewer.zip this plugin

**Comment by TymanWasTaken** [comment]
https://github.com/TymanWasTaken/aliucord-plugins/raw/builds/ReverseImageSearch.zip this is done
