### ISSUE TITLE
Custom Discord Backend URLs

### ISSUE THREAD

**Issue by NurMarvin** [Aliucord/plugin-requests#187]
### Discord Account

NurMarvin#1337

### Plugin Description

Basically swaps out the URLs to Discord's backend, e.g. the REST API or Gateway to something else of your choice, like a self hosted [Litecord](https://gitlab.com/litecord/litecord) instance or similar.

### Go into more detail...

As already mentioned, this plugin should let you change the URLs to each individual Discord backend URL, e.g. the REST API, which is `https://discord.com/api` normally, or the gateway URL, which `wss://gateway.discord.gg` normally, to something of your choice via a config file. Changing it via inputs in the app would probably also be nice, but shouldn't be the only way, since changing it to something invalid could render the app useless and the inputs to change the URLs back inaccessible.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by anotherdoesnm** [comment]
How to apply patch above? I don't saw doc to build Aliucord's Injector

**Comment by anotherdoesnm** [comment]
> However I made a patch for injector that should work (not tested cuz all current backend implementations suck and don't work with slightly different mobile client)

Oldcord works fine with Discord Android 126.21

**Comment by anotherdoesnm** [comment]
> How to apply patch above? I don't saw doc to build Aliucord's Injector

Now i figured how to build Injector but patch are incompatible now because written in Kotlin
