### ISSUE TITLE
Staff Tags

### ISSUE THREAD

**Issue by D3C0D3R5** [Aliucord/plugin-requests#19]
### Description
Custom tags for server staff members.

### More info
When a server staff member has the ability to manage messages and channels and other simple staff stuff, they would have a tag beside their name that says "Manager". When they have Administrator privileges enabled on their role, it'll have the tag "Admin" beside their name. And when they are the owner of the server it'll have the tag "Owner" beside their name.

---

- [x] I checked if this plugin wasn't already requested.

**Comment by vy-storm** [comment]
Ooo I quite like this!  And basing it off of the highest permission in their assigned roles is a clever way to achieve it.  That would be nice to have

**Comment by C10udburst** [comment]
MoreTags from https://github.com/c10udburst-discord/aliucord-plugins
this can be closed now
