### ISSUE TITLE
calltimer

### ISSUE THREAD

**Issue by alucardontop** [Aliucord/plugin-requests#199]
### Discord Account

alucard#1337

### Plugin Description

shows elapsed time in a vc
betterdiscord implementation:[https://github.com/QWERTxD/BetterDiscordPlugins/blob/main/CallTimeCounter/CallTimeCounter.plugin.js](url)
example:
![image](https://user-images.githubusercontent.com/89560393/131192157-fc6307cc-2788-4211-9c0e-8f32844fe5d1.png)

### Go into more detail...

very very very useful as discord only shows hours if it's a long vc and it only shows the exact time when you end it unless you calculate it yourself 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by TymanWasTaken** [comment]
Done https://github.com/TymanWasTaken/aliucord-plugins/raw/builds/CallTime.zip
