### ISSUE TITLE
Twemoji Everywhere

### ISSUE THREAD

**Issue by kyojn** [Aliucord/plugin-requests#202]
### Discord Account

Tav#7000

### Plugin Description

Port of Ven's PowercordTwemojiEverywhere for Aliucord. 

### Go into more detail...

Replaces the system emoji in server channels and (possibly) the text bar to Twemoji. I know that the emoji list in the android keyboard cannot be replaced without zFont/root.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by terabyte25** [comment]
https://github.com/vanniktech/Emoji - API for twemoji support on android

**Comment by DiamondMiner88** [comment]
this can be closed <https://github.com/wingio/plugins/raw/builds/TwemojiEverywhere.zip>
