### ISSUE TITLE
Assign badges

### ISSUE THREAD

**Issue by Itsnzk** [Aliucord/plugin-requests#205]
### Discord Account

឵n#4799

### Plugin Description

A plugin like the better discord one which you can select discord badges on your account like on screenshot
![572](https://user-images.githubusercontent.com/90006314/131911963-822ea4c7-6f9c-4065-9034-5e601e1eae0b.png)
Thanks !

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
https://github.com/Aliucord/plugin-requests/issues/171

**Comment by Flngithub** [comment]
Good

**Comment by buildintocopys** [comment]
its broken
