### ISSUE TITLE
Bookmark/favourite channels

### ISSUE THREAD

**Issue by dmack6464** [Aliucord/plugin-requests#206]
### Discord Account

D Mack#4481

### Plugin Description

Some people, like myself, have a lot of servers that they're in, sometimes only interested in a few channels.

### Go into more detail...

Channels that are bookmarked/favourited should also be able to be sorted into groups, sorta like personal guilds I guess.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
favorites is now stock
