### ISSUE TITLE
BiggerTextField

### ISSUE THREAD

**Issue by bordoga-bordoga** [Aliucord/plugin-requests#209]
### Discord Account

bordoga_bordoga#5386

### Plugin Description

Expand the text field in order to read more of your text and more easily edit/navigate it.

### Go into more detail...

Alternative 1: A small button at the top left corner to expand the text field. Either a fixed size or expandable.

Alternative 2: Automatically adjust the text field to fit the amount of text you have typed.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by wingio** [comment]
Will do

**Comment by hairyfred** [comment]
https://github.com/wingio/plugins/raw/builds/BetterChatbox.zip
