### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by vy-storm** [Aliucord/plugin-requests#21]
### Description
Add an image from within the plug-in settings which is then displayed as a background in all channels and DMs.

---

- [X] I checked if this plugin wasn't already requested.

**Comment by GangsterFox** [comment]
AA is currently doing it not sure if it will do what you say but it'll probably have changeable backgrounds

**Comment by vy-storm** [comment]
> AA is currently doing it not sure if it will do what you say but it'll probably have changeable backgrounds

Is AA working on in-app theming in general so you figure backgrounds will probably be apart of that?

**Comment by vy-storm** [comment]
> AA is working on theming for non-root users in general.

*celebration noises intensify*

**Comment by Vendicated** [comment]
Fulfilled by Themer https://github.com/Vendicated/AliucordPlugins/blob/builds/Themer.zip

**Comment by vy-storm** [comment]
> Fulfilled by Themer https://github.com/Vendicated/AliucordPlugins/blob/builds/Themer.zip

Sadly it doesn't do what I requested, it makes everything that image, it's not simply a background in DMs and channels

**Comment by Vendicated** [comment]
that looks really horribe, are you sure you want that?

**Comment by vy-storm** [comment]
![Screenshot_20210809-004338](https://user-images.githubusercontent.com/54405427/128788101-0ba56529-0b16-4832-97e1-42eea9ee442e.png)


> that looks really horribe, are you sure you want that?

I'm referring to this kind of thing (photo example for clarity), I guess looks are subjective but a lot of people like this style.  I think everything being transparent is a lot more ugly and visually confusing.  We might be talking about different things tho so I hope the picture helps.
