### ISSUE TITLE
Dm pinning

### ISSUE THREAD

**Issue by DeviL4939** [Aliucord/plugin-requests#213]
### Discord Account

D e v i L#0320

### Plugin Description

There is a feature in whatsapp where u can pin a dm/pm to make it show at the top always it would be cool to have that feature in discord too

### Go into more detail...

Adding an option "pin Dm" to the context menu of user to make it show at the top of this screen
![SmartSelect_20210907-185647](https://user-images.githubusercontent.com/90150373/132353314-155ff37b-9407-4648-b596-1191636084ce.jpg)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Reinified** [comment]
basic copy of issue #35, both ask for a dm to be pinned.

**Comment by OmegaSunkey** [comment]
alr exists and its called dmcategories https://discord.com/channels/811255666990907402/845784407846813696/921237766094880808
https://github.com/zt64/aliucord-plugins/raw/builds/DMCategories.zip
