### ISSUE TITLE
Close Embeds

### ISSUE THREAD

**Issue by ellaxx16** [Aliucord/plugin-requests#215]
### Discord Account

lovely+#3999

### Plugin Description

A plugin that lets you close embeds from links in the chat like on pc

### Go into more detail...

Probably should be a button somewhere on the menu when you hold a message down

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by C10udburst** [comment]
https://github.com/C10udburst/aliucord-plugins

**Comment by C10udburst** [comment]
https://github.com/C10udburst/aliucord-plugins

<sub>no self-botting features this time</sub>
