### ISSUE TITLE
Patch for Embed Mentions

### ISSUE THREAD

**Issue by Clari-7744** [Aliucord/plugin-requests#217]
### Discord Account

💜Clari#7744 (642416218967375882)

### Plugin Description

Make it so mentions in embeds actually work (both user and channel).

### Go into more detail...

User mentions have never worked in embeds, but a while ago channel mentions were made inactive too, it kinda sucks for usability so something that patches mentions would be cool.
Also maybe if user mentions that sometimes render as invalid could be fixed too? (not sure if the invalid-user plugin does that in embeds too)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
https://github.com/DiamondMiner88/aliucord-plugins
