### ISSUE TITLE
Extend In-app Notification Toast Time

### ISSUE THREAD

**Issue by Zefferis** [Aliucord/plugin-requests#219]
### Discord Account

Zeffy#4322

### Plugin Description

Allow users to extend the amount of time in which the notification toast stays on-screen. Or create a tab/menu to review previously notifications.

In-app notifications for discord appear for approximately 2.5 seconds or so, this is not very friendly for identifying what server / user / or message just appeared in the notification.  The two seconds makes it more of a nuisance than an actual helpful notification.

### Go into more detail...

A plugin that either allows for:

1) Setting variable times or set standard time for in-app notifications, ie; 4 seconds, 5 seconds, 8 seconds, ect.
2) Record and report the in-app messages in a settings menu for review by the user once the in-app notification goes away; possibly only keep the latest 10 in-app notifications and disregard the rest?

![image](https://user-images.githubusercontent.com/15270437/132782720-a445956f-059f-4a7d-8b39-00196e556473.png)

^ These notifications are just TOO fast, lasting a little shy of 3 seconds.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
https://github.com/zt64/aliucord-plugins/raw/builds/CustomNoticeDuration.zip
