### ISSUE TITLE
Better Call Confirmation Dialog

### ISSUE THREAD

**Issue by fym35** [Aliucord/plugin-requests#221]
### Discord Account

KongCz#7863

### Plugin Description

Maintained version of callconfirmationdialog plugin that shows a confirmation dialog when voice calling a user

Even if the unmaintained version still works it would still be better to have a maintained one

Edit : the unmaintained one no longer works :(

### Request Agreement

- [x] I did indeed check to make sure my plugin request is original!

**Comment by fym35** [comment]
The unmaintained version doesnt work anymore on V96 so i would really appreciate a maintained working one...

**Comment by scrazzz** [comment]
https://discord.com/channels/811255666990907402/845784407846813696/909923371838484520

**Comment by ItzOnlyAnimal** [comment]
reason why i should have repo access:
* I will delete the repo
* I will lock every issue as **too heated**
* I will not close issues that are duplicates
* im just trolling but you should also close this 
[MoarConfirm](https://github.com/ItzOnlyAnimal/AliuPlugins/raw/builds/MoarConfirm.zip)
https://discord.com/channels/811255666990907402/811275162715553823/896571282483728444

**Comment by fym35** [comment]
already exists , forgot to close lmao

https://github.com/ItzOnlyAnimal/AliuPlugins/raw/builds/MoarConfirm.zip
