### ISSUE TITLE
Rainbow text 

### ISSUE THREAD

**Issue by rickdtc** [Aliucord/plugin-requests#222]
### Discord Account

PUTDEMKNOCK#2006

### Plugin Description

A plugon that enables us to have rainbow text in text messages or typing status like in bluecord, would be a cool aesthetic honestly.
![Screenshot_20210911-141251_Bluecord](https://user-images.githubusercontent.com/74096544/132942242-07816d37-4150-441d-98b3-a9c1c3f29f43.jpg)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by terabyte25** [comment]
https://github.com/terabyte25/plugins/raw/builds/RainbowCord.zip

**Comment by rickdtc** [comment]
Thank you!

**Comment by Reinified** [comment]
awesome

**Comment by MrZeroLord** [comment]
Hey, adding an option for rainbow mentions would be great as well! :D 
Example
![zbLnOhUjcy](https://user-images.githubusercontent.com/40106969/134788652-fc891ca9-dbf3-4213-b3f0-b68100285f7d.gif)
:

**Comment by biast12** [comment]
@terabyte25 we got more people asking for the rainbow mentions now, any way you wanna look into adding that?

**Comment by rickdtc** [comment]
I think he is done with his aliu plugins

**Comment by biast12** [comment]
ok maybe we can get someone else to work on it and just do a pr instead
