### ISSUE TITLE
A plugin that lets you use the gallery app instead of the files app 

### ISSUE THREAD

**Issue by NaminBeforeGamin** [Aliucord/plugin-requests#223]
### Discord Account

Namin#1116(might change soon with my nitro ending)

### Plugin Description

This button used to give an option for a gallery app but now it just goes straight to files app
https://cdn.discordapp.com/attachments/811275334342541353/886368626477768755/Screenshot_20210911-145209.jpg

I would like the button to give me an option to use the gallery app because that is simply what I am used to. If possible, it would also be good if the gallery app had access to sending videos. I use the gallery app for sorting through my images and the current image selection is just not good. I cannot search for any favorite images at all. I am sure this is not an issue on my part as I am on the latest version of aliucord and it still does this

### Go into more detail...

I checked for any request involving the word "gallery" or "photo" and none related to this issue came up

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by RhythmLunatic** [comment]
Done. Tested on Android 8.0. Opens default gallery app. https://github.com/RhythmLunatic/aliucord-plugins

**Comment by RhythmLunatic** [comment]
Added a setting to allow all file types.
