### ISSUE TITLE
CopyRoleColor

### ISSUE THREAD

**Issue by Reinified** [Aliucord/plugin-requests#226]
### Discord Account

Soulz#0387 aka sexy

### Plugin Description

So there is a plugin for powercord that allows you to copy the color code when right clicking on a role in the user popout, the plugin is here: https://github.com/Antonio32A/copy-role-color

### Go into more detail...

continuing on, instead of discord automatically copying the role id for you instead it would pop up a context menu with multiple options, including the ability to copy the color in HEX. 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by terabyte25** [comment]
done, just waiting for jitpack to not be down
