### ISSUE TITLE
CopyRawMessage

### ISSUE THREAD

**Issue by Reinified** [Aliucord/plugin-requests#228]
### Discord Account

Soulz#0387

### Plugin Description

A plugin that adds a Copy Raw Message button to the message context menu, which will copy said message and its markdowns.

### Go into more detail...

I know ViewRaw already exists but instead of having to hold down on the text you want to copy, instead you would just press the CopyRawMesage button and automatically have it copied to your clipboard. Could be useful in certain situations.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
Request this in the view raw repo
