### ISSUE TITLE
CircularStatusIcons

### ISSUE THREAD

**Issue by Reinified** [Aliucord/plugin-requests#229]
### Discord Account

Soulz#0387 aka sexy

### Plugin Description

A plugin that would change the status options (Idle, DND,. and Invisible) to just be a full circle icons like the online one is.

Example:
![553](https://user-images.githubusercontent.com/54984650/133075317-c29f734d-0148-4e60-a42b-11ff69cbb78a.png)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by peter1599** [comment]
> ### Discord Account
> Soulz#387 aka sexy
> 
> ### Plugin Description
> A plugin that would change the status options (Idle, DND,. and Invisible) to just be a full circle icons like the online one is.
> 
> Example:
> ![553](https://user-images.githubusercontent.com/54984650/133075317-c29f734d-0148-4e60-a42b-11ff69cbb78a.png)
> 
> ### Go into more detail...
> _No response_
> 
> ### Request Agreement
> * [x]  I did indeed check to make sure my plugin request is original!

I could add this to BetterStatus.

**Comment by Reinified** [comment]
If you want to you can.

**Comment by peter1599** [comment]
Ok. Gonna add it. Expected release maybe... today. Cant say sure cause I have work. If something comes in I'll do it tomorrow.
