### ISSUE TITLE
Random Emote

### ISSUE THREAD

**Issue by vy-storm** [Aliucord/plugin-requests#23]
### Description
Sends a random emote.

### More info
Extremely silly idea, but bottom translator exsists so I get the feeling that you lot like to have fun.  Ideas for implementation:
• Type I'm feeling lucky into the emote search bar. (Fav)
• Slash command (Boring but functional)
• Hold the emote drawer button (A great unused trigger for a plug-in, but might be too good for something like this 😅)

---

- [X] I checked if this plugin wasn't already requested.

**Comment by zt64** [comment]
I made it so you can long press the emote button to send it, you can download it from https://github.com/zt64/aliucord-plugins/raw/builds/RandomEmote.zip
