### ISSUE TITLE
Last Online 

### ISSUE THREAD

**Issue by Therealloli101** [Aliucord/plugin-requests#231]
### Discord Account

Azrael#0195 

### Plugin Description

Something like the last online thing in watsapp if it's possible 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by peter1599** [comment]
Might add to BetterStatus

**Comment by Therealloli101** [comment]
That's an good idea

**Comment by DiamondMiner88** [comment]
#280
