### ISSUE TITLE
Local Pins

### ISSUE THREAD

**Issue by starspritechippy** [Aliucord/plugin-requests#232]
### Discord Account

Chippy#3660

### Plugin Description

My request is a plugin that allows you to pin messages on your device without having the Manage Messages permission. This would allow you to remember a message for later. Inspiration comes from BetterDiscord's [PersonalPins plugin](https://betterdiscord.app/plugin/PersonalPins) by DevilBro.

### Go into more detail...

The plugin should have an option "Pin locally" in the message context menu which saves the message. Along with that, there should be a button "local pins" next to the pinned messages button to view the saved messages.

There could be a way to filter messages from the same channel or server, similar to PersonalPins.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by peter1599** [comment]
There is already a plugin: https://discord.com/channels/811255666990907402/845784407846813696/878070010470334527

**Comment by starspritechippy** [comment]
Ah, I didn't catch that, my mistake. Thanks for showing me!
