### ISSUE TITLE
Scrollable too long names

### ISSUE THREAD

**Issue by Bednicoid** [Aliucord/plugin-requests#233]
### Discord Account

Bednič#0001

### Plugin Description

A plugin that will automatically scroll channel and account names that are too long just like the marquee names mod in bluecord. 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by terabyte25** [comment]
https://github.com/terabyte25/plugins/blob/builds/MarqueeEverywhere.zip?raw=true
