### ISSUE TITLE
Hide the top bar for real estate and AMOLED protection

### ISSUE THREAD

**Issue by siddhpant** [Aliucord/plugin-requests#235]
### Plugin Description

It would be good if the top bar with the Hamburger icon, channel name, and member list icon could be removed.

### Go into more detail...

It eats up unnecessary real estate on the screen.

- To open channel drawer or member list, you can swipe (which is what almost everyone does). So those icons are useless.
- Channel name is anyways shown in the typing space, or on the second drawer (the member list).
- Threads can be created by holding the channel name and choosing the Threads option in context. Maybe one can add an extra icon in the member list for threads.

Further, the top bar is static and doesn't move even while scrolling or typing, which will definitely cause burn-in on AMOLED phones if Discord is used regularly or sometimes for extended periods of time.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Similar to #4

**Comment by siddhpant** [comment]
Oops. Erroneous searching by me, my bad.

Though, are there any plans for implementing this?

**Comment by zt64** [comment]
So today I just noticed I have burn in from the top bar, so I'm gonna make this plugin

**Comment by zt64** [comment]
Done, I added quite a lot more than just hiding the top bar. Download is at https://github.com/zt64/aliucord-plugins/raw/builds/NoBurnIn.zip

**Comment by siddhpant** [comment]
Thank you so much!
