### ISSUE TITLE
@someone

### ISSUE THREAD

**Issue by VioletStorm** [Aliucord/plugin-requests#24]
### Description
Add @someone back, because we all miss it.

### More info
For those who don't know, @someone was an April Fools update which allowed people to ping a random person in a server.  Turned out everyone unironically loved it though and it is now one of the highest user requested features.  How is works is how you'd expect, simply type @someone and once the message is sent a random person will be selected to be pinged.

---

- [X] I checked if this plugin wasn't already requested.

**Comment by X1nto** [comment]
I'm grabbing this one

**Comment by vy-storm** [comment]
> I'm grabbing this one

Nice!!

**Comment by X1nto** [comment]
Sorry, I have to drop this. It's way harder than I thought and I can't figure out how to get the list of members in the channel.

**Comment by saintwithataint** [comment]
@Vendicated I think mantikafasi is working on this 
https://github.com/mantikafasi/AliucordPlugins/tree/main/Someone

**Comment by rushiiMachine** [comment]
unfortunately theres no good way to do this as the cached member list is tiny
(people at the top of the member list)
