### ISSUE TITLE
Unix Timestamps

### ISSUE THREAD

**Issue by saintwithataint** [Aliucord/plugin-requests#241]
### Discord Account

S'aint#2744

### Plugin Description

A plugin that allows the user to send unix timestamps.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
Like, current time or a date picker?

**Comment by MrAn0nym** [comment]
Already done by myself ^^
(Just called timestamps)

**Comment by DiamondMiner88** [comment]
close?
