### ISSUE TITLE
OCR

### ISSUE THREAD

**Issue by saint2706** [Aliucord/plugin-requests#242]
### Discord Account

S'aint#2744

### Plugin Description

A plugin that allows us to perform OCR and get the text from any image.

This could probably be implemented using an OCR API.

### Go into more detail...

A possible next update could be compatibility across languages and translation.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ow0x** [comment]
btw I found a free OCR API over a month ago which gives pretty decent results for anyone who may want to take this plugin request. The API is at https://api.kaogurai.xyz

FYI, this API uses Google vision OCR key under the hood and the key (theoritically has unlimited quota) was extracted from Speechify app as the person who owns this API has claimed it openly so feel free to try it out and go nuts lmao. :trollface: 

![IMG_20220407_095048](https://user-images.githubusercontent.com/24418520/162119736-4a21af1f-d640-45c5-ba55-06523fdf1672.jpg)

**Comment by rushiiMachine** [comment]
just use an ocr website manually this shouldnt be a plugin
