### ISSUE TITLE
Save settings on log out

### ISSUE THREAD

**Issue by dmack6464** [Aliucord/plugin-requests#243]
### Discord Account

D Mack#4481

### Plugin Description

With Bluecord, you can enable a setting that saves all Bluecord and some Discord settings when you log out.

### Go into more detail...

![Screenshot_20210917-020918_Bluecord](https://user-images.githubusercontent.com/29574547/133647605-9d3b9877-bb38-4a4c-817a-193364bb845c.jpg)
When you enable this setting, it makes account switching far less tedious, as things like appearance, dev mode and experiments are reset when you log out normally.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by terabyte25** [comment]
https://github.com/terabyte25/plugins/blob/builds/PersistSettings.zip?raw=true
