### ISSUE TITLE
Show full about me content

### ISSUE THREAD

**Issue by taskylizard** [Aliucord/plugin-requests#245]
### Discord Account

taskylizard#0001

### Plugin Description

For some weird reason, discord hides up long texts with `..` at the end, making the feature rather useless.

A plugin that shows the full content without hindering it would be awesome.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by terabyte25** [comment]
https://github.com/terabyte25/plugins/blob/builds/FullBio.zip?raw=true

**Comment by taskylizard** [comment]
Thank you, loving this!
