### ISSUE TITLE
Better Nitro Badge

### ISSUE THREAD

**Issue by Snare-Hawk** [Aliucord/plugin-requests#247]
### Discord Account

Snare-Hawk#6331

### Plugin Description

When you tapping on the Nitro badge on a user's profile, it usually brings up a dialog about the wonderful features of Discord Nitro. I've noticed when you do have Nitro, it simply tells you when the user got Nitro. I would like to see a plugin that does this for any user, regardless of if they have Nitro themselves.
![Screenshot_20210918-153930](https://user-images.githubusercontent.com/85657152/133906958-1a86f0b8-b582-4ea7-86e6-516637f8e44a.jpg)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by terabyte25** [comment]
https://github.com/terabyte25/plugins/blob/builds/FuckOffDiscord.zip?raw=true
