### ISSUE TITLE
Pascal Case 

### ISSUE THREAD

**Issue by ellaxx16** [Aliucord/plugin-requests#248]
### Discord Account

loveme!#0362

### Plugin Description

Plugin to make all words start with a capital letters

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
I'll do this :|

**Comment by scrazzz** [comment]
https://github.com/scrazzz/AliucordPlugins#capitalize

**Comment by vy-storm** [comment]
Why'd it not get marked as complete?
