### ISSUE TITLE
Always Animate GIF Avatar/Icon

### ISSUE THREAD

**Issue by vy-storm** [Aliucord/plugin-requests#25]
### Description
Always play any visible GIF profile pictures and server icons (separate toggles).

---

- [x] I checked if this plugin wasn't already requested.

**Comment by zt64** [comment]
Working on it

**Comment by zt64** [comment]
Done, you can download it from https://github.com/zt64/aliucord-plugins/raw/builds/AlwaysAnimate.zip

**Comment by hairyfred** [comment]
Will close once Always Animate is fully features

**Comment by hairyfred** [comment]
Will close this once Always Animate is fully features
