### ISSUE TITLE
PreviewMarkdownSyntax

### ISSUE THREAD

**Issue by Reinified** [Aliucord/plugin-requests#254]
### Discord Account

Soulz#0387

### Plugin Description

so on the desktop version of Discord, you have an option under Text & Images you have the option to preview emojis and markdown syntax as you type, I think it's a useful feature for discord, it's clean and simple.

Example:
![image](https://user-images.githubusercontent.com/54984650/134040924-64c2254b-8fc2-4e60-af51-3ce6c7c69c19.png)
![image](https://user-images.githubusercontent.com/54984650/134040952-1b00c7ef-2d8e-438d-b3b8-d9a170c9cad9.png)

### Go into more detail...

Import the discord feature onto mobile, afaik it's not an option on mobile.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by lenk** [comment]
This is now available, it can be closed, visit #Plugins-List in the Aliucord server!

[Aliucord-Plugins](https://github.com/lenk/aliucord-plugins)
