### ISSUE TITLE
CustomChannelIcons

### ISSUE THREAD

**Issue by Reinified** [Aliucord/plugin-requests#255]
### Discord Account

Soulz#0387

### Plugin Description

This plugin would change some channel icons, I don't know how else to describe it.
![image](https://user-images.githubusercontent.com/54984650/134041463-693f3a31-96d3-4208-bb7e-4809823d9d6a.png)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by wingio** [comment]
I'll take this

**Comment by Reinified** [comment]
sounds good, thanks!

**Comment by Reinified** [comment]
@wingio close this you already made plugin

**Comment by wingio** [comment]
https://github.com/wingio/plugins/raw/builds/BetterChannelIcons.zip
