### ISSUE TITLE
Channel Locker - Prevent Accidental Messages

### ISSUE THREAD

**Issue by bside-luke** [Aliucord/plugin-requests#257]
### Discord Account

LKD70#7070

### Plugin Description

A plugin similar to "Channel Locker" for PowerCord.
This plugin will prevent you from sending messages in any channel you ask it to do so.
This idea was implemented in pc by 'TaiAurori': https://github.com/TaiAurori/channel-locker

I feel this plugin is highly useful for those who have access to announcement or updates channels in larger servers where accidentally sending a message may cause a lot of hassle/distress.

### Go into more detail...

Taking the example of the powercord implementation, each channel (or the channels context-menu) would have an option to "Toggle Channel Lock" as shown here:
https://i.postimg.cc/wTzrgzXN/djh0e1-1.png

Enabling the toggle will change the send-message text field to a prompt to unlock prior to sending a message as shown:
https://i.postimg.cc/RmjDB1VT/vxvihw.png

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
Not accidentally sending an announcement

**Comment by ItzOnlyAnimal** [comment]
Done: [ChannelLocker](https://github.com/ItzOnlyAnimal/AliuPlugins/raw/builds/ChannelLocker.zip)
https://discord.com/channels/811255666990907402/845784407846813696/910048980170321961
