### ISSUE TITLE
Whisper command

### ISSUE THREAD

**Issue by rickdtc** [Aliucord/plugin-requests#259]
### Plugin Description

Whisper command like minecraft, messaging someone in normal chat without letting others know

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
DMs: *exist*. There is no point to make it, since DMs and in app notifications just exist.

**Comment by SudoHCT** [comment]
Try Private Messaging people if they have DMs open, that's one way
