### ISSUE TITLE
View Full Screenshare Previews Without Joining Call

### ISSUE THREAD

**Issue by D3C0D3R5** [Aliucord/plugin-requests#26]
### Description
The ability to see the best quality preview of what someone is screensharing without having to join the call.

### More info
Pressing the 3 dots on the top right of someone profile (if they are screensharing) would bring up a "Copy Screenshare Image URL" button. Once pressed, it would copy the URL of the screenshare preview to your clipboard, ready to be pasted in a browser on someones chat to see in better quality.
---

- [x] I checked if this plugin wasn't already requested.

**Comment by WinstonSepruko** [comment]
This is not possible, as Discord will not send that data to you without you being in the call.

Closed due to technical limitations.

**Comment by WinstonSepruko** [comment]
Reopened due to miscommunication.

**Comment by Juby210** [comment]
Done. You can open stream preview in Discord's image viewer by clicking on it.
 https://github.com/Juby210/Aliucord-plugins/raw/builds/ViewStreamPreview.zip
