### ISSUE TITLE
⠀

### ISSUE THREAD

**Issue by Moooodle** [Aliucord/plugin-requests#260]
### Plugin Description

One of those bluecord 🤢 features 

### Go into more detail...

A plugin that lets us set out own commands like the one in bluecord

(u type ! and some commands pop up that only u can see)

![Screenshot_2021-09-21-18-33-58-42_5a415ff834f6bc153619606941c55eb5](https://user-images.githubusercontent.com/88912716/134221219-3fd83c05-dbc8-4240-bf3d-ff10c4c693ac.jpg)

![Screenshot_2021-09-21-18-33-49-13_5a415ff834f6bc153619606941c55eb5](https://user-images.githubusercontent.com/88912716/134221286-d822c197-d5d4-406d-a4ef-ee90ada4407a.jpg)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
1. Please format your plugin request properly. theres no title etc
2. Custom tags exist
3. If custom tags do not have all the functionality you want, please edit this request to be more detailed

**Comment by hairyfred** [comment]
Close was a mistake

**Comment by hairyfred** [comment]
Closed
Custom Tags
