### ISSUE TITLE
Hide Stage Discovery Button

### ISSUE THREAD

**Issue by TheJesterRose** [Aliucord/plugin-requests#261]
### Discord Account

Innocence#3180

### Plugin Description

Simple as. A plugin that hides the Stage Discovery button for those of us who don't care for the feature and are tired of accidentally hitting it. 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by nattadasu** [comment]
Here's what I did to my Aliucord client to revert Stage Discovery to Search button:

1. Install [Experiment by Juby210](https://github.com/Juby210/Aliucord-plugins) plugin.
    * If you have any running client instance after downloading it, restart the app.
2. Open settings menu, there's should be a new button calls "Developer Options." It's above App Information section. 
3. Scroll slowly, search for **Stage Discovery for Users**.
4. If the dropbox is set to "Select...," replace with "Bucket 0."
5. Stage Discovery option was replaced to old Search option.
    * If it didn't replaced, restart your client (again).

This workaround is still working on current Aliucord release (which is 89.8 — Beta `89108` | Aliucord 0a82b19fb7987fdf0c118f14df76bcda09ec370c).

**Comment by nattadasu** [comment]
Oh also, I forget to mention this.

If you think you want to disable it fully, you might want to make an issue to LayoutController plugin repo, as the plugin controls what do you want to show and hide some of bloats/useless features.

**Comment by hairyfred** [comment]
> 
> 
> Oh also, I forget to mention this.
> 
> If you think you want to disable it fully, you might want to make an issue to LayoutController plugin repo, as the plugin controls what do you want to show and hide some of bloats/useless features.
> 
> _thou, I wonder why you want to fully disable it when you can replace it with very useful feature_ 🤔

 Im going to close this as right now you can disable it via an experiment
 in future as long as the code is kept inside the discord apk and the experiment is removed, it should be a layout controller request
