### ISSUE TITLE
Force enable message push notifications in large servers

### ISSUE THREAD

**Issue by 5h3i1ah** [Aliucord/plugin-requests#263]
### Discord Account

5h3i1ah#6253

### Plugin Description

In large servers, Discord will not allow you to receive push notifications for regular messages (though it does allow for them in threads, strangely enough...). This plugin would add an option to override that and receive such push notifications anyway.

### Request Agreement

- [x] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
Not possible, this is server side
