### ISSUE TITLE
Copying servers without templates

### ISSUE THREAD

**Issue by rickdtc** [Aliucord/plugin-requests#264]
### Plugin Description

A plugin that lets us copy a server without templates, all its channels with all its perms, and also saves a doc with all the ids and tags of the bots with their perms in that server because copying bots is not possible. But all should be done with maintaining rate limit.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Reinified** [comment]
selfbot behavior 😬
