### ISSUE TITLE
Rainbow mentions (maybe as theme)

### ISSUE THREAD

**Issue by MrZeroLord** [Aliucord/plugin-requests#267]
### Discord Account

Mr.Zer0#0003

### Plugin Description

RGB color change as mention color
Example:
![zbLnOhUjcy](https://user-images.githubusercontent.com/40106969/134788606-3db9d188-8806-4e6f-94f4-89d56793276a.gif)
 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
Going to say this should be combined with https://github.com/Aliucord/plugin-requests/issues/222
