### ISSUE TITLE
Font into reality

### ISSUE THREAD

**Issue by ManadyV** [Aliucord/plugin-requests#269]
### Discord Account

Manady#0028

### Plugin Description

I think it would be cool if we could use our own fonts and when we send a message using it, others (like non-aliucord users) would be able to see it

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
Not possible
Closest you can get is using fancy ascii like this https://lingojam.com/FancyTextGenerator
