### ISSUE TITLE
Bring back 1 click delete

### ISSUE THREAD

**Issue by iDutchy** [Aliucord/plugin-requests#272]
### Discord Account

Dutchy#6127

### Plugin Description

When wanting to delete a message, discord added a prompt a long time ago if you're sure you want to delete. This wasn't always the case, so I'm requesting a plugin that removes the prompt and just deletes when clicking delete from the context menu

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
I'll make this

**Comment by iDutchy** [comment]
> I'll make this

Any progress on this? :)

**Comment by DiamondMiner88** [comment]
zt is dead

**Comment by iDutchy** [comment]
> zt is dead

Oof, any chance of anyone else making this? I'd do it myself because it seems relatively simple to make, but I've only ever worked with Python 😅

**Comment by DiamondMiner88** [comment]
completed:
https://github.com/DiamondMiner88/aliucord-plugins/raw/builds/1ClickDelete.zip

zt stupit it took me 4 minutes to make this
