### ISSUE TITLE
In-app video player for Twitter embeds

### ISSUE THREAD

**Issue by MuffinOfPotato** [Aliucord/plugin-requests#273]
### Discord Account

PotatoMuffin#1784

### Plugin Description

Plays videos from embedded Twitter posts by utilizing an in-app video player.

Similar to #127 and #104, though this request focuses exclusively on Twitter post embeds.

### Go into more detail...

On mobile, Discord tries to open the Twitter app when the user attempts to select a video in an embedded tweet, as opposed to opening Discord's in-app video player. If feasible, being able to quickly view Twitter videos in-app could help scrolling through various posts to become far more seamless.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by RhythmLunatic** [comment]
Done (kind of). https://github.com/RhythmLunatic/aliucord-plugins/raw/builds/ShowAllTwitterImages.zip
Yes it supports videos too despite the name, it's disabled by default since it's kind of beta.
