### ISSUE TITLE
Hide Status Bar

### ISSUE THREAD

**Issue by Vexalus** [Aliucord/plugin-requests#274]
### Discord Account

Voxel#8210

### Plugin Description

A plugin that hides the android status bar throughout the entire app, to reduce clutter and chances of burn-in on oled devices. 

### Go into more detail...

I know that the Better Media Viewer plugin has an option to hide the status bar while looking at media, so I basically want that but across the entire app to help prevent burn-in on oled devices. That, plus the status bar is just ugly, so hiding it would be a nice aesthetic change. 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by vy-storm** [comment]
You can hide the status bar across your entire phone by forcing immersive mode to on for it, I use MacroDroid for this but only when I turn on do not disturb.  I agree that hiding the status bar in discord with a plugin would be nice though, just figured I'd mention this other option in case you want it gone everywhere.
