### ISSUE TITLE
Youtube redirect to YT Vanced

### ISSUE THREAD

**Issue by MrZeroLord** [Aliucord/plugin-requests#275]
### Discord Account

Mr.Zer0#0003

### Plugin Description

when clicking on the yt link **!(not the inapp player)** you are getting redirected to the yt-vanced app  instead of the original youtube app

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
Set YouTube Vanced to open supported links
Just tested and it works
