### ISSUE TITLE
Remove administration badges 

### ISSUE THREAD

**Issue by Therealloli101** [Aliucord/plugin-requests#278]
### Discord Account

Azrael#0195 

### Plugin Description

I would like to have a plugin wich removes these administration badges because it confuses me, especially when they are custom badges

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
What do you mean by administration badges?

**Comment by Therealloli101** [comment]
These crown things

**Comment by DiamondMiner88** [comment]
You mean server ownership crowns like these
![hydar crown](https://user-images.githubusercontent.com/33725716/141334492-48c29937-01e3-47ca-999a-9b8150531d79.PNG)
e?

**Comment by Therealloli101** [comment]
> You mean server ownership crowns like these? ![hydar crown](https://user-images.githubusercontent.com/33725716/141334492-48c29937-01e3-47ca-999a-9b8150531d79.PNG)

Yes

**Comment by DiamondMiner88** [comment]
Merged into LayoutController, can be closed
