### ISSUE TITLE
Last Time Seen/Online

### ISSUE THREAD

**Issue by Excarius** [Aliucord/plugin-requests#280]
### Discord Account

Kιzuhara#1111

### Plugin Description

I want to request if "Last seen online" feature can be possible?

It should basically look into people's status on profile and just like WhatsApp status, to show whether the user when he/she got status switched (from Offline mode to any other mode).

Could be perhaps implemented by ticking specific users ID (if mutual server & friends) so it does not overload phone and become resource hungry.

After adding specific IDs of Discord people, it should every x second check the status flag (if Online/Offline).

It could be set to every 10seconds

To avoid excessive ID Online status check, the plugin can limit itself to 3 checks per 1-2 second, to minimize impact of performance.

Its not useful feature but its definitely a handy feature for many people.

It could be similar to Accounts plugin to add people's Discord ID.

And it sends this info to a custom profile page main (someone's main discord profile).

This shouldnt cause any API ratelimit or cause any bans. It should fetch this info locally that is sent from discord server, and read it, if status changes locally, it updates that user's profile with a message, like "Last Status Change: 2021/09-23 19:25:47PM (Offline/Do Not Disturb/Idle)

It helps you know if you get ignored or if someone quickly logins discord and changes their status etc.

With future updates this could be further improved with few more simple *math* requiring updates to make more use of this feature/plugin.

The way plugin is intended to work is totally safe as its fully locally updated/fetched.

As long as discord runs on background, it should continue do its job.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Reinified** [comment]
iirc this is being added to userprofiles sometime, but i may be wrong.

**Comment by Reinified** [comment]
also very similar to #231

**Comment by Excarius** [comment]
Similar yes but his was too simple, i explained more depth how this could be implemented and be working to make it work smooth, programmer needs to code it that way with the idea.

Also, 
![Screenshot_20210930-035411](https://user-images.githubusercontent.com/12131986/135372955-d2d1f30d-38b0-422f-9c20-9aee42ab3f16.jpg)
It shows last message, it could be additionally added there an extra message row to update added user's ID to update their status.

**Comment by Excarius** [comment]
Maybe the Plugin named "UserDetails" by Juby210 can implement this idea to the pre-existing plugin as an upgrade.

**Comment by Reinified** [comment]
you could make a PR in userdetails github if you want or talk about it in the server in #plugin-development.

**Comment by rushiiMachine** [comment]
not possible as discord does not run in the background
