### ISSUE TITLE
DiscordClock

### ISSUE THREAD

**Issue by Reinified** [Aliucord/plugin-requests#282]
### Discord Account

Soulz#0387

### Plugin Description

plugin to add a clock with the option to use 12/24 hour times above the Discord button. 

### Go into more detail...

![image](https://user-images.githubusercontent.com/54984650/135484408-47c0f115-6b8f-4d6e-a592-4853a00422ad.png)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by BobIsMyManager** [comment]
Isnt there already a clock on your phone in about the same place? ![IMG_20210930_162549.jpg](https://user-images.githubusercontent.com/70704875/135484829-ccfd1e60-558e-4fe6-9812-d5376843cbbb.jpg)

**Comment by BobIsMyManager** [comment]
Seems kinda redundant but hey, maybe thats just me

**Comment by rushiiMachine** [comment]
system clock
