### ISSUE TITLE
Port of OnlineFriendsCount

### ISSUE THREAD

**Issue by Reinified** [Aliucord/plugin-requests#283]
### Discord Account

Soulz#0387

### Plugin Description

Port of the powercord plugin [OnlineFriendsCount](https://github.com/GriefMoDz/online-friends-count)

### Go into more detail...

I just think it would look nice, there would be a settings menu to customize what shows up.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
https://github.com/rushiiMachine/aliucord-plugins#counters
