### ISSUE TITLE
Server and friend removal alert

### ISSUE THREAD

**Issue by Stabbystabby1** [Aliucord/plugin-requests#284]
### Discord Account

Stabby#6061

### Plugin Description

This plugin notifies you whenever a friend has unfriended you or you have been kicked/banned or removed from a server. It would be useful to know if a friend has silently unfriended you or blocked you and it would tell you whether you got banned or kicked from a server or the server got deleted. 

### Go into more detail...

Similar to "guild and friend removal alerts" the better discord plug in this plugin should have exactly the same purpose and function

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by C10udburst** [comment]
https://github.com/c10udburst-discord/aliucord-plugins/raw/builds/Notifier.zip

**Comment by C10udburst** [comment]
this can probably be closed now

<@&811256800262619136>
