### ISSUE TITLE
number bans in ban page

### ISSUE THREAD

**Issue by weluvxyber** [Aliucord/plugin-requests#285]
### Discord Account

Xyber#0001

### Plugin Description

the plugin i want is to show bans in ban page in numbers like in a desktop browser for more details ill send a pic! shorturl.at/dfsSV 
i would really love if u would make that a plugin! thx so much
![Screenshot_20211001-092423_1](https://user-images.githubusercontent.com/83379269/135575469-e0e1e047-ca3e-4f9c-8baa-d618c5768aff.png)

### Go into more detail...

i would really like it to be a plugin thanks so much! i dont need to talk more about it because its a small request! thanks again.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
https://github.com/zt64/aliucord-plugins/raw/builds/BanCount.zip
