### ISSUE TITLE
Customize double tap on message action

### ISSUE THREAD

**Issue by iAndyHD3** [Aliucord/plugin-requests#287]
### Discord Account

iAndy_HD3#3579

### Plugin Description

Basically, a plugin that lets you customize the double tap on message action. In settings you would be able to choose an action from the long-hold menu (reply, create thread, profile, copy text, copy id, delete/pin if possible etc.) The best would be if the plugin could know the options that are available in the long-hold menu and make it compatible with other plugins that add actions to that menu e.g (quoter plugin, view raw, translate). 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Reinified** [comment]
similar to #2

**Comment by iAndyHD3** [comment]
I checked only in first page of issues sorry for that lol
