### ISSUE TITLE
hide gift nitro button

### ISSUE THREAD

**Issue by abashir7866** [Aliucord/plugin-requests#288]
### Discord Account

abashir7866#7708

### Plugin Description

I would really like a plugin that hides the "gift nitro" button, thats all really.

### Go into more detail...

I haven't found a plugin that hides the button. If there is a button, let me know.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Reinified** [comment]
[LayoutController](https://github.com/X1nto/AliucordPlugins/blob/builds/LayoutController.zip) does this.

**Comment by abashir7866** [comment]
Thank you, ill close the issue.

**Comment by hairyfred** [comment]
In future please check #plugins-list
