### ISSUE TITLE
numbers of bans in ban page

### ISSUE THREAD

**Issue by against-discord-tos** [Aliucord/plugin-requests#289]
### Discord Account

abashir7866#7708

### Plugin Description

id like a plugin where it shows how many bans in ban page in mobile, i have a big server and its frustrating to count them. thanks so much!

### Go into more detail...

it would be a really good plugin for big dev and in a big servers.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
https://github.com/Aliucord/plugin-requests/issues/285

**Comment by against-discord-tos** [comment]
u good bro?

**Comment by against-discord-tos** [comment]
yo fred u making the plugin soon 👀👀

**Comment by against-discord-tos** [comment]
wym duplicate

**Comment by against-discord-tos** [comment]
alright

**Comment by against-discord-tos** [comment]
GitHub > discord

**Comment by against-discord-tos** [comment]
dont ban

**Comment by against-discord-tos** [comment]
weak

**Comment by against-discord-tos** [comment]
ass

**Comment by against-discord-tos** [comment]
faggot

**Comment by against-discord-tos** [comment]
u getting

**Comment by against-discord-tos** [comment]
spammed pussy

**Comment by against-discord-tos** [comment]
what?

**Comment by against-discord-tos** [comment]
lame skid

**Comment by against-discord-tos** [comment]
pussy

**Comment by against-discord-tos** [comment]
furry ass nigga

**Comment by against-discord-tos** [comment]
nigger
