### ISSUE TITLE
Spoiler tagging on image upload

### ISSUE THREAD

**Issue by Ashford4989** [Aliucord/plugin-requests#29]
I've been wanting this feature forever. It is on pc and requires adding `_SPOILER_`  prefix before image name on mobile. I was wondering if it was possible to make a plugin for this.

**Comment by WinstonSepruko** [comment]
Closed for:

- Not following the template
- This is already included with [this plugin](https://github.com/Juby210/Aliucord-plugins/blob/builds/MoreSlashCommands.zip).

Please make sure you check through our plugin channel(s) in the [Support Discord](https://discord.gg/EsNDvBaHVU) to check which plugins exist, check through other issues here to see if it already has been requested/completed as well as follow our template.
