### ISSUE TITLE
Time Zone Plugin

### ISSUE THREAD

**Issue by Snare-Hawk** [Aliucord/plugin-requests#293]
### Discord Account

Snare-Hawk#6331

### Plugin Description

A simple plugin that would allow users to locally note time zones for specific user. Similarly to the Juby210's [PronounDB](https://github.com/Juby210/Aliucord-plugins#pronoundb), I would envision the plugin would display the time for one on one's user page.

### Go into more detail...

Some other things I could see would be customization to setting the times, such as toggling whether or not UTC is shown. Additionally, I could see the times could be taken from a site like how the aforementioned PronounDB plugin works, although, I believe a site hosting time zones is far more impractical than pronouns.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
https://github.com/ItzOnlyAnimal/AliuPlugins
