### ISSUE TITLE
Copying usernames, statuses and about me from user profile

### ISSUE THREAD

**Issue by rickdtc** [Aliucord/plugin-requests#295]
### Plugin Description

In desktop we can freely select any text we want, it would be cool to have a plugin that lets us select and copy any part of username, statuses, about me sections.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
This issue is you hold down a message for the context menu
This is the same way you hold down text and select
If this plugin is to work it needs to change the hold down for context to something else eg a double tap or something

**Comment by Reinified** [comment]
but you would only hold down text on the profile card, the message context menu is different, so it should work fine because afaik there is no context menu on the users profile card.

**Comment by Reinified** [comment]
> These are differnt Ven wants all options to be copy able (eg probs a button/hold down) This guy wants parts to be selectable (treats it like normal text)

ah my mistake, sorry for the inconvenience.

**Comment by Ushie** [comment]
You have essentially been given the desktop "copy anything" power by circle to search, making this request obselete

**Comment by dxcvvxd** [comment]
> You have essentially been given the desktop "copy anything" power by circle to search, making this request obselete

some people lowkey dont have it or dont use it for one reason or another

**Comment by Archimedes9500** [comment]
> some people lowkey dont have it or dont use it for one reason or another

Maybe, but something like [`com.camel.corp.universalcopy`](https://play.google.com/store/apps/details?id=com.camel.corp.universalcopy&hl=en-US) is probably better than anything aliucord will ever have
