### ISSUE TITLE
Custom Message Tags

### ISSUE THREAD

**Issue by omxpro** [Aliucord/plugin-requests#297]
### Discord Account

@OmxproYT#1165

### Plugin Description

So we should be able to make custom slash command messages (this is selfbot behavior btw) like /tag create [Command name (the thing shows up when we do /)] [Message] this could be very useful for the discord server mods that are using Aliucord as a tool to welcome people or tell them the rules and etc etc stuff, if you do look into it there can be a embed version of this too wich uses we hooks and grabs data from SendEmbed plugin it could work in 2 different way

1. Normal messages using / commands
2. Embeds using webhooks and SendEmbed plugin

### Go into more detail...

All the details are above 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by taskylizard** [comment]
[Juby210's Tags](https://github.com/Juby210/Aliucord-plugins#tags) plugin does exactly that.
