### ISSUE TITLE
Emoji Utilities

### ISSUE THREAD

**Issue by TheOddGarlic** [Aliucord/plugin-requests#3]
### Description
A plugin that allows users to "steal" (clone to another guild) emojis.

### More info
Preferably adds a button just after the "Add to Favourites" button in the emoji menu.

---

- [x] I checked if this plugin wasn't already requested.

**Comment by Juby210** [comment]
@Vendicated said that he is working on that.

**Comment by Vendicated** [comment]
Done! https://github.com/Vendicated/AliucordPlugins/tree/main/EmojiUtility
