### ISSUE TITLE
Client side roles/avatar

### ISSUE THREAD

**Issue by KeeperOverlord** [Aliucord/plugin-requests#301]
### Discord Account

cikeZ00#5068

### Plugin Description

I think a plugin that makes it so u can have custom client side roles/ would be cool, they could be in a different category than roles "below the normal/original" roles so they dont conflict. Also the client side avatar so u can have a .gif profile u can see or if with a custom user database, certain users with the database could see it too.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
Im rejecting this NOT because of the concept
More because these are probs better suited to 2 separate plugins
Make 2 new issues with each idea as a separate plugin
