### ISSUE TITLE
No back button exit

### ISSUE THREAD

**Issue by Cynosphere** [Aliucord/plugin-requests#303]
### Plugin Description

Changes to prevent the back button from exiting the app

### Go into more detail...

If in friends list, recent mentions or settings, it should return to the guild/channel list.
If in the guild/channel list it should close it.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Reinified** [comment]
afaik there are no settings to change it, so it could be my device. not sure

**Comment by saintwithataint** [comment]
@hairyfred and <@304675387416379392>
