### ISSUE TITLE
BetterChannels

### ISSUE THREAD

**Issue by Reinified** [Aliucord/plugin-requests#305]
### Discord Account

Soulz#0387

### Plugin Description

so, this is kinda hard to explain.
This plugin will allow you to drag and drop channels and create channels faster, just like desktop does.

### Go into more detail...

having the ability to quickly create channels and the drag and drop mechanism would be great.

![Screenshot_20211008-181516_Kiwi Browser](https://user-images.githubusercontent.com/54984650/136630448-21e1bf92-d137-4eec-b2a1-5da3508fe353.png)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
https://github.com/Aliucord/plugin-requests/issues/633#issuecomment-1051071994
https://user-images.githubusercontent.com/94068062/155764238-7a36ef46-b68b-4a87-a8de-a62e4b013c5d.mp4
Reposting here for people who can actually use github search before making issues
