### ISSUE TITLE
ViewFullEmbeds

### ISSUE THREAD

**Issue by Reinified** [Aliucord/plugin-requests#306]
### Discord Account

Soulz#0387

### Plugin Description

so I don't know if this is because of discord or because of the bot, but sometimes if an embed is too long, it will cut off.

### Go into more detail...

if it is possible, instead of cutting off it could show the entire embed and all of its text, oh and maybe preview images too?

![Screenshot_20211008-182353](https://user-images.githubusercontent.com/54984650/136630952-929f4ab9-6db1-49dc-aa4e-58a46429b558.png)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
this is not a thing lol, the github embeds are just trimmed to 2k characters by discords backend

**Comment by Reinified** [comment]
oh
