### ISSUE TITLE
Fix for identical emoji names rendering the "0"th one unusable

### ISSUE THREAD

**Issue by 5h3i1ah** [Aliucord/plugin-requests#311]
### Discord Account

5h3i1ah#6253

### Plugin Description

When you have access to more than one emoji of a given name, the "0"th one is unusable. This plugin should fix that.

### Go into more detail...

With Nitro, when you have multiple emojis of the same in different servers, Discord appends a "-x" to every one after the "0"th one, i.e. ":emoji-1:" ":emoji-2:". However, this apparently renders the 0th one unusable. When trying to send it in the emoji picker, it just sends ":emoji:", which doesn't format into an emoji because multiple emojis of that name exist. Manually typing ":emoji-0:" also doesn't do anything.
![image](https://user-images.githubusercontent.com/17099837/136678588-a88cb8fb-2a9f-4a0e-98c0-9994d2fcd9a8.png)

This plugin should make it so that typing ":emoji:" sends the "0"th emoji, as expected. Additionally, there could be a feature to set which emoji is the default when sending just ":emoji:", and sending ":emoji-0:" would work for sending the "0"th emoji. This would make the plugin useful even after Discord fixes the core issue.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
Done! The fix is shitty and emojis still show up as invalid in the input box but they send correctly https://github.com/Vendicated/AliucordPlugins/tree/main/FixEmotes

https://user-images.githubusercontent.com/45497981/146468136-001edb4c-c45b-4da1-a44c-8f3c8c6e4699.mp4
