### ISSUE TITLE
Online on Desktop

### ISSUE THREAD

**Issue by Juliaxe** [Aliucord/plugin-requests#316]
### Discord Account

Juliaxe#1058

### Plugin Description

A plug-in that shows you're online on a computer even though you're on mobile.

### Request Agreement

- [x] I did indeed check to make sure my plugin request is original!

**Comment by saintwithataint** [comment]
![image](https://user-images.githubusercontent.com/45678566/137443040-b18f1909-b5b5-4641-8655-ac133247bbe4.png)

**Comment by Juby210** [comment]
Most likely this will be detectable, so I will close this requests as this could result in a ban.
