### ISSUE TITLE
Discord toggler activity for mobile

### ISSUE THREAD

**Issue by Dhanush6122006** [Aliucord/plugin-requests#317]
### Discord Account

Dhanush#6250

### Plugin Description

It's op c mob players now add custom stuffs

### Go into more detail...

Like there is an extension that does this so ig u can check tat out https://chrome.google.com/webstore/detail/set-discord-activity/dlmmhgaeahcfkojednnfghfpinbinicj

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
1. That chrome extension looks dodgy af
2. Duplicate #83
