### ISSUE TITLE
Spoiler marking media

### ISSUE THREAD

**Issue by BlasterOverlord** [Aliucord/plugin-requests#32]
### Description
An option (more preferable) or command (less preferable) to spoiler mark any media sent.

### More info
On Android there's not a native way to spoiler media sent in the discord app. 
The only way to spoiler media on Android so far is to rename the file with "SPOILER_" at the beginning of its name. (Perhaps you can use this and automatically rename the file like that everytime we opt for spoilering a media)! Good luck!

---

- [x] I checked if this plugin wasn't already requested.

**Comment by vy-storm** [comment]
This has already been made iirc

**Comment by WinstonSepruko** [comment]
This is already included with [this plugin](https://github.com/Juby210/Aliucord-plugins/blob/builds/MoreSlashCommands.zip).

Please make sure you check through our plugin channel(s) in the [Support Discord](https://discord.gg/EsNDvBaHVU) to check which plugins exist, check through other issues here to see if it already has been requested/completed.
