### ISSUE TITLE
Auto2FA

### ISSUE THREAD

**Issue by pointydev** [Aliucord/plugin-requests#320]
### Plugin Description

Simple plugin to autofill login 2FA code if there's a 6 digit number on the clipboard.

### Go into more detail...

My password manager automatically puts my current TOTP on my clipboard after I autofill my login credentials, this would remove an extra hand movement, long hold and tap to paste it manually.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Reinified** [comment]
this is already a stock feature in discord

**Comment by Sepruko** [comment]
This stock feature works perfectly fine for me, without fail.

**Comment by Reinified** [comment]
close this when
