### ISSUE TITLE
First message

### ISSUE THREAD

**Issue by Penguin3939** [Aliucord/plugin-requests#326]
### Discord Account

_doggy#7879_

### Plugin Description

You put something like "/firstmessage" and Clyde shows the first message

### Go into more detail...

You put something like "/firstmessage @user or channel" and Clyde shows the first message link for that user or the channel your in right now , as I think it would be cool to use and to have fun with it

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
I will make this. (Will take some time though)

I'm not sure how I would get the first message of a *user* but I'll see what I can do.

**Comment by DiamondMiner88** [comment]
I've taken over this request (plugin-discussions)
