### ISSUE TITLE
Speak

### ISSUE THREAD

**Issue by Shawnical** [Aliucord/plugin-requests#330]
### Discord Account

Shawnic#6969

### Plugin Description

Sorry for requesting again ... This plugin will pronounce the words for you! Just hold the message and it will pronounce it and speak. Same as translate plugin but it will say it instead.

### Go into more detail...

I hope it will work with translate plugin so i can make it say stuff. Also sorry for requesting twice xd

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Shawnical** [comment]
Its shitty

**Comment by Reinified** [comment]
just go to your devices accessibility settings and turn on screen reader, every phone should have this

**Comment by rushiiMachine** [comment]
#258
