### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by Reinified** [Aliucord/plugin-requests#333]
### Discord Account

Soulz#0387

### Plugin Description

so, samsung being stupid, decided to remove their in-built calculator app (atleast for my phone) and instead add their crappy bloat to it.

so a plugin that adds a slash command calculator would be useful, somebody in the prd channel suggested it.

### Go into more detail...

it's probably pretty stupid but i'd rather not have to download a calculator app just for basic math.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
I'll make this

**Comment by Reinified** [comment]
oh that would be cool, but pretty sure complex calculations would be hard to make.

**Comment by saintwithataint** [comment]
complex calculations are handled by wolfram directly, you can simply say "integrate x^3" or whatever and it will handle it.

**Comment by scrazzz** [comment]
> @scrazzz make the plugin using the Wolfram API because then the plugin will be able to perform complex calculations as well.

https://github.com/scrazzz/AliucordPlugins#calc

I'll check the Wolfram API and see how it works and try to implement it in the next version.
