### ISSUE TITLE
EmbedAllTenorGifs

### ISSUE THREAD

**Issue by Reinified** [Aliucord/plugin-requests#335]
### Discord Account

Soulz#0387

### Plugin Description

life is pain, and trying to upload tenor gif links is a pain because half the time they dont embed, probably not possible idk but they should always embed the gif.

### Go into more detail...

![Screenshot_20211020-220047](https://user-images.githubusercontent.com/54984650/138198275-f9aed3c1-6b4b-4d5c-bc6d-24ae8df7692a.png)
tired of seeing tenor.com gifs never embed to discord.

dont bother explaining why it might not be possible if it isn't.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
they don't embed because the discord filter deems them nsfw
