### ISSUE TITLE
Link Shortner Command

### ISSUE THREAD

**Issue by hairyfred** [Aliucord/plugin-requests#34]
### Description
A slash command to shorten the link

### More info
Port of this https://github.com/doggybootsy/Link-Shortner

---

- [ x] I checked if this plugin wasn't already requested.

**Comment by ShiroBlank** [comment]
I'll start working on this.

**Comment by ShiroBlank** [comment]
Plugin finished, enjoy.

https://github.com/ShiroBlank/AliucordPlugins/raw/builds/UrlShortener.zip
