### ISSUE TITLE
Channel Cloner

### ISSUE THREAD

**Issue by Subtilizer28** [Aliucord/plugin-requests#341]
### Discord Account

Subtilizer#6619

### Plugin Description

Well this feature is available on pc and not on mobile. Using a bot for it is just pain. Is there any way to clone an channel with plugin? Since channels might have individual perms and might not be synced to the category, by cloning you can move all perms without setting it one by one. 

### Go into more detail...

Long hold on the channel you want to clone, an option of clone will appear. And after pressing the clone option.... Well it does its thing. It moves all of its perms and stuff. 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
finished <https://github.com/DiamondMiner88/aliucord-plugins#clonechannels>
