### ISSUE TITLE
Server Counter

### ISSUE THREAD

**Issue by Savvy7** [Aliucord/plugin-requests#344]
### Discord Account

senko pog#3885

### Plugin Description

Shows the number of servers you are in 

### Go into more detail...

Basically a port of ServerCounter(https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ServerCounter)  from BD 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
claiming this

**Comment by DiamondMiner88** [comment]
completed: <https://github.com/DiamondMiner88/aliucord-plugins#counters>
