### ISSUE TITLE
owoify-everything

### ISSUE THREAD

**Issue by Jacob1Tm** [Aliucord/plugin-requests#346]
### Plugin Description

Plugin that changes all text to something like in this plugin for powercord https://github.com/tobimori/owoify-everything

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by WitherredAway** [comment]
the [moreslashcommands](https://github.com/Juby210/Aliucord-plugins/raw/builds/MoreSlashCommands.zip) plugin already does this.

**Comment by TymanWasTaken** [comment]
> the [moreslashcommands](https://github.com/Juby210/Aliucord-plugins/raw/builds/MoreSlashCommands.zip) plugin already does this.

That adds a command to owoify a message, the request is to owoify literally everything

**Comment by Juby210** [comment]
Done, https://github.com/Juby210/Aliucord-plugins/raw/builds/OwoifyEverything.zip
