### ISSUE TITLE
Ghost Messager

### ISSUE THREAD

**Issue by guckyslush** [Aliucord/plugin-requests#347]
### Discord Account

Ken Mcken#0292

### Plugin Description

hewwo... 🥵👉👈 can one of youwu please make a plugin that lets me send a message that then automatically gets deleted? OwO 😁

### Go into more detail...

example:

/ghost <i>message</i>

<i>message</i> would be sent in chat then quickly deleted

and also maybe a customizable timer in milliseconds that defines how long the message stays in chat if its possible

/ghost "time=500" <i>message</i>

does the same thing but keeps it up for 500ms

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Reinified** [comment]
use [GhostMessage by Animal](https://github.com/ItzOnlyAnimal/AliuPlugins/raw/builds/GhostMessage.zip)
