### ISSUE TITLE
Pin/Priority DMs

### ISSUE THREAD

**Issue by vy-storm** [Aliucord/plugin-requests#35]
### Description
Adds an option to set DMs as either Pinned or Prioritized.

### More info
- Pinned go to the top of your DMs list regardless of last message date.
- Prioritized go above both regular and Pinned, while also ignoring Do not Disturb
- Both Pinned and Prioritized sort by last message data within their respective catagory.

---

- [x] I checked if this plugin wasn't already requested.

**Comment by MulverineX** [comment]
This should be an issue for improving better friends, a plugin that already exists that adds DM pinning. https://github.com/powercord-community/betterfriends

**Comment by WinstonSepruko** [comment]
Mulv, buddy, this is for Aliucord and not Powercord.

**Comment by MulverineX** [comment]
Oh my god I was wondering why you had perms. I'm sorry, I need sleep.

**Comment by fym35** [comment]
Would be cool if also supported pinning into the server list

**Comment by zt64** [comment]
Finished: https://github.com/zt64/aliucord-plugins/raw/builds/DMCategories.zip

**Comment by vy-storm** [comment]
> Finished: https://github.com/zt64/aliucord-plugins/raw/builds/DMCategories.zip

I can't figure out how to make it override do not disturb

**Comment by vy-storm** [comment]
I quite like that you can make as many as you want though, each can have it's own unique settings too since it's all user configurable

**Comment by zt64** [comment]
> > Finished: https://github.com/zt64/aliucord-plugins/raw/builds/DMCategories.zip
> 
> I can't figure out how to make it override do not disturb

What do you mean by "override do not disturb?"

**Comment by vy-storm** [comment]
I quite like that you can make as many as you want though, each can have it's own unique settings too since it's all user configurable

> > > Finished: https://github.com/zt64/aliucord-plugins/raw/builds/DMCategories.zip
> > 
> > 
> > I can't figure out how to make it override do not disturb
> 
> What do you mean by "override do not disturb?"

Do not disturb is a status you can set which prevents discord from making any sounds on desktop/mobile.  So DMs with the override would send a push/popup notification even when DND status is on

**Comment by vy-storm** [comment]
Basically, sometimes I want to hush the majority of discord, but not specific people like my closest friends/family.

**Comment by zt64** [comment]
Might be better as a seperate plugin then

**Comment by vy-storm** [comment]
> Might be better as a seperate plugin then

How so? I just want to be able to mark people for override

**Comment by Vendicated** [comment]
ignoring dnd is not possible unless you have discord open at which point you can just see the notification
