### ISSUE TITLE
Hidden Channel Peek

### ISSUE THREAD

**Issue by alsoknownasaka** [Aliucord/plugin-requests#354]
### Plugin Description

The Hidden Channel Peek feature would be able to look into usually hidden channels and allow the user to read messages from them

### Go into more detail...

It would let people see what's going on behind the scenes aswell as background work within the server

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Dungeonscats** [comment]
someone delete this issue. its not valid + there's a bunch of them.
