### ISSUE TITLE
Fix Missing/Extra @ In Replies

### ISSUE THREAD

**Issue by Kyza** [Aliucord/plugin-requests#36]
### Description
A plugin that fixes the `@` being missing or extra on replies that ping because Discord hasn't fixed it since before Aliucord existed.

#### Mobile Missing
![Screenshot_20210531-060708_Aliucord](https://user-images.githubusercontent.com/40003440/120178128-2488b300-c1d7-11eb-907c-5c86b2dd709a.png)
#### Desktop Missing
![Screenshot_20210531-061454_Chrome](https://user-images.githubusercontent.com/40003440/120178498-9103b200-c1d7-11eb-8f18-aa7e48b40b69.png)

#### Mobile Extra
![Screenshot_20210531-063203_Aliucord](https://user-images.githubusercontent.com/40003440/120180741-243de700-c1da-11eb-9971-09932aec6db9.png)
#### Desktop Extra
![Screenshot_20210531-063246_Chrome](https://user-images.githubusercontent.com/40003440/120180769-2dc74f00-c1da-11eb-9935-8b6c3ea4e453.png)

Bonus points if you add the missing attachment icon.

---

- [x] I checked if this plugin wasn't already requested.

**Comment by Juby210** [comment]
Discord already fixed that in update, so will be fixed with ac update later.

**Comment by Juby210** [comment]
Apparently discord's fix doesn't work.

**Comment by Juby210** [comment]
https://github.com/Juby210/Aliucord-plugins/raw/builds/ShowReplyMention.zip
