### ISSUE TITLE
Create a bot to send memes (with obvious cooldown)

### ISSUE THREAD

**Issue by ThatOneFBIAgent** [Aliucord/plugin-requests#360]
### Discord Account

FBI Agent#0420 (might change)

### Plugin Description

The plugin that i am requesting can use an API to gather images/memes, per say, ifunny or others, it can have a maximum of 20 images, to not spam too much, it will have a 10-30 minute cooldown, like chill bro, you can do it on your own lmao.
Name:
AutoMemer

### Go into more detail...

I would like it to be a button like in the send embeds plugin that will activate the bot, it will pop a prompt with one box, and that box is for it to send the maximum amount of memes (let's say you dont want 20 memes, but 10, you can use this box for it) 

On the settings it can be changed the preset of memes, it's cooldown (minimum of 10 MINUTES) and some others.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
this should not be a plugin
