### ISSUE TITLE
favoriting gif's on mobile uwu

### ISSUE THREAD

**Issue by LweoIsHere** [Aliucord/plugin-requests#362]
### Discord Account

AnotherLeo 💘#2756

### Plugin Description

i think like favoriting gif's on mobile would be pretty awesome, it's on PC so why not mobile as well? would be a pretty awesome thing to see especially when some people are on mobile alot instead of PC

hehe thanks for reading this!

### Request Agreement

- [x] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
Duplicate of #153
