### ISSUE TITLE
Change The look of Emojis 

### ISSUE THREAD

**Issue by askim1337** [Aliucord/plugin-requests#363]
### Discord Account

$ cosmin#4184

### Plugin Description

I think a plugin that change the look of emojis would be cool. Personally im bored of the basic emojis.It will be coup if somebkdy will make this plugin

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
Duplicate of #22

**Comment by rickdtc** [comment]
I was asking for the EXTRA rmojis in ctc,  not replacing the already existing ones <:husk:859796756111294474>
