### ISSUE TITLE
highestRoleAsBadge

### ISSUE THREAD

**Issue by evanswastaken** [Aliucord/plugin-requests#364]
### Discord Account

attribute!#0014

### Plugin Description

Have the highest role on the user show as a Badge. This is similar to the powercord plugin.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Duplicate of #95

**Comment by evanswastaken** [comment]
Oh I see. Sorry, I guess I missed it.
