### ISSUE TITLE
DoNotDisturb Exemptions

### ISSUE THREAD

**Issue by ItzDemonGrey** [Aliucord/plugin-requests#371]
### Discord Account

ItzDemonGrey#1133

### Plugin Description

Allow certian accounts to bypass your do not disturb setting.

### Go into more detail...

If you have do not disturb on, this will allow certian people's messages of your choosing to be let theough with a notification (based on your notif settings.) and it would keep all unadded exemptions under the normal DND mode

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
not possible

**Comment by ItzDemonGrey** [comment]
> not possible

damn. but wow I forgot how long ago I make that suggestion xD
