### ISSUE TITLE
Command/gesture to reload channel (to deal with buggy local client embedding)

### ISSUE THREAD

**Issue by Delphox** [Aliucord/plugin-requests#372]
### Plugin Description

The mobile client has a tendency of not embed images client-side when you post them despite them actually embeding server-side (different from actual embed fail on desktop, which fail server-side).

You can see it actually embed by triggering a channel reload, either by killing the app manually, or tabbing out of the app and waiting for a while. While the message itself remains intact.

A simple /reload command would suffice, but something like a pull up to reload would work too and be more elegant (but maybe harder to implement).

### Go into more detail...

https://user-images.githubusercontent.com/5883538/140613622-5affa1e9-5cbd-4129-ad8f-0615d011be70.mp4

Attached video shows the forced reload in action (jump to the end to see it reloading). This is essentially what I want the /reload or pull gesture to do.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Delphox** [comment]
Just realized this could be an addition to MoreSlashCommands by @Juby210 instead of a standalone plugin. Should I also open an issue on his repo, or would that too spamful?

**Comment by scrazzz** [comment]
> A simple /reload command would suffice, but something like a pull up to reload would work too and be more elegant (but maybe harder to implement).

There's restart button plugin by zt that adds this button near the logout button: https://github.com/zt64/aliucord-plugins/raw/builds/RestartButton.zip

**Comment by Delphox** [comment]
Yea but I don't wanna fully restart the app (I can already do that via the Recents UI from android. I just wanna reload the channel.

**Comment by rushiiMachine** [comment]
this is an occasional delay in discords unfurling service not a clientside bug
