### ISSUE TITLE
OpenProfileInReactions

### ISSUE THREAD

**Issue by Reinified** [Aliucord/plugin-requests#373]
### Discord Account

Soulz#0387 the coolest guy ever

### Plugin Description

when you open the reaction sheet on mobile, tapping the user would do nothing, so instead would it be possible to open their profile. You would tap on their avatar and/or username and have the ability to open up their profile, sometimes its just useful.

### Go into more detail...

TLDR: open profile in react menu

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
finished <https://github.com/DiamondMiner88/aliucord-plugins#openprofileinreactions>

**Comment by Reinified** [comment]
thanks daddy

**Comment by JonathanSwatz10** [comment]
Someone put the tag completed no one did that yet @zt

**Comment by ZT** [comment]
I did finish it, but before I committed I stored the code on a CD in Belize that was eaten by fugus. Will apply antifungal agent to the disc and see if that corrects it.

**Comment by ItzOnlyAnimal** [comment]
holy shit 2008 zt
he is now like 40

**Comment by ItzOnlyAnimal** [comment]
> I did finish it, but before I committed I stored the code on a CD in Belize that was eaten by fugus. Will apply antifungal agent to the disc and see if that corrects it.

That would be nice of you, it would be great to see this finished
