### ISSUE TITLE
Profile History

### ISSUE THREAD

**Issue by MeFinity** [Aliucord/plugin-requests#376]
### Discord Account

.Me.#9762

### Plugin Description

Stores PFP,Usernames and Tag for viewing and/or downloading later down the time

and oops my plugin is not original,well
part of it is

Username history request : [184](https://github.com/Aliucord/plugin-requests/issues/184) 

### Go into more detail...

i know that discord does not store pfp after they have been changed,maybe save it locally?

this serves no real purpose than to have another neat useless plugin

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
this wont work while discord is not running which ruins the point
downloading images can be done with ViewProfileImages
