### ISSUE TITLE
"Guild Member Avatars Kill Switch" re-implementation

### ISSUE THREAD

**Issue by dmack6464** [Aliucord/plugin-requests#378]
### Discord Account

D Mack#4481

### Plugin Description

![Screenshot_20211111-011702_Bluecord](https://user-images.githubusercontent.com/29574547/141130079-78db7ab5-7817-4246-94ef-6f6498a6466b.jpg)

### Go into more detail...

Pre-100 Discord versions included an experiment to disable per-guild avatars, I'd like this functionality back.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
completed: <https://github.com/DiamondMiner88/aliucord-plugins#nonitroavatars>
