### ISSUE TITLE
Remove "Wave to say hi!"

### ISSUE THREAD

**Issue by D3C0D3R5** [Aliucord/plugin-requests#379]
### Discord Account

JIREX#4205

### Plugin Description

Remove the annoying "wave to say hi!" popup when someone new joins a server you're in (and for some reason its still enabled by the server owner).

### Go into more detail...

Just remove the "Wave to say hi!" button, no need to remove the entire "(username) just joined the server". 

And maybe even a custom "just joined the server" text if possible? So it can just be "(username) joined" or whatever the user wants it to be?.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
exists, LayoutController
