### ISSUE TITLE
Message Link Embed

### ISSUE THREAD

**Issue by hairyfred** [Aliucord/plugin-requests#38]
### Description
Replace message links with an embed of the message content

### More info
https://github.com/Juby210/message-link-embed

---

- [ x] I checked if this plugin wasn't already requested.

**Comment by Vendicated** [comment]
I forgot to say I'm on it 

![Screenshot_20210608-015649](https://user-images.githubusercontent.com/45497981/121102063-f3bb0600-c7f4-11eb-8479-cf8e7d5186fa.jpg)

**Comment by Vendicated** [comment]
done!! https://github.com/Vendicated/AliucordPlugins/blob/builds/MessageLinkEmbeds.zip?raw=true
