### ISSUE TITLE
Copy button copies mentions, markdown, emojis, etc from messages

### ISSUE THREAD

**Issue by WitherredAway** [Aliucord/plugin-requests#380]
### Discord Account

Witherr🖤#5417

### Plugin Description

By default, the `copy message` button in message context menu copies the mention, emojis as text and does not copy the markdown. It'd be cool if the copy message copied all the above and other things that i can't remember right now, or an entirely separate button.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
i think this should be part of @Juby210's ViewRaw plugin

**Comment by WitherredAway** [comment]
True, i already made a suggestion there but no response as of yet. I'll close this issue if there is a response there.
