### ISSUE TITLE
Follow system theme

### ISSUE THREAD

**Issue by krystlwashere** [Aliucord/plugin-requests#386]
### Discord Account

krystl#7927

### Plugin Description

allows discord to follow system theme (dark theme/light theme)

### Go into more detail...

i think its pretty self-explanitory but ill explain it again just in case; if you turn on dark theme (or dark mode how its sometimes called) on your phone, discord would automatically switch to dark theme; turn it off and discord switches to light theme. this feature is only not available on android out of all the platforms discord is officially on, so until then it would be nice to have SOME sort of solution.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
[SystemTheme](https://discord.com/channels/811255666990907402/845784407846813696/1278182295953604790) is now available.
