### ISSUE TITLE
local channels

### ISSUE THREAD

**Issue by fym35** [Aliucord/plugin-requests#388]
### Discord Account

KongCz#7863

### Plugin Description

I think of a plugin that will allow you to create local channels on any server which only you will see and write to them . it could possibly sync like hiddenmessages (so other ppl could enter password or something to view the channel and write messages there, im not sure if this is possible via discords itself but if not it could be setup using simmilar way as pronoundb or badgedb) 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by fym35** [comment]
this may be too much complicated lmao

**Comment by rushiiMachine** [comment]
> so other ppl could enter password or something to view the channel and write messages there

kind of like a channel locked behind a role?
