### ISSUE TITLE
RoleFriends

### ISSUE THREAD

**Issue by abUwUser** [Aliucord/plugin-requests#390]
### Discord Account

A user#8169

### Plugin Description

I have some friends that I really like and that are special for me. So, It would be amazing to have a plugin where I can put them at the top of the DMs list as roles

### Go into more detail...

It will be like sections in the DMs list that you can color them, like this
```js
OwO cuties
Somebody#1234
AnotherSomebody#5678
AnotherAnotherSomebody#9012
```
```css
Very cool person
AnotherAnotherAnotherSomebody#3456


.Known .frens
.AnotherAnotherAnotherAnotherSomebody#7890
```
```bf
Direct Messages
```

Also when you DM somebody it should also apply the color of the section

This idea can go further, depending of the devs' imagination

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
Partially done https://github.com/zt64/aliucord-plugins/raw/builds/DMCategories.zip

**Comment by resucutie** [comment]
Due to Aliucord being slowly replaced by other mods that support the RN version, I'll close this issue

**Comment by tetralovania** [comment]
> Due to Aliucord being slowly replaced by other mods that support the RN version, I'll close this issue

Couldn't really find any useful information regarding this, could you tell me which discord mods support RN or point me to a resource where I can check it myself? ty!

**Comment by wingio** [comment]
> > Due to Aliucord being slowly replaced by other mods that support the RN version, I'll close this issue
> 
> Couldn't really find any useful information regarding this, could you tell me which discord mods support RN or point me to a resource where I can check it myself? ty!

https://github.com/vendetta-mod
