### ISSUE TITLE
Plugin that lets you use regex on the discord search feature.

### ISSUE THREAD

**Issue by WitherredAway** [Aliucord/plugin-requests#391]
### Discord Account

Witherr🖤#5417

### Plugin Description

I dont know if it's possible, but as a moderator for a pretty big server i think it would be awesome if there was an option (like from, mentions, etc) that lets you use regex on the search feature. Maybe also other options for searching from pc dekstop such as during, before, after and sorting from old and new.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Good addition to #72

**Comment by Vendicated** [comment]
not possible, search results are provided by the api so there's no way to add new options
