### ISSUE TITLE
Move channels

### ISSUE THREAD

**Issue by AhadEA** [Aliucord/plugin-requests#394]
### Discord Account

ੴ cobalt ριЖιs#6080

### Plugin Description

Move channels to up and down.

### Go into more detail...

A plugin for moving text channels to up or down with press and hold or with a move to up and down button that show when you hold the channel.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by fym35** [comment]
Duplicate of #384

**Comment by fym35** [comment]
Wait

**Comment by fym35** [comment]
It isnt because that one is LOCAL and this one isnt

**Comment by Juliaxe** [comment]
This is already a stock feature within Server Settings.

**Comment by Reinified** [comment]
stock discord mobile feature
close now now now
