### ISSUE TITLE
Material You theming 

### ISSUE THREAD

**Issue by vortck** [Aliucord/plugin-requests#396]
### Discord Account

esty#4449

### Plugin Description

With the rollout of Android 12 brought Material You, theming your phone using the colours of your wallpaper 

Would be really cool to have Aliucord take on your system colours the same way stock apps do 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
There's already themes for the Themer plugin that already implement this functionality

**Comment by Vendicated** [comment]
yeah themer plugin has this functionality but there's not many themes using it yet
