### ISSUE TITLE
Word Notifications

### ISSUE THREAD

**Issue by ItzOnlyAnimal** [Aliucord/plugin-requests#399]
### Discord Account

VEN HOW DO I GET FREE NITRO (nickname)

### Plugin Description

A plugin that notifies you when a word(s) is said in a server, similar to the ones on desktop client mods

### Go into more detail...

That is literally it there is no more detail <img src="https://cdn.discordapp.com/emojis/901591305203875910.png" width="24" height="24">

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Reinified** [comment]
similar to #179

**Comment by ItzOnlyAnimal** [comment]
die
it did not show me this when i searched

**Comment by Reinified** [comment]
well all i did was search the term "Notification"
get trolled

**Comment by ItzOnlyAnimal** [comment]
i literally searched that github sucks moment
