### ISSUE TITLE
LocallyRenameEmotes

### ISSUE THREAD

**Issue by Reinified** [Aliucord/plugin-requests#400]
### Discord Account

VEN MY BELOVED PLZS HOW ANIMATE AVTR FREE NITRO??! (Soulz#0387)

### Plugin Description

I think a plugin that would allow us to rename emotes to anything of our choice would be cool (maybe this could work with discord emotes too)

### Go into more detail...

Difficult to explain but

I would imagine holding down on the emoji and having an option to rename it in the context menu, it would open a little prompt asking you what you want to name it. After you renamed it you could type ``:customemotename:`` and then it would send the emoji of your choice. 

(eg rename ``:exploding_head:`` to ``:mindblown:``, type out ``:mindblown:`` and it would send the ``:exploding_head:`` emote.)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Masterjoona** [comment]
You can use [TextReplace](https://github.com/c10udburst-discord/aliucord-plugins/raw/builds/TextReplace.zip) for this
![Screenshot_20211118-215352](https://user-images.githubusercontent.com/69722179/142487310-7c11108b-74c2-45df-95a1-29158eda40ae.jpg)

**Comment by Reinified** [comment]
I forgor 💀

**Comment by Reinified** [comment]
oh also this was request 400 im so cool
