### ISSUE TITLE
A small dot/indicator to the right of channel names in the channel-list view if someone is typing in that channel

### ISSUE THREAD

**Issue by alcatrazblaze** [Aliucord/plugin-requests#402]
### Discord Account

Disco#3672

### Plugin Description

A plugin that would show a dot or any sort of symbol(hopefully a few options) that could indicate that a user/some users is/are typing in that channel. This is for the sidebar view/channel list view. 

Very crude mockup - 
![Screenshot_20211119-143421_1](https://user-images.githubusercontent.com/55349349/142596859-7e9991fc-ab78-464c-a7de-b70360122040.jpg)

I realise that this might mean that the channel name might have to be cut short by a few Pixels(in 0.9% cases only) , so I have another alternative

Possibility to have a different channel name color for active channels(channels having people typing in them). This second suggestion can be a plugin of its own or can be incorporated into the themer plugin, if possible 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
Duplicate https://github.com/Aliucord/plugin-requests/issues/46
