### ISSUE TITLE
Custom color for sender's message

### ISSUE THREAD

**Issue by alcatrazblaze** [Aliucord/plugin-requests#405]
### Discord Account

Disco#3672

### Plugin Description

Can be part of themer or highlightOwnMessages plugin.

Just a different color for your own messages.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by C10udburst** [comment]
Added to HighlightOwnMessages

https://github.com/c10udburst-discord/aliucord-plugins/raw/builds/HighlightOwnMessages.zip
