### ISSUE TITLE
Upload Images to external host

### ISSUE THREAD

**Issue by D3C0D3R5** [Aliucord/plugin-requests#406]
### Discord Account

JIREX#4205

### Plugin Description

Automatically uploads an image to a website and auto-copies the image link to your clipboard.

### Go into more detail...

It can upload it to a public site like https://imgur.com/upload, or you can choose who to send it to over discord (can be a friend of yours or your alt account. It would be chosen by discord user ID). It then would copy the link of that image to your clipboard and make it able to embed that image on a discord server that only allows embeds. Preferably, the plugin would be able to check if you are allowed to send images in the channel youre in by checking your user's permissions. If you cannot send images, it'll check if you can embed images. If you also cannot send embeds, the gallery button will either not show up, or be greyed out.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
I'll make this

**Comment by OmegaSunkey** [comment]
this is finished. the plugin name is uith and works like sharex.

**Comment by arkzok** [comment]
why is this issue still open?

**Comment by scrazzz** [comment]
> this is finished. the plugin name is uith and works like sharex.

I don't think I've published it "officially" because the code sucks and I got fed up because of many users wanting help configuring it.
