### ISSUE TITLE
Add Clear Role Permissions button

### ISSUE THREAD

**Issue by jue131** [Aliucord/plugin-requests#408]
### Discord Account

Usered#6888

### Plugin Description

My suggestion is to port a "clear role permissions" button in role settings from PC client.

### Go into more detail...

The button could clear all permissions of a role in a single action, instead of having to manually uncheck everything.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by lenk** [comment]
This is now available, it can be closed, visit #Plugins-List in the Aliucord server!

[https://github.com/lenk/aliucord-plugins](https://github.com/lenk/aliucord-plugins)
