### ISSUE TITLE
SERVER MESSAGE DELETION

### ISSUE THREAD

**Issue by Zerkm** [Aliucord/plugin-requests#414]
### Discord Account

Faze Mask#9777

### Plugin Description

I'd like to suggest a plugin where 
You can instantly delete all messages you've sent to a server
as easy as doing a command like(/del all)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by saintwithataint** [comment]
This is selfbotting, and WILL get you banned.
