### ISSUE TITLE
Save file as link

### ISSUE THREAD

**Issue by Z12aS0** [Aliucord/plugin-requests#418]
### Plugin Description

save storage by saving your files, downloaded from discord, as links, saved in a .txt file or whatever
also bypasses the nitro 8mb+ as your not the one who uploaded the file

### Go into more detail...

it should temporarely download files **(If not 8mb+)** and send them if the server does not give everyone(or atleast you), embed perms
we dont want to look like a clown and make an **epic embed fail**

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
what? whats the usecase for this
