### ISSUE TITLE
Plugin to add clickable mention in embeds

### ISSUE THREAD

**Issue by AKASGaming** [Aliucord/plugin-requests#419]
### Discord Account

AKASGamingYT#8615

### Plugin Description

A plugin that add the ability to tap mentions (Ex: Users, Voice Channels, etc)

### Go into more detail...

This isn't implemented already and never will be, says the people in the Discord Testers server

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
Completed: <https://github.com/DiamondMiner88/aliucord-plugins#clickablementions>
