### ISSUE TITLE
Status changer according to your time

### ISSUE THREAD

**Issue by Killerjet101** [Aliucord/plugin-requests#421]
### Discord Account

Killerjet101#7638

### Plugin Description

Have this plugin change your status to something you decide during certain times.

### Go into more detail...

This plugin can look at what time it is according to the clock of your phone. And look at what status you wanted at that time and change it to it. For example:
6:00-8:00: Set status to "Morning!"
8:00-3:00: Set status to "In school, dnd"
And so on.

You could also add where if your working or at school to set your status to "dnd" until after hours and go back to "online".
Of course, because it's using your phone's clock it will be able to adapt to daylight savings if you have that in your area.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
Not possible, also selfbotting.

just use zts status presets plugin and change manually
