### ISSUE TITLE
Emoji Fix

### ISSUE THREAD

**Issue by FrequencyX4** [Aliucord/plugin-requests#422]
### Discord Account

Luck#1574

### Plugin Description

a plugin to fix some emojis not parsing despite having access, the emoji not being locked, etc

### Go into more detail...

some emojis don't parse due to a discord bug that hasn't been fixed for months

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
duplicate of #311
