### ISSUE TITLE
owo Mode

### ISSUE THREAD

**Issue by AngelTRLX** [Aliucord/plugin-requests#424]
### Discord Account

@Igor The Chikito#9887 

### Plugin Description

A bottom to turn on a owo Mode that changes the R for W without having to go to Plug-in section to turn off in case of serious moments

### Go into more detail...

Just change the letters so it's like the owo Lenguaje

In options you will be able to modify how strong will it be

Change the J for G
Change the G for J
If detects ow it will modify to make owo like Howo
And more things

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
> Change the J for G
Change the G for J

You can achieve this by using TextReplace
https://github.com/c10udburst-discord/aliucord-plugins/raw/builds/TextReplace.zip
