### ISSUE TITLE
CompletelyHideMutedPings

### ISSUE THREAD

**Issue by ghost** [Aliucord/plugin-requests#427]
### Discord Account

`VastraKai#0001`

### Plugin Description

Can someone make a plugin to completely hide pings from muted channels/servers/DMs? 
Just visually of course.
Thanks in advance.
- kai

### Go into more detail...

No need

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
use every single notification mute option there is and it will work
