### ISSUE TITLE
Plugin suggestion

### ISSUE THREAD

**Issue by benekioo** [Aliucord/plugin-requests#430]
### Discord Account

benekio#6969

### Plugin Description

A plugin opposite to mutual servers, a option to see mutual friends in a server so you can see without checking every friend if they are in a server. 

/ optional idea, pick a server and see if any member is in the server you want to check mutuals

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by fym35** [comment]
Already exists : GuildProfie
