### ISSUE TITLE
Preview Discord Links

### ISSUE THREAD

**Issue by RhyMegu** [Aliucord/plugin-requests#431]
### Discord Account

Rhy#1752

### Plugin Description

A plugin which previews links (eg. https://discord.com/channels/serverid/channelid/messageid) to messages in discord just below the link.

### Go into more detail...

It should be preferably up to 100 or 200 characters, featuring the timestamp, sendertag, and it opens up the original message upon pressing it. The embed format may work, or the thread box would work too.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
Clearly didn't check it exists

**Comment by Vendicated** [comment]
https://github.com/Vendicated/AliucordPlugins/tree/main/MessageLinkEmbeds
