### ISSUE TITLE
Pin Dms

### ISSUE THREAD

**Issue by TheKuthra** [Aliucord/plugin-requests#432]
### Discord Account

TheKuthra#4774

### Plugin Description

Gives the user the ability to locally make dm groups and pin friends dms into those made groups(Ex: Close friends group, co workers group, etc)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Finished: https://github.com/zt64/aliucord-plugins/raw/builds/DMCategories.zip
