### ISSUE TITLE
Hidden reader

### ISSUE THREAD

**Issue by CH4INZ-dexd** [Aliucord/plugin-requests#434]
### Discord Account

♤𝙻𝚘𝚛𝚍-𝙻𝚎𝚟𝚒𝚌𝚞𝚜♤#8960

### Plugin Description

A plugin that allows you to read inside hidden channels instead of just being able to know they exist. For privacy reasons strictly.

You would not be able to type or interact but only view, 
*messages
*images and videos
*users who have access

### Go into more detail...

Another feature that i think would be useful would be a keyword search bar.

For example if you are in a situation where your name or pictures come up you can simply type in your tag and it will highlight all messages that include those keywords.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Not possible.

**Comment by CH4INZ-dexd** [comment]
> 

Damn

**Comment by hairyfred** [comment]
1. Huge breach of privacy, even if it was possible we would not condone such behaviour
2. Impossible

**Comment by fym35** [comment]
Its not possible because discord's api does only give the channel name , topic and last message send btw
