### ISSUE TITLE
Drawable/Resource browser

### ISSUE THREAD

**Issue by fym35** [Aliucord/plugin-requests#435]
### Plugin Description

A plugin to browse the app's resources/drawables and easily copy them

### Go into more detail...

This would be useful for some plugins like BetterChannelIcons , CustomBadges or even for theming 

bcuz it would be much better fo browse the resources inside the app itself instead of having to close it and open the decompiled discord jadx

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Reinified** [comment]
https://user-images.githubusercontent.com/54984650/145326120-e309a18e-f483-4305-bb0f-0bd3f1a50252.mp4 exists in themer just use that

**Comment by Vendicated** [comment]
you can even long press an entry and it will open a preview
