### ISSUE TITLE
Get bot invite link

### ISSUE THREAD

**Issue by ahihiyou20** [Aliucord/plugin-requests#438]
### Discord Account

@✼Ⓢⓝⓞⓦツ#3784

### Plugin Description

Get bot invite link without search for it on Google
_Ik we can just replace the bot id..._

### Go into more detail...

We should able to get the bot invite and edit permission

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
no way to properly know required permissions/scopes
more pain than its worth
