### ISSUE TITLE
Make the :tm: emote actually display the superscript tm instead of the barely visible emote

### ISSUE THREAD

**Issue by martmists-gh** [Aliucord/plugin-requests#439]
### Discord Account

Martmists#3740

### Plugin Description

See title

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
Already exists: https://github.com/DiamondMiner88/aliucord-plugins/raw/builds/BetterTm.zip

Please check the #plugins-list channel before requesting a plugin.
