### ISSUE TITLE
Swap Stage Discovery and Recent Mentions buttons

### ISSUE THREAD

**Issue by NatSepruko** [Aliucord/plugin-requests#44]
### Description
Moves the Stage Discovery button to Quick Switcher and Recent Mentions to the "hotbar."

### More info
Basically reverse "Mentions" and the Stage Channel icon.
![hotbar](https://cdn.discordapp.com/attachments/754154615297015880/851581644325781574/Screenshot_20210608-080018.png)
![quickswitcher](https://cdn.discordapp.com/attachments/754154615297015880/851581644557385728/Screenshot_20210608-080035.png)

---

- [x] I checked if this plugin wasn't already requested.

**Comment by GangsterFox** [comment]
At the current moment, you can disable that if you have discord experiments plugin by doing bucket 0 on stage discovery for users experiment.

**Comment by WinstonSepruko** [comment]
This however leaves the user with no way to access the Stage Discovery interface.

**Comment by NatSepruko** [comment]
Now a default feature as stage discovery as been shut down.
