### ISSUE TITLE
Normalise Usernames

### ISSUE THREAD

**Issue by RhyMegu** [Aliucord/plugin-requests#441]
### Plugin Description

A plugin which converts non-latin script unicode characters to what resembles them in latin script, specifically in nicknames, usernames and statuses. I know it's a massive project considering the sheer number of characters but it can be done over a period of time.

### Go into more detail...

A toggle can be added which can normalize message text too, with a patch which ignores normalization for certain usernames if the custom usernames plugin is toggled.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
I'll try to do this

**Comment by scrazzz** [comment]
I'm not making this, there's too much things to patch which I don't even know. Maybe someone else can do this.

**Comment by RhyMegu** [comment]
Plugin created which does the former
