### ISSUE TITLE
Add "Not request channel" to dev warning

### ISSUE THREAD

**Issue by OmegaSunkey** [Aliucord/plugin-requests#444]
### Discord Account

OmegaSunkey#9366

### Plugin Description

Add a "Also, this isnt a request channel, if you want to request a plugin, go to pins in #plugin-request-discussion and read" in the development warning in Aliucord.

### Go into more detail...

This is because people assumes that in a dev channel you can submit ideas, so this warning would be useful (assuming people can read)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
request it on normal aliucord repo, not in repo for external plugin requests
