### ISSUE TITLE
BetterMarkdown

### ISSUE THREAD

**Issue by WitherredAway** [Aliucord/plugin-requests#446]
### Discord Account

Witherr🖤#5417

### Plugin Description

Maybe a plugin that adds a menu next to the text box for inserting markdown symbols (with the cursor in the middle) like on github or reddit and I think discord pc.

And also markdown highlighting in the text box itself, like discord pc, such as:
![IMG_20211216_214155](https://user-images.githubusercontent.com/81734495/146407767-001ec65e-3fed-477b-a284-42d493cdf617.jpg)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by WitherredAway** [comment]
Turns out that this is similar to #254, but i will still keep it up since my suggestion also has the markdown menu

**Comment by Vendicated** [comment]
Plugin exists now, so you should bring this up in the repo of the plugin
