### ISSUE TITLE
Platform Indicators

### ISSUE THREAD

**Issue by TYTheBeast** [Aliucord/plugin-requests#448]
### Discord Account

xNefas\#0727

### Plugin Description

A port of the well-known [Platform Indicators](https://betterdiscord.app/plugin/PlatformIndicators) plugin by Strencher

### Go into more detail...

As the original plugin does, it'd be handy to be able to see whether someone is on desktop, mobile, or web, or a combination of those platforms.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
Exists

**Comment by Mythical-Forest-Collective** [comment]
While this is true, it doesn't intergrate with Themer well and it's been a long while so doubt that'll get an update

**Comment by peter1599** [comment]
It will get updates. I also fixed some Themer bugs. The only Themer bug now is thtat the own avatar had a status ring in the settings page.

**Comment by Mythical-Forest-Collective** [comment]
Ah okay then, good to know 👍🏼
