### ISSUE TITLE
Personal Pins

### ISSUE THREAD

**Issue by xAwice** [Aliucord/plugin-requests#449]
### Plugin Description

Ability to pin a message only for yourself and have it saved in a separate pinned section thats based on the channel/dm

### Go into more detail...

Once you hold a message the menu will pop up and there will be an option to pin the message only for yourself once youve pinned the message it will put it in a menu similar to the current pins but it would only show your personal pins if possible without the 50max pins limit

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Favorite messages plugin by wing does this in a similar way

**Comment by xAwice** [comment]
Yea but its all in a single menu and its hard to find a message youre looking for because(if you have a lot of them saved) theres no way to filter per user or channel but if it was added that would be cool

**Comment by wingio** [comment]
actually there is, in the search field if you begin your query with @ it will filter by author, # by channel, and * by server

**Comment by xAwice** [comment]
Ah i didnt know would it be possible to also make it if you hold on a channel/server/dm it opens it with the filter already aplied because some people have fonts int their names

**Comment by PeterKW** [comment]
Sorry for disturbing, but where is the favourite messages plugin? Edit: https://discord.com/channels/811255666990907402/845784407846813696/878070010470334527
