### ISSUE TITLE
Export entire chats/Dms

### ISSUE THREAD

**Issue by DeltaHaust** [Aliucord/plugin-requests#450]
### Plugin Description

A discord chats/dms exporter similar to https://github.com/Tyrrrz/DiscordChatExporter

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
1. Self bot
2. The potential Rate limit
3. Your phone is going to melt

**Comment by DiamondMiner88** [comment]
> A discord chats/dms exporter similar to Tyrrrz/DiscordChatExporter

You literally found the solution to your own request
