### ISSUE TITLE
Login As Bot

### ISSUE THREAD

**Issue by Minacat1** [Aliucord/plugin-requests#451]
### Discord Account

SuKanzoo#8931

### Plugin Description

It controls the bot and get invite links :)

### Go into more detail...

it also does create edit ban kick and delete members and channel/messages

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by TymanWasTaken** [comment]
It would probably be less effort to create an entirely new app for bot accounts
You can't just make the discord app use a bot account

**Comment by hairyfred** [comment]
> It would probably be less effort to create an entirely new app for bot accounts You can't just make the discord app use a bot account

It its very complicated to modify discord to allow bots to sign in, the amount of stuff you need to spoof etc, hense why only 1 PC client has implemented it (its now abandoned due to the effort to maintain it), on mobile it would be even harder.
