### ISSUE TITLE
OpenSteamLinksInApp

### ISSUE THREAD

**Issue by Minacat1** [Aliucord/plugin-requests#456]
### Discord Account

SuKanzoo#8931

### Plugin Description

I couldn't find this plugin for aliucord

### Go into more detail...

it should open steam on discord with browser

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
You can already do this by setting steam to open up steam links

Also fill out plugin description correctly
