### ISSUE TITLE
UserLookup

### ISSUE THREAD

**Issue by minacat2222** [Aliucord/plugin-requests#457]
### Discord Account

ultriax#0009

### Plugin Description

It looks up userinfo and whois and the time date and clock

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
What does that even mean? What do you mean by "userinfo and whois and the time date and clock"? Isn't it just [UserDetails plugin](https://github.com/Juby210/Aliucord-plugins#userdetails)?

**Comment by minacat2222** [comment]
Oh

**Comment by DiamondMiner88** [comment]
Please don't make a request ever again
