### ISSUE TITLE
[Plugin Request] ThreadFix

### ISSUE THREAD

**Issue by Muatex** [Aliucord/plugin-requests#459]
### Discord Account

Mua2x#0002 

### Plugin Description

I think that making a plugin that fixes threads permissions on mobile would be cool. Maybe so I can talk in them.

### Go into more detail...

Channels with their main channel with send messages off for everyone but send messages in threads for everyone is on it doesnt let you send a message on mobile 😭😭 its been like this for ages someone make a plugin that fixes this 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
Can't reproduce. I think discord fixed that itself.
