### ISSUE TITLE
Channel Typing Indicators

### ISSUE THREAD

**Issue by Wind0S** [Aliucord/plugin-requests#46]
### Description
Animated indicator that appears when users are typing in other channels that aren't currently selected, similar to this plugin for Desktop: https://github.com/powercord-community/channel-typing
### More info
Due to the layout of Discord mobile, this is probably only possible to be seen when doing the swipe-right gesture to reveal the channels in a server. Would be interesting if when it detects typing, it briefly flashes the channel bar or something if you're not looking at the channels, and also in a way that's not too annoying if the server is very active. One idea: https://media.discordapp.net/attachments/839306462244372480/851752174865350716/typing_flash.gif

---

- [x] I checked if this plugin wasn't already requested.

**Comment by tuleo1** [comment]
okay so basically I have a suggestion, the same thing but in dms for example when someone is typing in ur dms it would show something like this ![PicsArt_07-01-07.20.00.jpg](https://user-images.githubusercontent.com/64293951/124057554-e92f0d80-da3c-11eb-8585-d1c6acea9940.jpg) it would be pretty cool ngl

**Comment by Litleck** [comment]
Working on channel typing indicators, maybe I'll include functionality for DMs as well

**Comment by zt64** [comment]
So it's been months and I've put a lot of work on this, and no matter what I do discord just ends up completely unusable. I'm gonna drop it, maybe someone else can try. Sorry.

**Comment by DiamondMiner88** [comment]
finished <https://github.com/DiamondMiner88/aliucord-plugins#typingindicators>
