### ISSUE TITLE
Exact Timestamp for mesages

### ISSUE THREAD

**Issue by ICoolBuddyBruh** [Aliucord/plugin-requests#462]
### Discord Account

ICoolBuddy#3353

### Plugin Description

A really helpful plugin is one that makes all Discord messages show the exact time and date.

### Go into more detail...

for example:
hh:mm:ss ; dd/mm/yy
10:33:43 ; 12/09/2021

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
Custom Timestamps, literally one of the first Aliucord plugins
https://github.com/Juby210/Aliucord-plugins/blob/builds/CustomTimestamps.zip
