### ISSUE TITLE
Show view message

### ISSUE THREAD

**Issue by Tyler0201** [Aliucord/plugin-requests#467]
### Discord Account

Tyler01#4155

### Plugin Description

[This plugin could work only in DMs].

This plugin will let us see if our message have been seen.

### Go into more detail...

For example in Instagram , when the guy who is speaking to you read the message you sent , it says "seen" or "read" or "view". I'd like if you guys can do this on discord. When i DM someone and he opens the dm and doesnt answer i'd like to see if the guy i speak to , read the message or no

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
This is not possible to do

**Comment by hairyfred** [comment]
Not Possible
