### ISSUE TITLE
Activity status

### ISSUE THREAD

**Issue by DariSerg** [Aliucord/plugin-requests#469]
### Discord Account

DariSerg#3745

### Plugin Description

A plugin that could enable activity status on Android, just like desktop.

### Go into more detail...

As I said, kinda like desktop's activity status. You can set it so you are playing a certain game, listening to music on a certain application and streaming. It would be pretty cool

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
Duplicate of #83 #211 and #317

Please don't lie that you checked to make sure your plugin request is original.

**Comment by DariSerg** [comment]
Sorry, didn't check properly
