### ISSUE TITLE
Show bot prefix

### ISSUE THREAD

**Issue by DariSerg** [Aliucord/plugin-requests#470]
### Discord Account

DariSerg#3745

### Plugin Description

Shows the bot prefix before or next to the bots nickname or username

### Go into more detail...

Examples:
(r!) Robotop
(Pls) dank memer
(r!) Rythm
Or
Dank memer (pls)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
This is basically impossible.

Prefixes of bots can be set and changed by the server owner at anytime to anything.

**Comment by hairyfred** [comment]
Nightmare
Id agree its basically imppossible

**Comment by Vendicated** [comment]
The plugin could analyze what messages bots reply to to determine their prefix(es) overtime
