### ISSUE TITLE
rename attachments before sending them like on pc

### ISSUE THREAD

**Issue by quiet69** [Aliucord/plugin-requests#472]
### Discord Account

quiet#0069

### Plugin Description

A plugin which lets us rename or randomise name of attachment of pictures and videos before uploading

### Go into more detail...

That's it

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
Duplicate of #327

Please don't lie that you checked to make sure that your plugin request is original.

**Comment by quiet69** [comment]
I apologise... I didn't scroll too far...

**Comment by scrazzz** [comment]
![guh](https://user-images.githubusercontent.com/70033559/147073164-ed59b079-a18f-49d0-bc73-aea24a370c25.jpg)
