### ISSUE TITLE
Hug/Kiss/etc commands

### ISSUE THREAD

**Issue by OGPandaGod** [Aliucord/plugin-requests#475]
### Discord Account

Panda God#0666

### Plugin Description

I think it would be cool if we could have affection commands that don't require a bot to use, I feel like it would be really fun to have

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by flleeppyy** [comment]
How would you envision it works?

**Comment by scrazzz** [comment]
I'll make this

**Comment by scrazzz** [comment]
https://github.com/scrazzz/AliucordPlugins/blob/builds/Emotions.zip
