### ISSUE TITLE
Read all message button

### ISSUE THREAD

**Issue by ahihiyou20** [Aliucord/plugin-requests#477]
### Discord Account

@Ogiwara Sayu#3784 

### Plugin Description

Add a button. If you press it then it will read all message for you (_or just add slash command_)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
1. Duplicate of #55 and many others
2. it needs to be implemented correctly to not be selfbot behavior
