### ISSUE TITLE
Tap a username to copy it

### ISSUE THREAD

**Issue by oddmario** [Aliucord/plugin-requests#478]
### Plugin Description

Basically a plugin that copies someone's username along with their tag by tapping it on their profile. I think this is already a thing on the native iOS Discord app but it was never pushed to the native Android one

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by lenk** [comment]
This is now available, it can now be closed, visit #Plugins-List in the Aliucord server!

[https://github.com/lenk/aliucord-plugins](Aliucord-Plugins)

**Comment by oddmario** [comment]
> be

thank you! ❤️
