### ISSUE TITLE
pronouns

### ISSUE THREAD

**Issue by sexymelkor** [Aliucord/plugin-requests#481]
### Plugin Description

similar to the existing pronoun display plugin but instead of using pronoundb the plugin would let you set people's pronouns individually inside aliucord so you can change them ad hoc and people don't have to use the database website

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
Request this as a feature on the repo of the pronoundb plugin
