### ISSUE TITLE
Colored text based on users highest role

### ISSUE THREAD

**Issue by AKASGaming** [Aliucord/plugin-requests#483]
### Discord Account

AKASGamingYT#8615

### Plugin Description

A plugin that colors any text sent from a user based on their highest role in that server

(Literally the colored text option from BetterDiscord)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
exists

**Comment by hairyfred** [comment]
https://github.com/zt64/aliucord-plugins
