### ISSUE TITLE
View Server as User

### ISSUE THREAD

**Issue by IndigoSamurott** [Aliucord/plugin-requests#485]
### Plugin Description

Effectively an upgrade to the 'View Server as Role' plugin - being able to select an option in a user's profile sheet to view the server with the permissions of their roles, but also channels which grant them specific permissions as a member. I'm not sure how easy this would be to implement, though. 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
request it in the repo of the plugin
