### ISSUE TITLE
Status presets 

### ISSUE THREAD

**Issue by CH4INZ-dexd** [Aliucord/plugin-requests#486]
### Discord Account

♤𝙻𝚘𝚛𝚍-𝙻𝚎𝚟𝚒𝚌𝚞𝚜♤#8960

### Plugin Description

The plugin lets you save statuses for easy switching.

### Go into more detail...

It would be a slider with user saved statuses, for example you could type "sleeping rn dont text" and save it and then put a new status later then go back to the slider and select it.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
exists
