### ISSUE TITLE
Delay Reaction to Avoid Rate Limit

### ISSUE THREAD

**Issue by IndigoSamurott** [Aliucord/plugin-requests#489]
### Plugin Description

When the user interacts with reactions (adding or removing them) in quick succession and has this plugin installed, the client displays the change immediately but queues the action and delays the time until the changes are sent to Discord to avoid being rate limited. Alternatively, after a reaction is rate limited, the client doesn't display it being undone and instead queues and reattempts it after a short delay.

### Go into more detail...

This could also be used when adding and removing roles from a user. 

*As TextReact also automatically delays its reactions, I don't think this would be considered self-bot-like behaviour.*

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
or maybe just get some patience? <:dogsmirkreverse:898881619660783686>

**Comment by IndigoSamurott** [comment]
True, it doesn't matter massively but I think it'd be nice for convenience' sake

**Comment by rushiiMachine** [comment]
ReactionQueue
