### ISSUE TITLE
Emote downloader

### ISSUE THREAD

**Issue by Sebianoti** [Aliucord/plugin-requests#490]
### Discord Account

Sebianoti#0007

### Plugin Description

Don't you just hate it when you see a cool emote in chat but the server it was posted from is private? This plugin would allow you to download any emote from any server someone posted in chat, so you could upload it to your server.

### Go into more detail...

Ideally a download button below join server in the emote context menu, or by pressing and holding an emote in the chat for a few seconds.
![Screenshot_20220101-201801](https://user-images.githubusercontent.com/96957054/147859403-847f13ef-7228-4cf7-91d9-0b282893ecc6.png)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
https://discord.com/channels/811255666990907402/811275162715553823/846165924708614194
EmojiUtility
#3 #40 Duplicate
