### ISSUE TITLE
A plugin to play MP3s in Discord as on PC

### ISSUE THREAD

**Issue by LexouilleTM** [Aliucord/plugin-requests#494]
### Discord Account

Léxouille™#2911

### Plugin Description

To play an MP3 on mobile, it must be downloaded. It would be convenient to be able to read them directly as on pc from Discord.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
#105 #143 #319 Duplicate 
Please check your plugin request is original
