### ISSUE TITLE
Makesweet Maker Command

### ISSUE THREAD

**Issue by hairyfred** [Aliucord/plugin-requests#495]
### Discord Account

fred#9876

### Plugin Description

https://api.makesweet.com/ Makesweet has an api that could be potentially utilized by a plugin

### Go into more detail...

Command to make Nitro How do I get Free Ven on demand

/makesweet heart-locket image=https://cdn.discordapp.com/emojis/859796756111294474.png?size=128 text=ven
*making a easy to use command will probs be the difficulty

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
I'll take this

**Comment by scrazzz** [comment]
I have a working copy of this plugin, but I don't know how I'll make this plugin without exposing my API key. Maybe someone else can take up this request.

**Comment by Mythical-Forest-Collective** [comment]
You could just require a user to use their input key?

**Comment by scrazzz** [comment]
> You could just require a user to use their input key?

No, the makesweet developer would get more than 40+ messages asking for a private key and that would be sus init.

---

Also, I've figure out a way to make this plugin work without exposing my API key. But I'll still add an option in settings to use your own API key if you do have it.

**Comment by scrazzz** [comment]
https://github.com/scrazzz/AliucordPlugins/raw/builds/Makesweet.zip

**Comment by hairyfred** [comment]
We cant expect God to do all the work
