### ISSUE TITLE
PlatformEmulator

### ISSUE THREAD

**Issue by BdAddons** [Aliucord/plugin-requests#498]
### Discord Account

Birdyy#0001

### Plugin Description

It will change and spoof the emulator/user agent of a device.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
Would break push notifications

**Comment by BdAddons** [comment]
Ok?

**Comment by hairyfred** [comment]
#316  I did indeed check to make sure my plugin request is original!
