### ISSUE TITLE
Auto Select Server

### ISSUE THREAD

**Issue by BdAddons** [Aliucord/plugin-requests#499]
### Discord Account

Birdyy#0001

### Plugin Description

This Will When Discord starts up, this plugin will automatically make the server that you're speaking in the currently selected one.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
Can you go into detail with what you mean by "Auto Selects Server"

**Comment by BdAddons** [comment]
https://github.com/TonyRaccoon/betterdiscord-plugins/blob/master/auto-select-server.plugin.js

**Comment by BdAddons** [comment]
This Will When Discord starts up, this plugin will automatically make the server that you're speaking in the currently selected one.

**Comment by hairyfred** [comment]
Great, now fill that into your original post with the example + explanation

**Comment by BdAddons** [comment]
Hre

**Comment by hairyfred** [comment]
> Here

Please learn how to edit your original issue, add the new info to the "Go into more detail..." section

**Comment by hairyfred** [comment]
Wait nevermind you have, my bad

**Comment by BdAddons** [comment]
Ok

**Comment by ItzOnlyAnimal** [comment]
More or less done by https://github.com/ItzOnlyAnimal/AliuPlugins/raw/builds/StartupChannel.zip: give it a channel id and your discord will from then on open to that channel

Will add something to save last selected channel later

**Comment by hairyfred** [comment]
> More or less done by https://github.com/ItzOnlyAnimal/AliuPlugins/raw/builds/StartupChannel.zip: give it a channel id and your discord will from then on open to that channel
> 
> Will add something to save last selected channel later

Probs best to add a issue on his repo as a feature request to his existing plugin
