### ISSUE TITLE
Plugin Checker

### ISSUE THREAD

**Issue by Hadock-is-ok** [Aliucord/plugin-requests#504]
### Discord Account

dank Had0cK#6081 don't ban me please

### Plugin Description

A plugin that checks all of your currently installed plugins for broken ones.

### Go into more detail...

It searches through all currently installed plugins to see which ones cannot be used (aka are broken) and disable them.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
You can't 
<img src="https://cdn.discordapp.com/emojis/899775965687857193.png?size=32"/>
