### ISSUE TITLE
Mark Stickers as favorites

### ISSUE THREAD

**Issue by kaname-png** [Aliucord/plugin-requests#505]
### Discord Account

kaname-png#6666

### Plugin Description

A plugin in which you can mark Stickers as favorites, just as you can officially with emojis.

It is very annoying to always have to search for our favorite stickers since discord only shows a list of the last used stickers, but not our favorite stickers.

### Go into more detail...

I think it would be something very useful and good, since it is also something that Discord does not officially have in any of its clients, I do not understand why, I hope they can put a plugin like that.

### Request Agreement

- [x] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
I will make

**Comment by kaname-png** [comment]
I don't think he ever will.
