### ISSUE TITLE
Make non nitro emotes show up as theyre typed out just like normal default emojis work

### ISSUE THREAD

**Issue by ermcy** [Aliucord/plugin-requests#506]
### Discord Account

!                     WankyPanky#1491

### Plugin Description

basically make typing out emotes name possible for non nitro users but make it so after selecting the emote when something like the image below shows up the emote is automatically converted to the embed link 

### Go into more detail...

I think this plugin could help if you don't want to favourite every emote you like. On how this could work I think the app can make a cache of all emotes with names and when they're typed out they'll show up as normal emotes do but in a case where the emote would be converted to an embed with the help of `NitroSpoof` plugin it converts the text into the embed link for the emote.
![Screenshot_20220106-123603](https://user-images.githubusercontent.com/90040892/148342874-e0d20be3-35af-4e8c-8d02-e467b4583b88.jpg)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
I think there is an experiment that can be enabled and it will do this if enabled. Let me check.

**Comment by OmegaSunkey** [comment]
2021_03_nitro_emoji_autocomplete_upsell_android — Emoji Autocomplete Upsell experiment. So this means no need for a plugin
