### ISSUE TITLE
Plugin that repairs about mes in dms

### ISSUE THREAD

**Issue by ImHeXa** [Aliucord/plugin-requests#507]
### Discord Account

hexa#0069

### Plugin Description

when im in dms and i click on someone's profile, i can't see his about me. another situation is in servers, where i can see any about me without any bugs. funniest thing is i can see them on non-modded discord

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
bug with this discord version, will be fixed once we update

**Comment by ImHeXa** [comment]
but the bug existed even back in 108.2

**Comment by hairyfred** [comment]
> but this bug existed even back in 108.2

Please test with the latest Discord (110.2), high chance its fixed by now

**Comment by Vendicated** [comment]
as I said it is fixed
