### ISSUE TITLE
Translate Message with "See Original"

### ISSUE THREAD

**Issue by KazKaz90** [Aliucord/plugin-requests#508]
### Discord Account

☆愛《𝕂𝔸ℤ》憎☆#9327

### Plugin Description

A plugin that can translate messages while also viewing the original message, as stated in the title.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
translate plugin exists

**Comment by DiamondMiner88** [comment]
Reference issue: https://github.com/TymanWasTaken/aliucord-plugins/issues/9
