### ISSUE TITLE
Spell Check

### ISSUE THREAD

**Issue by BdAddons** [Aliucord/plugin-requests#512]
### Discord Account

..=..#0001

### Plugin Description

Adds a Spell Check to all Message Inputs

### Go into more detail...

It will fix the messages. :)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
get gboard

**Comment by BdAddons** [comment]
I have kindle sorry

**Comment by OmegaSunkey** [comment]
how are you using aliucord on a device that is made specifically for reading

**Comment by BdAddons** [comment]
I downloaded on the browser

**Comment by ItzOnlyAnimal** [comment]
????

**Comment by hairyfred** [comment]
> I downloaded on the browser
If you could download an external apk on a browser
Just install a apk for a keyboard? not hard
