### ISSUE TITLE
Colored emojies

### ISSUE THREAD

**Issue by BuyMyTofu** [Aliucord/plugin-requests#514]
### Discord Account

toshy._.#5295

### Plugin Description

Colors the greyed emjies in the emojie menu (idk how to spell emojie)

### Go into more detail...

If u dont have nitro the emojies are greyed out but this plugin has it colored

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
1.- nitrospoof does that
2.- its emoji
