### ISSUE TITLE
Un-spoiler replies

### ISSUE THREAD

**Issue by IndigoSamurott** [Aliucord/plugin-requests#515]
### Plugin Description

If the message being replied to was un-spoilered by the user, then the reply text also displays it as un-spoilered rather than as a spoilered black bar.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
Not sure if this is what you mean but AutoShowSpoilers does this 
https://github.com/ItzOnlyAnimal/AliuPlugins/blob/builds/AutoShowSpoilers.zip
![gay](https://user-images.githubusercontent.com/24845294/149864569-2b8f20c6-4c45-41c3-8621-99aba33fec8f.png)
