### ISSUE TITLE
Nitrospoof: Add a button to copy URL of an emote

### ISSUE THREAD

**Issue by m-y-x-i** [Aliucord/plugin-requests#519]
### Discord Account

myxi#1818

### Plugin Description

Bluecord's nitro spoof feature has a cool thing.

When you tap on an emote, it shows three buttons. One of them was added by Bluecord, "Copy emote."

It copies the URL of the emote to my clipboard for later use.
I would like to have an option like that for [NitroSpoof by X1nto.](https://github.com/X1nto/AliucordPlugins/tree/master/plugins%2FNitroSpoof) 

![Screenshot_2022-01-10-19-52-48-62_5a415ff834f6bc153619606941c55eb5](https://user-images.githubusercontent.com/86738916/148781876-81a78b12-7a3c-4bfe-a6a6-08ea85b137d7.jpg)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by neko-astolfo-uwu** [comment]
EmojiUtility basically.
https://discord.com/channels/811255666990907402/811275162715553823/846165924708614194
"I did indeed check to make sure my plugin request is original!!!"

**Comment by m-y-x-i** [comment]
> EmojiUtility basically.
> https://discord.com/channels/811255666990907402/811275162715553823/846165924708614194
> "I did indeed check to make sure my plugin request is original!!!"

The copied link doesn't include `size` query with the integer I specified in the settings of `NitroSpoof` plugin.

**Comment by neko-astolfo-uwu** [comment]
Then add it yourself, either way, should open issue on the EmojiUtility repo and not here. Also, NitroSpoof is unmaintained.

**Comment by m-y-x-i** [comment]
> Then add it yourself, either way, should open issue on the EmojiUtility repo and not here. Also, NitroSpoof is unmaintained.

Okay, my bad I guess.
