### ISSUE TITLE
tips for Mobile 

### ISSUE THREAD

**Issue by harrynotfound** [Aliucord/plugin-requests#522]
### Discord Account

mr.harry#8366

### Plugin Description

how about a plugin that rolls discord like it does in the pc verson and also it gives the tips 

### Go into more detail...

Tips like do you know the mascot etc and more , and my last request was just stupid because I didn't had plugin downloder lmao

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
Not possible. Plugins load after splash screen

**Comment by OmegaSunkey** [comment]
you will modify splash screen
