### ISSUE TITLE
Mark Emojis As Favorites

### ISSUE THREAD

**Issue by BdAddons** [Aliucord/plugin-requests#525]
### Discord Account

angry birds#7719

### Plugin Description

It will mark emojis as favorites into the list

### Go into more detail...

it will mark emojis and list it on favorites. 😀

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
pls banne @BdAddons

**Comment by BdAddons** [comment]
Bruh

**Comment by OmegaSunkey** [comment]
your banneEnviado desde mi Galaxy
-------- Mensaje original --------De: BdAddons ***@***.***> Fecha: 12/1/22  17:48  (GMT-05:00) A: Aliucord/plugin-requests ***@***.***> CC: OmegaSunkey ***@***.***>, Comment ***@***.***> Asunto: Re: [Aliucord/plugin-requests] Mark Emojis As Favorites (Issue #525) 
Bruh

**Comment by BdAddons** [comment]
Tf!?!?

**Comment by hairyfred** [comment]
Its built into discord?
Unless I'm missing somthing

**Comment by OmegaSunkey** [comment]
tried replying with mail
