### ISSUE TITLE
Get notifications when people say your name

### ISSUE THREAD

**Issue by xStormyy** [Aliucord/plugin-requests#526]
### Discord Account

I think it's pretty obvious who it is really.

### Plugin Description

Pings you everytime your name (or a certain word of choice) is said in a server.

### Go into more detail...

If a person for example says your name (without pinging you), you should get a notification. Or if you want to advance it you could also make the user have the ability to use custom words!

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
Not possible, use something like a highlight bot

**Comment by lenk** [comment]
https://github.com/wingio/plugins/raw/builds/KeywordAlerts.zip @DiamondMiner88 a thing

**Comment by DiamondMiner88** [comment]
won't work while not in-app smh
anyway @ven close

**Comment by ven** [comment]
hi

**Comment by mantikafasi** [comment]
Hi @ven

**Comment by DiamondMiner88** [comment]
:skull:
