### ISSUE TITLE
country selection on profiles as timezones

### ISSUE THREAD

**Issue by bruhveteran** [Aliucord/plugin-requests#535]
### Discord Account

monke#1091

### Plugin Description

locally add countrys to someones profile basically like timezones but for regions/countrys #ti

### Go into more detail...

locally add countrys to someones profile basically like timezones but for regions/countrys

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
Use discord notes, cause they also work on stock app and sync to every platform ‼️

**Comment by hairyfred** [comment]
I agree with Animal here
