### ISSUE TITLE
Prevent the screen turning off when playing a video

### ISSUE THREAD

**Issue by FBIAgent05** [Aliucord/plugin-requests#536]
### Plugin Description

Discord turns the screen off automatically even if you play a video, unless you touch the screen, so a plugin that prevents it would be cool.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
I think this is a device issue, go to your device settings and change the auto screen off setting to something like 5 minutes.

**Comment by FBIAgent05** [comment]
> I think this is a device issue, go to your device settings and change the auto screen off setting to something like 5 minutes.

why can youtube itself disregard this, even if there is a limit on auto turn off screen in the settings. It has to be in the app.

**Comment by OmegaSunkey** [comment]
> I think this is a device issue, go to your device settings and change the auto screen off setting to something like 5 minutes.

Every social media app or instant messaging app makes the device focus when watching a video. Not device issue just discord lazy to insert focus. <:trolley:916000825325780992>

**Comment by zt64** [comment]
> > I think this is a device issue, go to your device settings and change the auto screen off setting to something like 5 minutes.
> 
> Every social media app or instant messaging app makes the device focus when watching a video. Not device issue just discord lazy to insert focus. <:trolley:916000825325780992>

I can add this to better media viewer

**Comment by hairyfred** [comment]
Recreate this issue on @zt64 repo for a request for better image viewer
