### ISSUE TITLE
Remove Telemetry

### ISSUE THREAD

**Issue by xarvatium** [Aliucord/plugin-requests#54]
### Description
Removing the telemetry and tracking that are found in the base Discord app.

### More info
Basically preventing Discord's telemetry from communicating in some way to protect the end user's privacy.

---

- [x] I checked if this plugin wasn't already requested.

**Comment by Vendicated** [comment]
this is already part of the Aliucord coreplugins https://github.com/Aliucord/Aliucord/blob/main/Aliucord/src/main/java/com/aliucord/coreplugins/NoTrack.java
