### ISSUE TITLE
Time VC

### ISSUE THREAD

**Issue by kewg0** [Aliucord/plugin-requests#551]
### Discord Account

kkwk#2655

### Plugin Description

The plugin can show how long you've been in a VC & I think also a 'bed time' reminder to get off Discord would also be cool.

### Go into more detail...

It can be displayed as another bar below the original one or it can be shown at the Mobile Voice Overlay for convinces and doesn't hog up more screen space.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
#119 #204 
 https://github.com/TymanWasTaken/aliucord-plugins/raw/builds/CallTime.zip
 "I did indeed check to make sure my plugin request is original!"
 Please look harder next time
