### ISSUE TITLE
Bitch generator

### ISSUE THREAD

**Issue by Nour112** [Aliucord/plugin-requests#552]
### Discord Account

username#0000

### Plugin Description

Bitch generator
Bitch generator
Bitch generator
Bitch generator

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
Unfortunately this plugin would be incompatible for you

**Comment by ItzOnlyAnimal** [comment]
![no bitches??](https://cdn.discordapp.com/attachments/811255667469582420/932876822859886663/196-rzdp19.png)
