### ISSUE TITLE
JUST REQUEST

### ISSUE THREAD

**Issue by Pretty1Kitty** [Aliucord/plugin-requests#553]
### Discord Account

FancyIdi♡T#6572

### Plugin Description

Suggest Number One 
1- I'd suggest to have timezone 
Next to our friend name for example
Alexa 2:00 AM
Hello
Siri 4:00 AM
Hi 

If you ignore suggest number one (1)
.
.
.
Here is suggest number Two (2) 

2- I'd suggest to have Costume nickname
We set nickname to someone on any 
server dms etc like for example 
Alexa 2:00 AM
Hello 

Everyone see name and everything normal
Expect me I put nickname ONLY ME sees
The nickname I put for example (annoying)
For them it show 

Alexa 2:00 Am
Hello  (what they see) 

For me 

Annoying 2:00 
Hello  (what i see) 

If you ignore suggestion number three (2)
.
.
.
Here is suggestion number three (3) 

3- I'd suggest to be able to copy other 
people BIO / STATUS (That's it) 

If you ignore suggestion number three (3)
.
.
.
Here is suggestion number three (4) 

4- I'd suggest to have feature that shows
All github READ ME about the Plugin
Because we (Most) ignore README
But if it's on plugin description we read it
And add scroller on it so we can scroll on this little small box and read
.
.
.
GET 2 OR ALL OF THOSE DONE 
CAN'T WAIT FOR IT

### Go into more detail...

No detials just want to be idiot 999%

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
use the format :husk: don't make multiple requests in one issue

**Comment by Pretty1Kitty** [comment]
NEW TO GITHUB BROTHER

**Comment by hairyfred** [comment]
Please make these separate requests and use the template

**Comment by NemNorbi** [comment]
tf?
