### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by Pretty1Kitty** [Aliucord/plugin-requests#554]
### Discord Account

FancyIdi♡T#6572

### Plugin Description

I think it only displays in the user's profile. Would be a cool feature if it displayed next to messages
Like instead of clicking someone profile and see the GMT+ (TIMEZONE WE SAT) 
can we just have it next to the msg?
Wouldn't it be better?

### Go into more detail...

FOR 2ND TIME NO DETIALS XD

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by mantikafasi** [comment]
Make that request to developers repo as feature Request, not here
