### ISSUE TITLE
Secret-Servers

### ISSUE THREAD

**Issue by Asimoposting** [Aliucord/plugin-requests#555]
### Discord Account

Asimo#2810

### Plugin Description

A plugin that hides servers from discord, for seeing the server you need to go to a menu or putting a password

### Go into more detail...

There should be a menu that makes you enter the password for entering the server

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
Somewhat a duplicate of #520
