### ISSUE TITLE
Fnaf-cord🥵

### ISSUE THREAD

**Issue by Asimoposting** [Aliucord/plugin-requests#558]
### Discord Account

Asimo#2810

### Plugin Description

A plugin that has the command of putting all the lore of fnaf, the order of fnaf games, question of fnaf games, characters of fnaf games

### Go into more detail...

Slash command please UWU 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
Please can you elaborate, what do you mean by "putting all"

**Comment by Asimoposting** [comment]
> Please can you elaborate, what do you mean by "putting all"

Ok, (i wont be online at 21:00 to 15:00 (germany time)
