### ISSUE TITLE
Spotify Controls

### ISSUE THREAD

**Issue by Dxrkzen** [Aliucord/plugin-requests#559]
### Plugin Description

So basically like you can join and invite people to listen with you on Spotify and add spotify controls like there is a plugin for PC which let's you control spotify inside the app like Play, Pause, Skip Song, Volume etc. 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Dxrkzen** [comment]
Like this plugin for BD by devilbro https://betterdiscord.app/plugin/SpotifyControls

**Comment by RhyMegu** [comment]
That's cool and all, but _where_ would the controls be placed?

**Comment by Dxrkzen** [comment]
> That's cool and all, but _where_ would the controls be placed? 

You could make it like a slash cmd so when you do for example /controls it shows the spotify controls thing with Clyde and the buttons actually work

Or. 
Make it like a little icon when you open discord so basically when you click it shows all the things the I was talking about and maybe a playlist preview? So like you don't have to get out of the discord app and you can just click the floating little round bubble

**Comment by Dxrkzen** [comment]
In the image below, in the top right corner you can see the outline of the button 
In the settings you can make it so it doesn't appear or it appears. 

![20220118_232119](https://user-images.githubusercontent.com/84992554/150064006-58ad745c-f47f-4659-9a3f-428f7db5a113.jpg)

**Comment by Vendicated** [comment]
This plugin is very very very much effort for a feature that already exists one swipe away. Just pull down and use the Spotify notification and for volume quite literally just use your volume buttons
