### ISSUE TITLE
Character Counter

### ISSUE THREAD

**Issue by clarkgp** [Aliucord/plugin-requests#56]
### Description
Adds a live character counter in fields where text can be inputted.

### More info
The live character counter is visible in any text input box such as the nickname editor, user notes, message input, etc.
For message input, if possible, maybe add a small spacer below the message box.

---

- [x] I checked if this plugin wasn't already requested.

**Comment by Litleck** [comment]
Shouldn't be too hard to make this. I'll see what I can do
