### ISSUE TITLE
Change the home icon

### ISSUE THREAD

**Issue by biast12** [Aliucord/plugin-requests#561]
### Discord Account

Biast12 (Tobias)#0001

### Plugin Description

A plugin that allows you to change the home icon directly (overwriting the theme), by either selecting an image on your phone or adds a link where the icon can be added (like from imgur.com)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
you mean the app icon in your launcher?

**Comment by OmegaSunkey** [comment]
he means the discord icon in the bottom bar

**Comment by biast12** [comment]
i mean Change the Home icon in the left top corner.
![image](https://user-images.githubusercontent.com/53872542/150185341-d20e5ba5-c5dd-4459-92fe-e34667cbf71b.png)
![image](https://user-images.githubusercontent.com/53872542/150185375-2a1436f2-1b39-4cb4-9609-144d89954bbc.png)

**Comment by biast12** [comment]
also if you want a reason, it's because the icon looks ugly and i want to change it for something better looking, so 
please keep me up if it's at least possible to do so

**Comment by ItzOnlyAnimal** [comment]
cant u use themer for this

**Comment by biast12** [comment]
i asked if that was possible, but no one said anything, tho i assume we can't

**Comment by ItzOnlyAnimal** [comment]
ah k anyway working on it lol

**Comment by ItzOnlyAnimal** [comment]
Done https://github.com/ItzOnlyAnimal/AliuPlugins/blob/builds/HomeIconSwitcher.zip?raw=true
