### ISSUE TITLE
Member list search

### ISSUE THREAD

**Issue by hjyoung1** [Aliucord/plugin-requests#564]
### Discord Account

Juan66#8279

### Plugin Description

A plugin to search and find members quickly directly from sidebar.
If user hasn't posted any message finding them using normal search is very hard.
If implementing this isn't possible (api issues, etc) then atleast making roles collapsable in sidebar would be good too.
Please check below picture to get the gist of what i mean with my request.
![request](https://user-images.githubusercontent.com/45882061/150386496-3755c918-9f90-4a68-9e7c-0a714a548127.png)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
Not possible. If the member isnt findable by trying to @ them that means they're not cached and theres no way to get all members

**Comment by hjyoung1** [comment]
> Not possible. If the member isnt findable by trying to @ them that means they're not cached and theres no way to get all members

Closing this then. Maybe discord will add this natively someday ~~for nitro users~~.
If i have multiple requests is it alright to open one issue with all details? Or need to open separate for each?
