### ISSUE TITLE
More Codes Types (Binary, Morse ect)

### ISSUE THREAD

**Issue by Nonexist1** [Aliucord/plugin-requests#569]
### Discord Account

҈҈#9595

### Plugin Description

So i saw the Base64 plugin, and i tought "what if theres more codes?" so thats why i decided to post it here.
mostly, at least some to be added (like Morse, Binary, maybe Enigma?), but i think its going to be hard, i think...
i dont know
i wanted to do it by myself, but since im a profesional idiot whit no pc, amd having absolutely no idea how to code, i hoped someone would do it

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by oSumAtrIX** [comment]
Can you explain how that would be useful? If you convince me, you can send me a list of encodings/encryptions

**Comment by DiamondMiner88** [comment]
This should be added to the Translate plugin instead

**Comment by Nonexist1** [comment]
> Can you explain how that would be useful? If you convince me, you can send me a list of encodings/encryptions

well, my idea was for like pepole who cant / dont want / lazy to learn to code and decode, and just for secret messaging (for Enigma), it just will be fun, and secret messaging, if someone has their dm's closed.

Here's just a lil list that i had ideas to be:
-Binary
-Morse
-Enigma (this one is more harder, due that its more complicated)

if you do it, please dont force it on yourself, i dont want to force it to be maked, it was just a idea, oh well, i hope you have a nice day!

**Comment by hairyfred** [comment]
Not really secret messaging as its obvious what each code is
Base64 is used often to post links to warez, hense why the plugin exists
Other codes arnt really used, and if you want encrypted messages, theres a plugin that does that

**Comment by Nonexist1** [comment]
> This should be added to the Translate plugin instead

why on that one?
wouldn't be better like a Beta64 pack?
because Translate is languages, and codes are just... codes, not languges... im just confused...

**Comment by Nonexist1** [comment]
> Not really secret messaging as its obvious what each code is Base64 is used often to post links to warez, hense why the plugin exists Other codes arnt really used, and if you want encrypted messages (also invisible), theres a plugin that does that

oh...
i tougjt it just be a good idea, but guess i think i just wasted pepoles time, oh well, sorry for this dumb idea that i head.

welp, have a great day, at least!
