### ISSUE TITLE
UserVolumeBooster (OG by QWERT[BD])

### ISSUE THREAD

**Issue by depressquid** [Aliucord/plugin-requests#570]
### Discord Account

lisquid#4889

### Plugin Description

Allows you to set a user's volume in a voice chat/call above the maximum 100% for mobile

### Go into more detail...

imo there's almost nothing more frustrating than a user you can't hear in a voice chat, and literally _not being able to increase their volume_. as the image below shows, a plugin such as this would change that, and I honestly think it would be extremely usefully for Aliucord users, being on mobile and all.

![image](https://user-images.githubusercontent.com/98269110/150763625-70a8d8d7-b4d0-42dd-b71e-12d77fe0b5a3.png)
[betterdiscord code](https://betterdiscord.app/plugin/UserVolumeBooster)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
- #193
