### ISSUE TITLE
AssignBadges

### ISSUE THREAD

**Issue by EvilZoidYT** [Aliucord/plugin-requests#573]
### Discord Account

EvilZoid#4315

### Plugin Description

Allows you to locally assign badges to users to the users would be cool.

### Go into more detail...

It would be cool if this plugin exist, that you can locally add badges to people

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
#69 #171 #196 #205 
"I did indeed check to make sure my plugin request is original!"
