### ISSUE TITLE
Scrape/Download image/s from a channel

### ISSUE THREAD

**Issue by KazKaz90** [Aliucord/plugin-requests#575]
### Discord Account

薔薇|•KaZero#9327

### Plugin Description

As stated in the title, a plugin that can scrape or download all images from a channel, I'm not sure if it's possible, but I'll just leave it here.

### Go into more detail...

Make it a slash command plugin, perhaps.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by JonathanSwatz10** [comment]
Can someone block @KazKaz90 he just tried to selfbot.

**Comment by KazKaz90** [comment]
> Can someone block @KazKaz90 he just tried to selfbot.

@JonathanSwatz10 This is 3 months ago

**Comment by JonathanSwatz10** [comment]
I know.

**Comment by KazKaz90** [comment]
> I know.

Ok

**Comment by KazKaz90** [comment]
Owners or collaborators please lock this issue
