### ISSUE TITLE
DoNotTrack Port/Telemetry blocker

### ISSUE THREAD

**Issue by Hate9** [Aliucord/plugin-requests#576]
### Discord Account

Mrs. Policewoman#0106

### Plugin Description

A plugin that prevents discord from tracking you via telemetry/analtyics would be great.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
Already built in

**Comment by Hate9** [comment]
oh dang, really? nice!
