### ISSUE TITLE
Change Twimojis to system emojis, or any emoji set 

### ISSUE THREAD

**Issue by shxrted** [Aliucord/plugin-requests#589]
### Discord Account

eftahjn#9005

### Plugin Description

I think discord should have done this a long time ago, and since they clearly haven't yet, there should be a plugin that changes discord to use system emojis/any system emoji, for example google/apple/samsung and so on.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
![image](https://user-images.githubusercontent.com/24845294/151106653-46ee27ac-5b16-4352-bb8b-75ae274c4315.png)
:trollface:

**Comment by shxrted** [comment]
> ![image](https://user-images.githubusercontent.com/24845294/151106653-46ee27ac-5b16-4352-bb8b-75ae274c4315.png) :trollface:

the last time a suggestion was made was like 8 months ago so I didn't know if it was still being worked on, my bad
