### ISSUE TITLE
Hide "Find or start a conversation"

### ISSUE THREAD

**Issue by TheOddGarlic** [Aliucord/plugin-requests#6]
### Description
A plugin that hides the "Find or start a conversation" button/bar under direct messages.

### More info
The search button exists.

---

- [x] I checked if this plugin wasn't already requested.

**Comment by X1nto** [comment]
I'll grab this one too.

**Comment by X1nto** [comment]
Done.

Screenshot:
![image](https://user-images.githubusercontent.com/48173186/119878517-46fea000-bf3b-11eb-891e-a730b1e66843.png)

Link: https://github.com/X1nto/AliucordPlugins/raw/builds/HideSearchBox.zip
