### ISSUE TITLE
EmojiReplace

### ISSUE THREAD

**Issue by Clown69420** [Aliucord/plugin-requests#601]
### Plugin Description

Replaces Discord's Emojis with Emojis of a different Provider (Apple, Facebook...)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
me when I did indeed check to make sure my plugin request is original!

duplicate #589 #563 #363 #22 and several more

**Comment by hairyfred** [comment]
Sir I recommend an eye test asap for your safety
