### ISSUE TITLE
Double tap message option to locally edit messages 

### ISSUE THREAD

**Issue by harrynotfound** [Aliucord/plugin-requests#604]
### Discord Account

mr.harry#8366

### Plugin Description

not really a plugin thing but can you guys make it so that , there is another option to select in the taptap plugin so if you double tap any messages it will locally edit a message , as if the other commands too 

### Go into more detail...

probably just a new update to it , to double tap and be able to edit any message locally

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
Request it on taptap's plugin repo

**Comment by hairyfred** [comment]
Request it on taptap's plugin repo
