### ISSUE TITLE
how about a plugin that could just make it so that...

### ISSUE THREAD

**Issue by harrynotfound** [Aliucord/plugin-requests#605]
### Discord Account

mr.harry#8366

### Plugin Description

![IMG_20220130_095143](https://user-images.githubusercontent.com/84095133/151686510-17262422-51b8-43e5-aa94-5729823ca912.jpg)
How about a plugin that could just make it so that , when you tap the pfp from there it would show the full pfp photo but from here not in the profile 

### Go into more detail...

ik there is a plugin which if you see someone's profile and tap there pfp it will show the image , smthn like that but for other place 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
request it for viewprofileimages

**Comment by Vendicated** [comment]
but why

literally just use view profile images and open profile it's one click more
