### ISSUE TITLE
Themer Stop

### ISSUE THREAD

**Issue by Itsfadixx** [Aliucord/plugin-requests#606]
### Plugin Description

A plugin that stops all the themes from working when trying to screen shot a dm or a discord convo  

### Go into more detail...

it's should work like ones a Screenshots is TRIGGERD the theme wil lstop working entirely, Its like that because so there is no more people trying to report you to discord  Admins 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
Not possible without a restart and other plugins would still give it away. Just use stock discord for taking Screenshots
