### ISSUE TITLE
AudioFileListener

### ISSUE THREAD

**Issue by skullhunter0x7** [Aliucord/plugin-requests#607]
### Discord Account

skullhunter0x7#6396 

### Plugin Description

This would allow audio files to be played on mobile (much more detail in the next section)

### Go into more detail...

When an audio file such as an mp3 is uploaded to a channel there is no play button or anything to let you listen to it (like there is on desktop) you'd have to download it and play it another way, this would simply allow them to be played on mobile, without the lengthy process to do it.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
#105 #143 #319 #494
" I did indeed check to make sure my plugin request is original!"

**Comment by skullhunter0x7** [comment]
Welp i understood wrong. Quite idiotic looking back. I only checked existing plugins, my bad
