### ISSUE TITLE
Timestamp Calculator

### ISSUE THREAD

**Issue by Killermaschine88** [Aliucord/plugin-requests#610]
### Plugin Description

Basically a calculator for Discords <t:time> timestamps where you can set days etc to add

/timestamp days hours minutes

prints out current date + the time you specified

/timestamp 1 0 0 would send an ephemeral message which holds the correct time (current time + 1 day formatted in seconds) for the user to copy paste

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
exists

**Comment by Killermaschine88** [comment]
where i didnt find it

**Comment by Killermaschine88** [comment]
damn found it fml
