### ISSUE TITLE
Games played

### ISSUE THREAD

**Issue by trapcoa** [Aliucord/plugin-requests#611]
### Discord Account

trapcoa#4129

### Plugin Description

Idk if its even possible cause im dumb but a pluggin that allows you to see what games a user has previously played while discord was active

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
its not an aliucord plugin but use this https://github.com/MrSpidercat/DiscordVerifiedGameStatistics

**Comment by rushiiMachine** [comment]
discord does not run in the background
