### ISSUE TITLE
Plugin for moving servers around

### ISSUE THREAD

**Issue by griffi-gh** [Aliucord/plugin-requests#612]
Moving shitty servers i join to the bottom of the list extremely long a tedious process.  
A Aliucord plugin which allows to rearrange the discord server list faster or even move servers in groups should be the perfect solution.  
The server context menu seems to be the perfect place for a button that opens the fullscreen menu with channel-list-like controls(?)

**Comment by zt64** [comment]
You will follow the issue template

**Comment by griffi-gh** [comment]
@zt64 Uhh it didn't offer me to use it

**Comment by hairyfred** [comment]
> @zt64 Uhh it didn't offer me to use it

It did
redo this with the template
