### ISSUE TITLE
Quick scroll to mention/ping

### ISSUE THREAD

**Issue by TotallyHuman675** [Aliucord/plugin-requests#614]
### Discord Account

TotallyHuman#0675

### Plugin Description

A plugin that adds a button that you can press to quick scroll to an unread ping/mention, like ones on Whatsapp 

### Go into more detail...

Sometimes i get pinged but i cant find the message and i cant reply to it, so it would be great if we can automatically scroll to the last ping/mention

### Request Agreement

- [x] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
literally built into discord 
![image](https://user-images.githubusercontent.com/24845294/152476535-7b5f452f-ecc5-4225-b5ee-913f7c5185ed.png)

**Comment by TotallyHuman675** [comment]
> literally built into discord (the @ icon)
> ![image](https://user-images.githubusercontent.com/24845294/152476535-7b5f452f-ecc5-4225-b5ee-913f7c5185ed.png)
> 

Wait what, oh sorry, im an idiot
