### ISSUE TITLE
⭐ - Ability to favorite media on mobile

### ISSUE THREAD

**Issue by frodest-rodest** [Aliucord/plugin-requests#615]
### Discord Account

Rodewt#2655

### Plugin Description

Allows to favorite images and videos for later use

### Go into more detail...

I think the button to favorite the files and media can be in the long press menu on a message containing a video or image file.
A way to access the favorited media can have a dedicated category where you can long click to copy it's media.discordapp link and use it anywhere you like. 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by mantikafasi** [comment]
https://github.com/Aliucord/plugin-requests/issues/417
duplicate
