### ISSUE TITLE
Auto-delete Failed Embed's

### ISSUE THREAD

**Issue by sszz7** [Aliucord/plugin-requests#616]
### Plugin Description

(Suggestion)

Pretty much a Plugin that automatically deletes for the user if ever the embed they sent failed. (Anti-Embed Fail Plugin)

Pros
+Saves the user from embarassment
+No more failed video/gif/emote messages

Cons
-People with embed fail gif saved will be very sad

### Go into more detail...

You: Sent a funny meme embed
Discord: *ruins your day*
Everyone: <embed fail, laugh at this user.gif>

-- 

If ever this plugin is made:

You: Sent a funny video embed
  -fails but it got automatically deleted by the plugin-
Everyone: *saw nothing*

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
there is no way to detect if a link is supposed to unfurl into an embed without unfurling it yourself
