### ISSUE TITLE
Google search plugin

### ISSUE THREAD

**Issue by HaHyun-Ki** [Aliucord/plugin-requests#619]
### Discord Account

Ha Hyun-Ki#6527

### Plugin Description

I request the developers to create a plugin from which if we use Slash command /search (text) it will send the screenshot of Google results and we can also do like
/search (text) send: true/false like this it would be great.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
I'll take this

**Comment by HaHyun-Ki** [comment]
> I'll take this

K Thanks

**Comment by DiamondMiner88** [comment]
https://user-images.githubusercontent.com/33725716/152808203-d8d37c7d-8a3d-4b51-9969-c62551d922d0.mp4

**Comment by ItzOnlyAnimal** [comment]
but diamond we need a plugin for every possible thing imaginable :trollface: :moyai:

**Comment by scrazzz** [comment]
Done https://github.com/scrazzz/AliucordPlugins/raw/builds/ScreenshotAPI.zip

:trollface:

**Comment by HaHyun-Ki** [comment]
> Done https://github.com/scrazzz/AliucordPlugins/raw/builds/ScreenshotAPI.zip
> 
> :trollface:

Doesn't work ;-;

**Comment by hairyfred** [comment]
> 20220207_063340.mp4

Sums it up pretty well

**Comment by JonathanSwatz10** [comment]
That's wrong it supposed to be completed not rejected stupid low quality @hairyfred

**Comment by hairyfred** [comment]
> That's wrong it supposed to be completed not rejected stupid low quality @hairyfred

Zero idea how I did that, updating label now

**Comment by catnamedmina** [comment]
Delete it @wingio now
