### ISSUE TITLE
Automatic PFP Change

### ISSUE THREAD

**Issue by MizuMizuGaming** [Aliucord/plugin-requests#625]
### Discord Account

Mizu 水#6969

### Plugin Description

I think a plugin that lets you select a folder from your phone and auto change your pfp to images from the folder every day would be cool. (You have to crop the images beforehand or they'll be auto cropped).

### Go into more detail...

I asked someone how I'm supposed to figure out if a plugin would be possible and they told me to just use common sense. I think this one should be possible but idrk. 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
:husk: selfbot

**Comment by hairyfred** [comment]
Even though daily it would be such a slow speed I doubt discord would care

Still a selfbot.
