### ISSUE TITLE
Hide Nitro-only/unusable emoji

### ISSUE THREAD

**Issue by PookaMustard** [Aliucord/plugin-requests#626]
### Plugin Description

A plugin that hides all nitro-only or unusable emoji

### Go into more detail...

As a non-nitro user, the emoji picker is cluttered with unusable custom emojis. To reduce clutter and make the emoji picker easier on the eyes, all nitro-only emoji would be hidden or disabled (unless say you were a nitro user), including the emoji categories of other servers.

[This plugin is already available as a cutthecord patch](https://gitdab.com/distok/cutthecord/src/branch/2021-05-31/resources/patches/hideunusableemojis), so I believe should be possible with Aliucord. (Unless there's something I don't know about preventing it).

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by neko-astolfo-uwu** [comment]
EmojiUtility has this already
![Screenshot_2022-02-12-15-18-05-166_com aliucord](https://user-images.githubusercontent.com/81871789/153714979-dd7d80be-af6e-478c-9478-387dd63d6a76.jpg)

**Comment by PookaMustard** [comment]
Ah, thanks for the mention. It didn't occur to me that EmojiUtility would have that 😅 
Closing now.
