### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by LLAFTeamKiwi** [Aliucord/plugin-requests#63]
### Discord Account

[L.L.A-F] TeamKiwi#6959

### Plugin Description

Change the default font to a custom one.

### Go into more detail...

Be able to change the default font to a custom with a font file.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by RGBCube** [comment]
maybe not default, but `/customfont message:like this?`

**Comment by Juby210** [comment]
What? They want to replace font for example in chat that they see, not in messages xD

**Comment by BloupLeVrai** [comment]
> 
> 
> What? They want to replace font for example in chat that they see, not in messages xD

Lol we want to change the font in the discord, to make one more pleasurable to read

**Comment by LLAFTeamKiwi** [comment]
Me and BloupLeVrai will try to make it

**Comment by Vendicated** [comment]
Fulfilled by the themer plugin https://github.com/Vendicated/AliucordPlugins/blob/builds/Themer.zip
