### ISSUE TITLE
Open Steam Links In App [OG : DevilBro]

### ISSUE THREAD

**Issue by MrArhynaH** [Aliucord/plugin-requests#630]
### Plugin Description

A plugin that will open steam links in the steam app directly instead of opening them on browser.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by MrArhynaH** [comment]
Doesn't work with discord. Either it takes me to browser or just doesn't do anything.

**Comment by ItzOnlyAnimal** [comment]
ah. does nothing for me as well now L
wait for some1 to make a plugin or bug valve

**Comment by Vendicated** [comment]
literally already a thing. it doesn't work but that's steam skill issue and Aliucord can't fix that. message steam support

![Screenshot_20220215-152030](https://user-images.githubusercontent.com/45497981/154080650-4d5ba397-5b52-4566-be67-4a88f6f503e3.png)
