### ISSUE TITLE
Hold and move channels

### ISSUE THREAD

**Issue by dxddiidxnnii** [Aliucord/plugin-requests#633]
### Discord Account

jah#2612

### Plugin Description

I know this has been requested before but what I think is something along the lines but different. How about a way to hold down channels from the channel list and move it around just like on pc. 

### Go into more detail...

A way to press and hold a channel or category in the channel list and move it up or down on the list. Probably make it scroll up when you drag above the channel list.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
#305

**Comment by sourcekilla** [comment]
https://user-images.githubusercontent.com/94068062/155764238-7a36ef46-b68b-4a87-a8de-a62e4b013c5d.mp4

possible already
