### ISSUE TITLE
Split messages over 10 files

### ISSUE THREAD

**Issue by VoltoxderEchte** [Aliucord/plugin-requests#635]
### Plugin Description

When your message has more than 10 files discord wont send them.
A good idea would be to split the files in different messages

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by saintwithataint** [comment]
Duplicate of https://github.com/Aliucord/plugin-requests/issues/566
