### ISSUE TITLE
Cum plugin

### ISSUE THREAD

**Issue by onbotbutcool** [Aliucord/plugin-requests#636]
### Discord Account

onbot#4520

### Plugin Description

hmm

### Go into more detail...

whenever you type something it'll randomly add CUM to the end of the sentence

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
Unfortunately this plugin isn't useful to most people.

**Comment by catnamedmina** [comment]
Cum
