### ISSUE TITLE
Actively listen for notifications

### ISSUE THREAD

**Issue by ChaosNicro** [Aliucord/plugin-requests#638]
### Discord Account

Nicro#5093

### Plugin Description

I don't have access to GCM and would like to get notifications if possible. 

### Go into more detail...

Possibly done by periodically waking up to actively check for updates. Alternatively many FOSS apps use a permanent notification to keep a service awake. There is also UnifiedPush, but that doesn't seem viable here, since it would need server-components.

I understand that the framework may not be powerful enough to do this, but Discord is one of the few messagers that still strictly rely on Google notifications.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
there is no way to retrieve push notifications without gcm as it is the sole source
