### ISSUE TITLE
audio i/o switcher

### ISSUE THREAD

**Issue by skff-err** [Aliucord/plugin-requests#639]
### Discord Account

zach#8998

### Plugin Description

i should be able to switch input devices either between phone's mic or connected devices's mic and vice versa for output

i hope this option could be included in the voice and video section in settings if possible thanks for considerign :))))

### Go into more detail...

20 bucks earphone

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
Duplicate of #151.
