### ISSUE TITLE
A plugin to crash android in one way or another

### ISSUE THREAD

**Issue by GangsterFox** [Aliucord/plugin-requests#64]
### Discord Account

Fox#0004

### Plugin Description

For the hell of it make a plugin which will one way or another crash android and force your phone to restart. 

### Go into more detail...

The plugin could achieve an android crash in multiple ways, so why not make it even easier with a slash command to insta crash android and force your phone to restart. Why do we need it I have no idea but I would like to see it happen since I would use it. You could try making clyde send a really long message, maybe make a setting to only crash Aliu but that would be boring. Anywho be creative on ways how to crash android.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
what about no
