### ISSUE TITLE
spam

### ISSUE THREAD

**Issue by EMan9543** [Aliucord/plugin-requests#640]
### Discord Account

Spammmy#6262

### Plugin Description

Add a /spam command to spam a word of your choice

### Go into more detail...

Like this

/spam 666 devil
Devil
Devil
Devil
Devil
Devil
etc

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
this doesnt abide by the rules

**Comment by OmegaSunkey** [comment]
+ not original

**Comment by Juby210** [comment]
We don't allow such plugins, end of story.
