### ISSUE TITLE
Aliucord Badge.

### ISSUE THREAD

**Issue by cyclone018** [Aliucord/plugin-requests#641]
### Discord Account

theabyss#5000

### Plugin Description

I think it would be cool to have a plugin that shows people that are using aliucord. With the plugin oc. 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
Already exists and is built-in to Aliucord, but you have to support us to make your badge visible to all Aliucord users. https://www.patreon.com/Aliucord

If you don't want to support us you can get a badge but only visible for you using https://github.com/wingio/plugins/blob/builds/CustomBadges.zip
