### ISSUE TITLE
Aptate Port

### ISSUE THREAD

**Issue by cyclone018** [Aliucord/plugin-requests#642]
### Discord Account

theabyss#5000

### Plugin Description

I think this would also be cool to send encrypted messages to each other. 

Based off of this mod, and maybe have same encryption for cross platform.
https://betterdiscord.app/plugin/Apate 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
Already exists, https://github.com/mantikafasi/AliucordPlugins/blob/builds/InvisibleMessages.zip
