### ISSUE TITLE
role stealer

### ISSUE THREAD

**Issue by myysty** [Aliucord/plugin-requests#644]
### Discord Account

mysty#0001

### Plugin Description

just copies the role and adds it to another server (where you have role permissions) useful if you wanna steal colour roles

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [x] I did indeed check to make sure my plugin request is original!

**Comment by saintwithataint** [comment]
You can use RCM by Wing to copy role colors

**Comment by myysty** [comment]
where can i find this

**Comment by Henry-Hiles** [comment]
https://github.com/wingio/plugins
![Screenshot_20220323-121503032 (1)](https://user-images.githubusercontent.com/71790868/159746005-315abb54-0756-4984-9f17-889180dfe50a.jpg)

**Comment by saintwithataint** [comment]
This one can be closed btw
