### ISSUE TITLE
Last.fm discord activity

### ISSUE THREAD

**Issue by br4zyy** [Aliucord/plugin-requests#645]
### Discord Account

brazy#9346

### Plugin Description

Shows your last.fm currently playing track on your profile like how Spotify does

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
Not possible on mobile

**Comment by br4zyy** [comment]
> Not possible on mobile

ok then
