### ISSUE TITLE
Meme command!

### ISSUE THREAD

**Issue by HaHyun-Ki** [Aliucord/plugin-requests#646]
### Discord Account

Ha Hyun-Ki#6527

### Plugin Description

If we use Slash command ( /meme ) it will send a video meme or pic meme!

Eg: /meme
Output: Video meme/picture meme  ( but the YouTube ones because reddit memes are ded memes like of dank memer ;-; )

If there will be /meme send:(true/false) it would gud.

**Comment by scrazzz** [comment]
Duplicate of #369
