### ISSUE TITLE
shortcut for delete message button

### ISSUE THREAD

**Issue by bozohi** [Aliucord/plugin-requests#649]
### Plugin Description

just make a shortcut for deleting messages button, nothing much

### Go into more detail...

ą

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
Duplicate of #560 ~~and #2.
Ven pls check #2 and implement it to TapTap~~
