### ISSUE TITLE
Clone channels from other servers

### ISSUE THREAD

**Issue by BRY4NZIN** [Aliucord/plugin-requests#650]
### Discord Account

BRY4N 🐄#1849

### Plugin Description

Clone channels from other servers including permissions

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by saintwithataint** [comment]
how would you clone perms bro, that would require both servers to have the same roles

**Comment by BRY4NZIN** [comment]
Hm ok, So only channels?

Em seg., 21 de fev. de 2022 11:03, Saint ***@***.***>
escreveu:

**Comment by scrazzz** [comment]
Duplicate of #341 and #482
Check issue #341, this is already an existing plugin
