### ISSUE TITLE
Hide servers

### ISSUE THREAD

**Issue by Darkyistakenok** [Aliucord/plugin-requests#653]
### Discord Account

Darky#6454

### Plugin Description

A simple plugin to hide servers from servers bar just to keep discord clean and get more Emojis 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
#300 #375 #520 #555 
"I did indeed check to make sure my plugin request is original!"
