### ISSUE TITLE
CameraPermDisabler

### ISSUE THREAD

**Issue by xStormyy** [Aliucord/plugin-requests#654]
### Discord Account

I think it's pretty obvious who it is really.

### Plugin Description

A Plugin That Doesn't Force You To Enable The Camera Permission Everytime You Wanna Change Your Profile Picture Or Server Picture.

### Go into more detail...

desc.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
but why

**Comment by xStormyy** [comment]
Because it's annoying as hell to have to disable camera perms after I changed my pfp for example

**Comment by Vendicated** [comment]
just choose "only this time"?
