### ISSUE TITLE
Next Image

### ISSUE THREAD

**Issue by sneazy-ibo** [Aliucord/plugin-requests#657]
### Discord Account

❥ᰰຼ ‧ ꪱ𝚋𝚘 ‧໋݊ 𖠲۪#5114     / 915996800391987220 I am changing my name way to often ;~;

### Plugin Description

A plugin that allows you to move to the next or the last image in fullscreen

### Go into more detail...

A plugin that allows you to switch to the next image on fullscreen if multiple images are sent. Double clicking each side to go back or forward. That would be combined with the nhentai pages option really useful ;3

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
#210
