### ISSUE TITLE
Bypass Ban Plugin

### ISSUE THREAD

**Issue by FrancisKhian** [Aliucord/plugin-requests#659]
### Discord Account

Francis Khian L. Coniendo#4894

### Plugin Description

Can you please add the "Bypass Ban" Plugin because I want to get unbanned from the banned server... That would be cool If you have a "Bypass Ban" Plugin and I have been wishing this to happen so can you please add It?

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
This isn't possible

**Comment by OmegaSunkey** [comment]
+ doesn't abide by the rules

**Comment by DiamondMiner88** [comment]
alt+vpn
