### ISSUE TITLE
Disable untrusted domain link warning dialog

### ISSUE THREAD

**Issue by tayloroneill** [Aliucord/plugin-requests#66]
### Plugin Description

Requesting a plugin that disables this for all domains

![Screenshot_20210628-180036](https://user-images.githubusercontent.com/61822772/123601206-be756700-d83a-11eb-8a09-2aa92172c1c4.png)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Litleck** [comment]
I'm gonna try making this

**Comment by zt64** [comment]
Added in HideBloat as of latest version
