### ISSUE TITLE
Preview selected message selected before deletion/pin/etc

### ISSUE THREAD

**Issue by SylveonBottle** [Aliucord/plugin-requests#661]
### Plugin Description

Whenever I'm about to delete a message, I can't tell if I'm deleting the correct message or if my big fat thumbs might've selected a message just above/below the one I want to be deleted.
The message options (edit, delete, pin, etc) doesn't actually show you what message you've selected, so you just have to trust that you've selected the right one blindly.

I've had multiple cases where I send a few messages to a friend, decide that one message isn't good to send, hold the message and delete it, only to realize that an entirely different message got deleted because my thumb was 0.001 inches a little too high.
Once I even deleted an entirely separate user's message simply because I had no feedback on what message I was deleting.

I figure this would be a good addition for mobile users.

### Go into more detail...

Just show a preview of the message contents on the confirmation dialogue pop-up when deleting/pinning a message.

Alternatively, if one wanted to be fancy you could probably link to the message when selecting it. That might work if it scrolls far enough for the message to be shown above the options.

1. User holds finger on a message
2. Options for the message pops up
3. A link to the message is opened, resulting in the app scrolling to the selected message and highlighting it in blue
4. User knows exactly what message is currently being interacted with

This would give the user proper feedback on what message is currently being selected.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
Done
https://github.com/scrazzz/AliucordPlugins/blob/builds/WhichMessage.zip?raw=true
![penis](https://cdn.discordapp.com/attachments/807840893054353430/947564595806081024/unknown.jpeg)

**Comment by SylveonBottle** [comment]
Thanks ❤
