### ISSUE TITLE
show if user is using aliucord or not

### ISSUE THREAD

**Issue by HoriKyoukosimp** [Aliucord/plugin-requests#665]
### Discord Account

Hori kyouko#6463

### Plugin Description

If user use aliucord. Make the icon in their name like betterstatusindicator
I'm not sure if this is possible or not but if this is possible i wanna see someone make it
Thanks

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
not possible
