### ISSUE TITLE
channel drag

### ISSUE THREAD

**Issue by SparklyBubbly** [Aliucord/plugin-requests#666]
### Discord Account

SparklyBubbly#5024

### Plugin Description

Makes possible to drag channels to move their positions, like how it works in pc, also could it work with categories tol?

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by SMOLKEYS** [comment]
issue 666
