### ISSUE TITLE
Copy attachment link

### ISSUE THREAD

**Issue by dweee** [Aliucord/plugin-requests#67]
### Discord Account

dave#5225

### Plugin Description

Simple as the title. It could probably be integrated into MessageLinkContext. If anyone posts an attachment in chat (I was thinking more for audio/other files), then you can select the message and just copy the attachment file. Could be useful for image/video links too maybe?

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
Open attachment > Click share button > Copy ?

**Comment by X1nto** [comment]
Done!
https://github.com/X1nto/AliucordPlugins/raw/builds/AttachmentUtils.zip
