### ISSUE TITLE
Hide muted categories 

### ISSUE THREAD

**Issue by Gomido** [Aliucord/plugin-requests#670]
### Discord Account

Lilek#1141

### Plugin Description

Plugin that hides categories if you mute all channels in it or if you mutate the categories themselves. 

### Go into more detail...

Currently, having administrator rights after muting categories and channels, we can still see it (empty) in the channel list.  An example can be seen in the video below. I muted the channels and the category is and takes up space even though it is empty.

https://streamable.com/xgn6v5

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment]
- #176
