### ISSUE TITLE
Show media size in media picker

### ISSUE THREAD

**Issue by Random4568** [Aliucord/plugin-requests#673]
### Discord Account

Furro321#8552 

### Plugin Description

It would show how many mb/mib a file would have

### Go into more detail...

Basically, it would be in the corner, in the same place that shows the length of a video, but instead of showing the duration would show how many mb it weighs (if it is a photo) and if it is a video, it would show either on top or next to the duration and that if the media you chose pass 8mb, the aliucord would warn in some way

Here's an example I imagined:
00:00
00.0MB or 00:00 / 00.0MB

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Exists: https://github.com/rushiiMachine/aliucord-plugins
