### ISSUE TITLE
Disable image zoom limit

### ISSUE THREAD

**Issue by DiamondMiner88** [Aliucord/plugin-requests#676]
### Discord Account

Guh gaming

### Plugin Description

Opening images within Discord has a zoom-in limit which could be removed

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
https://github.com/Juby210/Aliucord-plugins/blob/builds/RemoveZoomLimit.zip
