### ISSUE TITLE
A better krisp noise supression

### ISSUE THREAD

**Issue by Slyther-quaza** [Aliucord/plugin-requests#679]
### Plugin Description

The regular krisp noise suppresion isn't as good and I would like for it to be improved 

### Go into more detail...

This would actually make the krisp noise supression way better on mobile 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by wingio** [comment]
i don't think that's possible
