### ISSUE TITLE
Revert uppercase text

### ISSUE THREAD

**Issue by dmack6464** [Aliucord/plugin-requests#68]
### Discord Account

D Mack#4481

### Plugin Description

Discord has a design language that incorporates uppercase text into sub-headers such as hoisted role and channel category names, sections in the profile popout and etc...

### Go into more detail...

I know, and even work on Discord desktop themes that reverts/resizes uppercase text, I know it's a small thing but it would make the app look nicer imo, A plugin would have to do similar things for the text to be readable.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
Claiming this

**Comment by DiamondMiner88** [comment]
finished: <https://github.com/DiamondMiner88/aliucord-plugins#nouppercase>
