### ISSUE TITLE
New quote layout

### ISSUE THREAD

**Issue by Unebe-rcg** [Aliucord/plugin-requests#680]
### Discord Account

Litegeria#5469

### Plugin Description

The current quote plugin is quite good I want an upgrade in it or a new plugin of the same (if that is possible). If will be more useful and good looking too (maybe? 🤭).

### Go into more detail...

The new structure/layout of the quote according to me should be like:

'''(tag of the person who we are replying) | Date, Exact timestamp‌'''
‌>(Their text)
Our text/reply/msg. 

Sorry, I had used ' insted of ` because GitHub is making it in block structure too like discord. 

Here is the image of the same to understand it better. 

![IMG_20220304_213124](https://user-images.githubusercontent.com/96997819/156797828-ff3f5334-d725-4e5e-8e04-36ef59bc8cc6.png)

We can also introduced an option like in the current plugin's settings that if we want to mention the user inside the block or outside. (Because one will not get tagged/pinged if their tag is written inside the block.) It depends on the user's preference. 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
You should request this on the repo of the existing plugin
