### ISSUE TITLE
Traffic routing through tor

### ISSUE THREAD

**Issue by Foxify52** [Aliucord/plugin-requests#681]
### Discord Account

foxify52#3735

### Plugin Description

A plug-in that allows you to route all your discord traffic through tor community servers or bridges. Meek support would be nice but I don't really mind if it's not there.

### Go into more detail...

This plug in would be very useful for bypassing restrictions on the network since in some places discord is blocked. It also would allow people to bypass local firewall restrictions on the networks since discord is blocked in certain places by the network administrator for usually stupid reasons even though some people use it for actual communication purposes.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
> since in some places discord is blocked
Change your dns

**Comment by OmegaSunkey** [comment]
https://play.google.com/store/apps/details?id=org.torproject.android
just use this

**Comment by RhythmLunatic** [comment]
This gets your account locked until you verify with a phone number btw
And even then they'll just disable it because they think it's a botnet
