### ISSUE TITLE
Role Icon

### ISSUE THREAD

**Issue by Physloms** [Aliucord/plugin-requests#682]
### Discord Account

Av13nts#9449

### Plugin Description

I think there should be a plugin where you can make a role have a icon.

### Go into more detail...

You know how on pc you can give roles custom icons? Maybe a plugin like that but instead for mobile and you can do it on mobile.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Physloms** [comment]
Av13nts#9449*

**Comment by DiamondMiner88** [comment]
I did indeed check to make sure my plugin request is original!

 #627

**Comment by Vendicated** [comment]
Please don't open multiple issues for the same request
