### ISSUE TITLE
Spotify Music Player

### ISSUE THREAD

**Issue by cyclone018** [Aliucord/plugin-requests#688]
### Discord Account

theabyss#5000

### Plugin Description

Pause/play next/back song detalls etc. (Basically a music player plugin for Spotify) (I'm not sure if this already exists, I'm pretty sure that it doesn't)

### Go into more detail...

Basically it adds a music player built into discord maybe towards the bottom of the channels list above the nav bar. I Maybe might have built this myself but I'm not very experienced with Knotlin and I don't know too much about how to build them correctly for this modded cilent to use it correctly. This plugin Is basically a PC port request from SpotifyControls (https://betterdiscord.app/plugin/SpotifyControls) 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
I see no point in this, there's already Spotify music controls in the notification, which is just a swipe down

**Comment by Vendicated** [comment]
This is a lot of effort for something that already exists as part of the stock Spotify app. As zt said just use the notification, it does all this while being one swipe away
