### ISSUE TITLE
Edit Users

### ISSUE THREAD

**Issue by HypedDomi** [Aliucord/plugin-requests#69]
### Discord Account

HypedDomi#1711

### Plugin Description

A plugin to edit local the users. Like pfp, name, badges, banner

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by keanuplayz** [comment]
Duplicate of #42.

**Comment by Bderdev** [comment]
I approve!

**Comment by Bderdev** [comment]
Seems pretty good.

**Comment by Juby210** [comment]
> Seems pretty good.

Please avoid useless comments. Read:
https://github.com/Aliucord/plugin-requests/blob/main/README.md#i-really-want-x-plugin-but-i-dont-know-how-to-make-it

**Comment by Asimoposting** [comment]
Hehe funny number
