### ISSUE TITLE
Server Member count

### ISSUE THREAD

**Issue by essam87** [Aliucord/plugin-requests#690]
### Discord Account

Kator#6096

### Plugin Description

Show how many total members there are in a server. Preferred place for it would be here right under "threads pins":
![Screenshot_20220308-145543](https://user-images.githubusercontent.com/17764523/157242338-5b91865b-842c-4bd4-952d-5568783e714e.png)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by FERFAIL-TXZ** [comment]
I would like to see a plugin that has the member count always visible. Yes, it is a stock feature, but you have to touch the server name to see the member count and the amount of online members. In original Discord app is already a feature, the member count is below the server name:
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/16445f2e-5fec-4c08-a3ca-14ed59e1bbd6" />

Would be also cool to add the amount of how many people are online, next to the member count.

**Comment by rushiiMachine** [comment]
@FERFAIL-TXZ make a new plugin request
