### ISSUE TITLE
Discord Stream Popout Window.

### ISSUE THREAD

**Issue by c0zymaneASC** [Aliucord/plugin-requests#691]
### Discord Account

CozyMane#6049 

### Plugin Description

Pop out window for the discord streams. 

### Go into more detail...

It should pop out the window for the discord stream window, like an overlay.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by WitherredAway** [comment]
Or at the top half of the screen maybe like on the desktop version

**Comment by rushiiMachine** [comment]
not possible without being core/too hard
