### ISSUE TITLE
Custom Game activity/Tik tok embads 

### ISSUE THREAD

**Issue by Alxiez** [Aliucord/plugin-requests#694]
### Plugin Description

I think a custom Game activity status would be a cool add on but it's just a suggestion!

And tik tok embeds since people send tik tok links alot in discord more than spotify/yt

### Go into more detail...

About the game activity I'm not sure if it against tos since you can edit it through desktop but not in mobile,

And that's it ty for ur time

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
Please open one issue per request. Also properly check whether requests already exist before opening another
