### ISSUE TITLE
a plugin that can find out who reacts message first

### ISSUE THREAD

**Issue by mhmdysf** [Aliucord/plugin-requests#696]
### Plugin Description

maybe it can help the server to find members if someone reacts with the nsfw/racist emoji

### Go into more detail...

Like if we check this page 
![Screenshot_20220312-092858_Aliucord](https://user-images.githubusercontent.com/87840041/157998214-76de831e-39f2-40ab-b3a1-f2f2fb326cc3.png)

It will show who the first react that message 
Example: (First) @username

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
this would only be possible if the reaction is added while your app is running. Use a bot instead
