### ISSUE TITLE
Invited by

### ISSUE THREAD

**Issue by WiBJDOGKINGZ** [Aliucord/plugin-requests#697]
### Discord Account

WiB JDOG KINGZ#9000

### Plugin Description

How about a plugin that tells you who invited a user with slash command or in thier user profile.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
The Discord API doesn't give information of who invited whom.

**Comment by Vendicated** [comment]
Not possible. There are bots which offer this functionality (by tracking all invites and checking which one's uses increased every time a member joins), use that
