### ISSUE TITLE
Hide Invite Members in Channels Pane

### ISSUE THREAD

**Issue by TheOddGarlic** [Aliucord/plugin-requests#7]
### Description
A plugin that hides the invite members button in the channels pane.

### More info
The same functionality is available in the guild profile menu.
And I mean this: ![Invite members button](https://cdn.discordapp.com/attachments/811275334342541353/845659539864027167/Screenshot_2021-05-22-16-49-01-15.jpg)

---

- [x] I checked if this plugin wasn't already requested.

**Comment by X1nto** [comment]
I might be able to make the plugin.

**Comment by X1nto** [comment]
Done.

Screenshot:
![image](https://user-images.githubusercontent.com/48173186/119800519-ea28c880-beed-11eb-9620-7ed601d5cdbd.png)

File: https://github.com/X1nto/AliucordPlugins/raw/builds/HideInviteButton.zip
