### ISSUE TITLE
Copy UserAvatar

### ISSUE THREAD

**Issue by Wolfkid200444** [Aliucord/plugin-requests#70]
### Discord Account

Wolfie#4444 

### Plugin Description

It Copies the Avatar Link 
and probably the banner link as well?

### Go into more detail...

I guess whoever makes this can add a double click feature so it Copies the url in your clipboard

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by RGBCube** [comment]
maybe make a button right up/down (like in bluecord) to copy user id that says
**Copy Avatar Link**
**Copy Banner Link**
which copies a cdn link of the avatar/banner

**Comment by Vendicated** [comment]
Done!

https://github.com/Vendicated/AliucordPlugins/blob/main/ViewProfileImages

![Demo](https://github.com/Vendicated/AliucordPlugins/blob/main/ViewProfileImages/demo.gif?raw=true)

**Comment by Wolfkid200444** [comment]
thank u love u
