### ISSUE TITLE
Tell if a person blocked me without interacting with them

### ISSUE THREAD

**Issue by NickEman132** [Aliucord/plugin-requests#704]
### Plugin Description

A plugin to tell if someone blocked me by adding some sort of badge/icon or text if someone blocked me without having to message them prior.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
not possible

**Comment by Vendicated** [comment]
React to one of their messages. If it doesn't work you're blocked
