### ISSUE TITLE
Copy links from audio files

### ISSUE THREAD

**Issue by br4zyy** [Aliucord/plugin-requests#705]
### Discord Account

brazy#9346

### Plugin Description

a plugin that shows a button to copy the link to an audio file when you long press the audio file

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by A-rhyna-H** [comment]
view raw?

**Comment by br4zyy** [comment]
> view raw?

wdym

**Comment by A-rhyna-H** [comment]
ViewRaw plugin gets you link for any uploaded file

**Comment by Vendicated** [comment]
Duplicate of #67
