### ISSUE TITLE
A Command To Get Your Token

### ISSUE THREAD

**Issue by RGBCube** [Aliucord/plugin-requests#71]
### Discord Account

Studio#4777

### Plugin Description

a command [/token] when executed makes a clyde dialog that has your token

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Litleck** [comment]
I'm gonna try making this

**Comment by Litleck** [comment]
Finished, you can download it at [https://github.com/litleck/aliucord-plugins/raw/builds/Token.zip]()
