### ISSUE TITLE
ThemeRepo

### ISSUE THREAD

**Issue by lvlahraam** [Aliucord/plugin-requests#711]
### Discord Account

Mahraam#5124

### Plugin Description

I would really like to have this plugin if its possible

Its just like PluginRepo but for themes

It would be easier to download themes with this plugin

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
tell @mantikafasi to make it :trollface:

**Comment by Hades785** [comment]
Literally part of the Themer plug-in 
![Screenshot_20220322-150416__01.jpg](https://user-images.githubusercontent.com/30666056/159500022-7a19cb8f-8ced-46df-a788-3f74e83b123d.jpg)

**Comment by mantikafasi** [comment]
> tell @mantikafasi to make it :trollface:

Guh I was planning to make it but since screenshots and theme files are messed up in themes channel, I dont wanna try to make a script to get all themes

**Comment by ItzOnlyAnimal** [comment]
> For the themes you could like, take the json for the theme and like make a screenshot thst has 3 parts showing about the theme...

this would probably be each theme dev's job, since they already do this in the themes channel anyway

**Comment by lvlahraam** [comment]
Oh ok....
Sorry if this was a really dumb request! 😅

**Comment by mantikafasi** [comment]
It isnt a dumb request lol, we really need something like that

**Comment by GersomR-afk** [comment]
I have no experience with Aliucord, but couldn't you autogenerate an image preview of the theme based on the theme data? I mean, you won't be able to show custom buttons from plugins, but it should do the job, I think. The Bitmap API would probably allow for some basic drawing of shapes, it would at least be possible to show the primary and accent colors, and maybe some details like the bottom navbar.
