### ISSUE TITLE
HideChannels & HideServers

### ISSUE THREAD

**Issue by lvlahraam** [Aliucord/plugin-requests#717]
### Discord Account

Mahraam#5124

### Plugin Description

A plugin that could hide the servers or channels in a db, so even when the app is restarded it wouldnt show up

(By & i meant like 2 different plugins)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by lvlahraam** [comment]
OmegaSunkey...
Folders dont work on channels
And putting a server in a folder wont actually hide it

**Comment by Vendicated** [comment]
1) mute channel
2) in server settings check hide muted channels

**Comment by rushiiMachine** [comment]
- #520
