### ISSUE TITLE
Snowfall

### ISSUE THREAD

**Issue by lvlahraam** [Aliucord/plugin-requests#720]
### Discord Account

Mahraam#5124

### Plugin Description

A plugin that is about snowfall, this plugin is like the plugins from powecord that drops snowflakes kn the screen 

https://github.com/oSumAtrlX/snowfall/
https://discord.com/channels/538759280057122817/755005584322854972/938808488728096838

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by lvlahraam** [comment]
Wow there are alot of typos in there:
"this plugin is like the plugin from powercord that drops snowflakes on the screen"*

**Comment by lvlahraam** [comment]
Bruh the github link is wrong my bad here: https://github.com/oSumAtrIX/snowfall/

**Comment by DiamondMiner88** [comment]
Duplicate of #381
