### ISSUE TITLE
Show username alongside nickname 

### ISSUE THREAD

**Issue by random-guy1285** [Aliucord/plugin-requests#722]
### Plugin Description

Exactly what it says on the tin. Formatting unimportant, as long as it's visible in the chat and member list. 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by WiBJDOGKINGZ** [comment]
We have this already 

CustomNicknameFormat

**Comment by random-guy1285** [comment]
Looked through the list 3 times and didn't see it. Guess I'm blind. Closing this
