### ISSUE TITLE
Chat stalkers are annoying

### ISSUE THREAD

**Issue by opCipher** [Aliucord/plugin-requests#723]
### Discord Account

Poor Richie#0001

### Plugin Description

So it will detect the people who are **seeing**  a
specific channel <even invisible ppl>

### Go into more detail...

so yeh we will have a whole data of who all are seeing the channel, server, dm group if downloaded

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
not possible
