### ISSUE TITLE
Show user info

### ISSUE THREAD

**Issue by zszushi** [Aliucord/plugin-requests#724]
### Discord Account

◣𝗓ₛ𝗓ᵤₛₕᵢ◢#349

### Plugin Description

(account age,server join day)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by WiBJDOGKINGZ** [comment]
Already a plugin 

UserDetails

**Comment by zszushi** [comment]
Ok,sorry
