### ISSUE TITLE
A Close Sam's button

### ISSUE THREAD

**Issue by CamjamPNG** [Aliucord/plugin-requests#725]
### Discord Account

Camjam#0001

### Plugin Description

Add the close dms button from PC to mobile

### Go into more detail...

Makes it so the close dms button will close a dm so it's no longer in the message log, just like how it is on pc

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
https://github.com/DiamondMiner88/aliucord-plugins/raw/builds/CloseDMs.zip
also hi cam
