### ISSUE TITLE
DeleteSpecificMessage from a message for a specfic amount

### ISSUE THREAD

**Issue by lvlahraam** [Aliucord/plugin-requests#726]
### Discord Account

Mahraam#5124

### Plugin Description

Okay so... In my opinion this could be a great plugin
This is same as like some clear/purge commands that bots have
This plugin should be a slash command that deletes messages and takes one message_id and amount
This plugin then should delete messages starting from THAT MESSAGE_ID and delete message for the given amount

If this is possible please mame it 🙏 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by lvlahraam** [comment]
This is just like a way to delete a lot of messages but you also want to keep some messages
And ngl, holding on the messages and clicking on the delete button and the confirm button is just annoying

**Comment by lvlahraam** [comment]
And by message i meant messages

**Comment by Juby210** [comment]
Use a moderation bot, automating user actions is selfbotting

**Comment by lvlahraam** [comment]
Way what?!....
