### ISSUE TITLE
Sort Discord Experiments from new to old

### ISSUE THREAD

**Issue by hairyfred** [Aliucord/plugin-requests#73]
### Discord Account

fred#9876

### Plugin Description

A plugin to allow sorting from new to old experiments in the developer settings

### Go into more detail...

Either just a button for different sorting methods or just sort from newest to oldest like on pc

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
Should be a part of the Experiments plugin instead of a separate plugin.
