### ISSUE TITLE
Custom badge global

### ISSUE THREAD

**Issue by hamzahyahya** [Aliucord/plugin-requests#732]
### Discord Account

Wokabi 108#3401

### Plugin Description

Is plugin like a custom badge but everyone (including official discord) can view it

### Go into more detail...

none

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
Okay give me 15 minutes I will hack into discords server and give you the badge
