### ISSUE TITLE
Read Messages

### ISSUE THREAD

**Issue by Salforddavid** [Aliucord/plugin-requests#736]
### Discord Account

Salford.David_#8660

### Plugin Description

I think a plugin where if someone opens your dms or looks at the message in any type of way itll maybe have a message that says ```read``` underneath your message would be cool because maybe your friends are ignoring you or something?

### Go into more detail...

I think it should give you a notification too because sometimes you don't check if they read in a different way im saying it should have the notification like the plugin ```notify when react```

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
Not possible

**Comment by ItzOnlyAnimal** [comment]
Possible if you like re creating the entire platform :trollface:

**Comment by ditt0132** [comment]
It will partially possible maybe (only when discord is open)
just add `read` when DM channel got typing indicator since they must read DM if they typed something
