### ISSUE TITLE
Rich croissants presence setter

### ISSUE THREAD

**Issue by thecprog** [Aliucord/plugin-requests#737]
### Discord Account

tcpr#9567

### Plugin Description

Now heat me out, i know rich presents isn't possible on mobile itself, but you can make a button to send command to a client on out network where it can be set. useful if im not at home and want to connect to my pc and set my rich prince or if im just on the toilet xD

### Go into more detail...

i dont think it needs more detail

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by thecprog** [comment]
anyone?

**Comment by zt64** [comment]
No rich croissants?

**Comment by thecprog** [comment]
Can you give me croissants
