### ISSUE TITLE
Increase scrollbar width

### ISSUE THREAD

**Issue by dmack6464** [Aliucord/plugin-requests#74]
### Discord Account

D Mack#4481

### Plugin Description

I sometimes have to use the scrollbar in order to scroll more quickly, some people, especially on certain Samsung phones, find it very difficult to grab the scrollbar with how wide it currently is.

### Go into more detail...

I know it may look kinda ugly, but it would be worth it for better usability.

(Perhaps a simpler alternative could be to remove the scroll speed limit!)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Litleck** [comment]
I'm gonna attempt this

**Comment by Litleck** [comment]
Took a while but I got it working. Unfortunately scaling also effects the height and I couldn't figure out a way to do just the width, it may be possible but for now I think it's fine. You can download it [here](https://github.com/litleck/aliucord-plugins/raw/builds/WiderScrollbar.zip).
