### ISSUE TITLE
Close All DMs Slash Command

### ISSUE THREAD

**Issue by Gankutsuou-Gank** [Aliucord/plugin-requests#741]
### Discord Account

Gankutsuou.Hx#3533

### Plugin Description

A slash command that closes all dms 

### Go into more detail...

Just like mark all guilds as read plugin but it closes all dms

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by saintwithataint** [comment]
This will probably be a self bot
