### ISSUE TITLE
Game detection Service for all Androids

### ISSUE THREAD

**Issue by AyeItsAzhan** [Aliucord/plugin-requests#744]
### Discord Account

𝔸𝕫𝕙𝕒𝕟#5360

### Plugin Description

After the discord update only samsung smartphones display what game you are playing as status and other androids dont display is there a possible way to make all androids show what they are playing in status just like pc that would be really cool

### Go into more detail...

before the discord 7.9.9 update there used to be detection service on all androids but now its gone and that time it didn't used to display the picture of the app and after 3 or 4 mins detection service would stop working well the picture part isnt necessary but i hope the plugin doesn't stop working after 3-4mins

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Moooodle** [comment]
im pretty sure I made a request similar to this already but sounds nice to have

**Comment by rushiiMachine** [comment]
not possible as discord does not run in the background
