### ISSUE TITLE
Role Icon Plugin

### ISSUE THREAD

**Issue by DerNinJory** [Aliucord/plugin-requests#747]
### Plugin Description

A plugin with which you can set a custom role icon via mobile phone.

### Go into more detail...

So that in the role settings if you have a level 2 server, that you can also set role icons via app and not always via Chrome or something!

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Muatex** [comment]
+1 im not always on pc and when i am i always forget to switch role icons to what i wanted

**Comment by jedenastka** [comment]
Duplicate of #627.
