### ISSUE TITLE
Playable mp3 files

### ISSUE THREAD

**Issue by GhostFaceKnight** [Aliucord/plugin-requests#753]
### Discord Account

جيGhostfaceknight#2314

### Plugin Description

I think if you guys could make a plugin that allows us to play mp3s like in WhatsApp

### Go into more detail...

I maybe you could even add a mic recorder that auto sends an mp3 of what it recorded but idk if that one's practically or easy

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
#105 #143 #319 #494 #415 #607 #709
"I did indeed check to make sure my plugin request is original!"
I think this is a new record

**Comment by hairyfred** [comment]
> lolol bro read half the thing and called it a duplicate bro I added extra features and more detail the other guy just wanted to not leave aliucord I asked for a WhatsApp type with microphone direct to mp3 but whatever

Then why not comment your suggestions on the original post

And the record microphone feature could of been a seperate request
