### ISSUE TITLE
Dnd options 

### ISSUE THREAD

**Issue by Salforddavid** [Aliucord/plugin-requests#757]
### Discord Account

⃟⃝#8660

### Plugin Description

My idea was if u have ur status on dnd u can choose an option on people u do receive notifications  from

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
#371 
Please check for duplicates
