### ISSUE TITLE
Custom status

### ISSUE THREAD

**Issue by Salforddavid** [Aliucord/plugin-requests#758]
### Discord Account

⃟⃝#8660

### Plugin Description

Sorry for making alot suggestions but so like when your playing roblox for an example it'll make your custom status and then when someone clicks on ur profile it has a picture ```playing () for (how lonng)``` but you could make your custom game status if possible

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
Normally I list every duplicate request
But I'm tired
