### ISSUE TITLE
A plugin that allow us to send one of your installed plugin using slash command 

### ISSUE THREAD

**Issue by Lightning-playZ** [Aliucord/plugin-requests#759]
### Discord Account

𝗗 𝗘 𝗩 𝗜 𝗟#4604 

### Plugin Description

A plugin that helps to send one of your installed plugin using slash command like '/send-plugin plugin-name' so it's easy to send someone plugin instead of going to file manager and sending through it.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
If anything this should send the github link instead. You should never install plugin zips someone else sends you as that is comparable to running an .exe and dangerous

**Comment by Lightning-playZ** [comment]
Yeah that's also right and that's even better

**Comment by rushiiMachine** [comment]
security risk either way
