### ISSUE TITLE
Sticker Spoof

### ISSUE THREAD

**Issue by RGBCube** [Aliucord/plugin-requests#76]
### Discord Account

Studio#4777

### Plugin Description

NitroSpoof but for stickers!

also maybe an option to add your own sticker links (cdn) 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
It should be a part of NitroSpoof, because it's named ***Nitro***Spoof

**Comment by RGBCube** [comment]
yus

**Comment by Vendicated** [comment]
Did not mean to press that button 😅 

As of now this would be an extremly hard challenge, so it's probably more viable to simply send gifs.

(Animated) stickers are either apngs, which would somehow have to be converted to gifs first, or worse yet lotties, which would have to be rendered to a gif using a hacky method (see <https://github.com/airbnb/lottie-android/issues/731>) with discords heavily obfuscated com.airbnb.lottie.
