### ISSUE TITLE
Modify speed of client animations

### ISSUE THREAD

**Issue by cloudwithax** [Aliucord/plugin-requests#762]
### Discord Account

Clxud#6951

### Plugin Description

This plugin would allow the user to customize the timing for all client animations (i.e: the amount of time it takes to open the server list, channel, etc). You can adjust these settings either using a slider or fine tune using decimal amounts.

### Go into more detail...

It would be nice if there was a way to change how the animation looks altogether (i.e: you can change it to be a fade rather than a slide in, etc.) 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
This is configurable via Android System Developer Options
