### ISSUE TITLE
Pfp & banner downloader

### ISSUE THREAD

**Issue by Salforddavid** [Aliucord/plugin-requests#763]
### Discord Account

Salford.David_#8660

### Plugin Description

So this idea was took from bluecord so when you click on a pfp it gives you the full picture maybe if you do that with pfp and banner

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
Exists, the bluecord feature is literally a blatant copy of the plugin. ViewProfileImages
