### ISSUE TITLE
See who is viewing the current channel

### ISSUE THREAD

**Issue by Kxsumi** [Aliucord/plugin-requests#764]
### Discord Account

Twix?#9960

### Plugin Description

Similar to the "see a list of who's currently typing" plugin, is there a way to see who exactly is viewing your current channel or the amount of people viewing the channel without them typing?

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
Not possible
