### ISSUE TITLE
Triple tap to delete ur own messages

### ISSUE THREAD

**Issue by Jackiedsmemer** [Aliucord/plugin-requests#765]
### Plugin Description

Mobile plugin that when yoi  tap on ur own message 3 times it deletes it

### Go into more detail...

Do i need to explain lol

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
duplicate of #2 & #287

**Comment by OmegaSunkey** [comment]
well... similar to them
