### ISSUE TITLE
Fake bot verification

### ISSUE THREAD

**Issue by Jackiedsmemer** [Aliucord/plugin-requests#766]
### Plugin Description

a local effect that gives any bot(unverified) a verification check

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by WiBJDOGKINGZ** [comment]
You can do this already using the UserTags plugin.

It won't let you change the word bot but it will let you add a check.
