### ISSUE TITLE
Tinder

### ISSUE THREAD

**Issue by monkeyfoxture** [Aliucord/plugin-requests#769]
### Discord Account

Sexceo#2000

### Plugin Description

Shows profiles 'hook up' instead of the call button, which send a friend request and opens messages tab, now the list begins.

### Go into more detail...

Sex...?

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by taskylizard** [comment]
> Go into more detail...
Sex...?

are you ok

**Comment by monkeyfoxture** [comment]
Nope, am mentally insane from watching ven and fred flirt

**Comment by taskylizard** [comment]
ven will be mine soon

**Comment by JonathanSwatz10** [comment]
I don't think that's allowed but maybe?
