### ISSUE TITLE
Loop/Timed Messages

### ISSUE THREAD

**Issue by Ushie** [Aliucord/plugin-requests#77]
### Discord Account

Ushie#7739

### Plugin Description

Creates a timed message loop, sends the certain messages everytime the set time has passed.

### Go into more detail...

This feature would be pretty useful in a large amount of cases, but there should be some limitations like minimum amount of time between messages and a limited amount of channels in a server to avoid misuse of this command :)) 

For example:-
/setloop 1d "[Message]"

> Be able to create loops (obviously).

> The ability to delete existing loops, or putting them on hold.

> A loop list command to show all the current existing loops.

> Ability to have multiple loops running at the same time.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
This would not only be selfbotting, it would also be nearly impossible to implement as Aliucord has to be running for a plugin to operate
