### ISSUE TITLE
Insult command

### ISSUE THREAD

**Issue by DeltaHaust** [Aliucord/plugin-requests#770]
### Plugin Description

A /insult command that uses api like https://insult.mattbas.org/api/insult or some other api, idk whichever has the best insults

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
Completed
<https://github.com/DiamondMiner88/aliucord-plugins/raw/builds/Insult.zip>
