### ISSUE TITLE
Keyword alert suggestion

### ISSUE THREAD

**Issue by Jackiedsmemer** [Aliucord/plugin-requests#774]
### Plugin Description

Another small button "case insensitive" so you can highlight one word and it won't be case sensitive
Like you can say HEy and it will still highlight

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
do you people read

**Comment by Jackiedsmemer** [comment]
> do you people read

Yes'nt

**Comment by OmegaSunkey** [comment]
request it in wing's repo
