### ISSUE TITLE
Mutual server count badge

### ISSUE THREAD

**Issue by rafalohaki** [Aliucord/plugin-requests#775]
### Discord Account

Autarch#7555

### Plugin Description

Mutual server count badge:
Badge with number of mutual servers shown in nickname
![image](https://user-images.githubusercontent.com/20607107/162624796-fc4855ed-545f-42cb-9944-bd5a4fe01ba0.png)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
Not possible without insane api spam, also pretty useless, just open their profile and check

**Comment by rafalohaki** [comment]
kk
