### ISSUE TITLE
Server Profiles

### ISSUE THREAD

**Issue by Wolfkid200444** [Aliucord/plugin-requests#78]
### Discord Account

Wolfie#4444 

### Plugin Description

So Currently discord gives some what of info when clicking on the guild tab u get the online members and total members but i was thinking why not add like more detail like if the guild has vanity url or not, maybe like mutual friend list.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by wingio** [comment]
Ill take this

**Comment by wingio** [comment]
Done
https://github.com/wingio/plugins/blob/builds/GuildProfiles.zip?raw=true
