### ISSUE TITLE
Rickroll detector

### ISSUE THREAD

**Issue by Jackiedsmemer** [Aliucord/plugin-requests#780]
### Plugin Description

Scan websites for rickroll, scan sent youtube links for rickroll scan spoiled(|) messages for rickroll

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Jackiedsmemer** [comment]
> ### Discord Account
> _No response_
> 
> ### Plugin Description
> Scan websites for rickroll, scan sent youtube links for rickroll scan spoiled(|) messages for rickroll
> 
> ### Go into more detail...
> _No response_
> 
> ### Request Agreement
> * [x]  I have made sure my plugin is possible and abides by the rules!
> 
> ### ​
> * [x]  I did indeed check to make sure my plugin request is original!

Also scan files for rickroll

**Comment by DiamondMiner88** [comment]
- websites: extremely easy way to ip log yourself
- youtube: doable only if something like "rickroll" is in video metadata
- files: not possible

**Comment by JonathanSwatz10** [comment]
Stupid stuff.
