### ISSUE TITLE
Platform indicators

### ISSUE THREAD

**Issue by gachalife1** [Aliucord/plugin-requests#784]
### Discord Account

$ghlc#1000

### Plugin Description

platform indicator, a badge thing that shows whether they're on pc, mobile or browser, i was hoping you could add this 

### Go into more detail...

And if it doesn't fit in chat/dm list or the user list in the server please try atleast to make it small. I would really appreciate this!

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by C10udburst** [comment]
I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Already exists, https://github.com/Juby210/Aliucord-plugins/raw/builds/BetterStatusIndicators.zip
