### ISSUE TITLE
Read Receipts

### ISSUE THREAD

**Issue by Kim-Taehyung-7** [Aliucord/plugin-requests#786]
### Discord Account

Jeon#0124

### Plugin Description

This has been rejected with "not possible" on other suggestions, maybe make it so it only works for people with the plugin? like if I read the message with normal discord the other person can't see if I've read their message. but if I open aliucord and have the plugin turned on, they can.

### Go into more detail...

dms:
> have `Read` under your last message if the user has read your message.

servers and groupchats:
> if any message has only been read by one person, then have a `Read by **@user**` under that message, and clicking it would open the profile of the user. if the message was read by 2+ people, then something like `Read by **2 people**`, and clicking that would open a list of people who've read it.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
DB for the 3 people that will use this plugin :trollface:

**Comment by ItzOnlyAnimal** [comment]
i mean i guess but yeah :trollface:

**Comment by Vendicated** [comment]
if you want read receipts then use WhatsApp or something like that
