### ISSUE TITLE
A way to change the discord call ringtone 

### ISSUE THREAD

**Issue by rickdtc** [Aliucord/plugin-requests#80]
### Discord Account

PUTDEMKNOCK#2006

### Plugin Description

A plugin that allows users to change discord call ringtone to a audio of their choice.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
Now part of themer thanks to @terabyte25 

https://user-images.githubusercontent.com/45497981/141374780-3f0aa151-ffdd-48df-9d82-75f2a2235184.mp4

**Comment by rickdtc** [comment]
Let's goo
