### ISSUE TITLE
No Bye

### ISSUE THREAD

**Issue by doggieblankie** [Aliucord/plugin-requests#807]
### Discord Account

Discord#0001

### Plugin Description

@
@ItzOnlyAnimal @hairyfred @Juby210 @Juby210 @zt64 @zt64 fuck

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
why im not in this
