### ISSUE TITLE
Change or remove guild folder opacity

### ISSUE THREAD

**Issue by dmack6464** [Aliucord/plugin-requests#81]
### Discord Account

D Mack#4481

### Plugin Description

By default, Discord forces a default opacity value for guild folder background colours.

### Go into more detail...

I want an option to modify, or even remove the opacity value for said background colours, leaving the colour completely solid.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Working on it

**Comment by zt64** [comment]
Done, https://github.com/zt64/aliucord-plugins/raw/builds/FolderOpacity.zip
