### ISSUE TITLE
Message translation plugin

### ISSUE THREAD

**Issue by Hades785** [Aliucord/plugin-requests#82]
### Discord Account

On behalf of xPandaku#0001

### Plugin Description

**Core:** Lets one translate a message from one language to another language.

**Potential:** Could also let one translate their inputted text from one language to another language before sending a message.

### Go into more detail...

**Core:** Context menu button on messages to try and translate them using a third party service. 
Source language could be guessed, configured or chosen on the fly (when doing the action).
Target language could be taken from app or system language, configured or chosen on the fly (when doing the action).

**Potential:** When writing a message, have a button dedicated to translation.
Source language could be guessed, taken from app or system language, configured or chosen on the fly (when doing the action).
Target language could be configured or chosen on the fly (when doing the action).

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Hades785** [comment]
There was apparently one being made by ChaosTheory#8268, but they are inactive.

**Comment by TymanWasTaken** [comment]
Done https://github.com/TymanWasTaken/aliucord-plugins/blob/builds/Translate.zip
