### ISSUE TITLE
pinDMs

### ISSUE THREAD

**Issue by lolpowerluke** [Aliucord/plugin-requests#84]
### Discord Account

lolpowerluke#5364

### Plugin Description

Allows you to pin DMs, making them appear at the top of your DMs/ServerList

### Go into more detail...

the pinDMs plugin from betterdiscord made for aliucord

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by MulverineX** [comment]
https://github.com/powercord-community/betterfriends

**Comment by WinstonSepruko** [comment]
Duplicate of #35
