### ISSUE TITLE
Always Show Offline

### ISSUE THREAD

**Issue by vankiller-n** [Aliucord/plugin-requests#847]
### Discord Account

VanKiller#6087

### Plugin Description

Always show offline members in the memberlist, even if the server has over 1k members. Good for locked channels.

### Go into more detail...

Another specific needs request but idk I love Aliucord and hope my suggestions are fucking useful
Have a good day.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
api aboose
