### ISSUE TITLE
Force custom font

### ISSUE THREAD

**Issue by GangsterFox** [Aliucord/plugin-requests#85]
### Discord Account

Fox#0004

### Plugin Description

A plugin which allows you to force discord to use systems font since discord doesnt allow you to use a custom font. 

### Go into more detail...

Easy to explain, just a plugin which tells discord to use systems font and not its own font since it looks like trash.
Maybe you could make it more complicated and make a full on folder where you can put your ttf files and via the plugin settings change the font but I think that would be too much, what I really need is just to make discord use systems font.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
https://github.com/Aliucord/plugin-requests/issues/63
