### ISSUE TITLE
Mark all mentions as seen 

### ISSUE THREAD

**Issue by BRY4NZIN** [Aliucord/plugin-requests#851]
### Discord Account

BRYAN 🤝🏻#7042

### Plugin Description

imagine tagging all your mentions with a simple button 

### Go into more detail...

Preferably have two buttons one to mark the mentions of servers and others of dm

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
exists, but only for guilds
insert all servers in a folder
hold folder
click mark as read
profit
