### ISSUE TITLE
Channel pin

### ISSUE THREAD

**Issue by Videry** [Aliucord/plugin-requests#853]
### Discord Account

NotVidery#4832

### Plugin Description

Basically a plugins that makes some channels that you pin more easy to find

### Go into more detail...

Basically long click in channel click on the new button pin and it'll show a pin logo before the channel's name and when going to server option and clicking on a list to find all pinned channels

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by FeroshUX** [comment]
That's called the Quick Switcher, and it's probably more convenient for the details you gave.

**Comment by ItzOnlyAnimal** [comment]
https://discord.com/channels/@favorites coming soon to a mobile near you :trollface: :trollface: :trollface:

**Comment by Videry** [comment]
Ok, cuz i get lost sometimes but I'm on mobile

**Comment by rushiiMachine** [comment]
favorites
