### ISSUE TITLE
Replace discord twemoji with system emoji or custom emoji

### ISSUE THREAD

**Issue by Nexxol** [Aliucord/plugin-requests#854]
### Plugin Description

Twemojis are horrible, I think there should be a plugin that either: replaces them with our be system emojis or allows us to select an emoji to replace the twemojis

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Dungeonscats** [comment]
Not valid 😢
