### ISSUE TITLE
Emojis look plugin

### ISSUE THREAD

**Issue by xero-cmd** [Aliucord/plugin-requests#856]
### Discord Account

Xero#2121

### Plugin Description

I would like a plugin to see my phone stock emojis instead of discord emojis, just me, not everyone else.

### Go into more detail...

Since discord emojis are kinda... Ugh, i would like to have my stock emojis.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
> I did indeed check to make sure my plugin request is original!
