### ISSUE TITLE
Download/copy link of guild/profile picture

### ISSUE THREAD

**Issue by KaKi87** [Aliucord/plugin-requests#86]

**Comment by Juby210** [comment]
1. Your issue doesn't follow our template
2. This plugin already exists as **ViewProfileImages**

https://github.com/Vendicated/AliucordPlugins/blob/builds/ViewProfileImages.zip?raw=true

![preview](https://github.com/Vendicated/AliucordPlugins/blob/main/ViewProfileImages/demo.gif?raw=true)
