### ISSUE TITLE
Profile through embed ping

### ISSUE THREAD

**Issue by Lightning-playZ** [Aliucord/plugin-requests#878]
### Discord Account

𝗗 𝗘 𝗩 𝗜 𝗟#4604 

### Plugin Description

A plugin that let you open profile of the person when we click on the person that is pinged in the embed usually we can't open profile and that's kinda annoying seperately pinging to open his profile 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Already exists: https://github.com/DiamondMiner88/aliucord-plugins/raw/builds/ClickableMentions.zip
