### ISSUE TITLE
Colors 

### ISSUE THREAD

**Issue by Therealloli101** [Aliucord/plugin-requests#879]
### Discord Account

Cookiesツ#1721 

### Plugin Description

A plugin wich will make hex codes in chat appear in their respective color 

### Go into more detail...

It should make every hex code appear in their respective color, a example for a use would be if you have a server and everyone who boosts gets a own role with color and they send you the hex code you will be able to see giw it would look 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by wingio** [comment]
Added in MoreHighlite v1.2.0 https://github.com/wingio/plugins/blob/builds/MoreHighlight.zip?raw=true

**Comment by catnamedmina** [comment]
It's over now delete it now.
