### ISSUE TITLE
ShowNames

### ISSUE THREAD

**Issue by Tharki-God** [Aliucord/plugin-requests#880]
### Discord Account

LoneWeebAhlawat#0480

### Plugin Description

A plugin that changes the color of usernames to stop them from blending into the background. It will make colors lighter if they match close to your theme's background color (in discord settings). Like some shades close.

### Go into more detail...

[yeah someone did tried to make it before.](https://github.com/TymanWasTaken/aliucord-plugins/raw/builds/ShowNames.zip)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Tharki-God** [comment]
would be great if can you can make it for bd too. i have the same problem on pc too sadly. XD

**Comment by Tharki-God** [comment]
Made it for better discord myself. Port it if you can. BTW this is the plugin: [ShowNames.plugin.js](https://github.com/Tharki-God/BetterDiscordPlugins/blob/master/ShowNames.plugin.js). The name ain't copyrighted right? LOL

**Comment by DiamondMiner88** [comment]
this is already a plugin from last year
https://github.com/TymanWasTaken/aliucord-plugins/blob/builds/ShowNames.zip?raw=true

**Comment by Tharki-God** [comment]
> this is already a plugin from last year
> https://github.com/TymanWasTaken/aliucord-plugins/blob/builds/ShowNames.zip?raw=true

I thought you would know it better. Its an unmaintained plugin which don't work and idk java

**Comment by Tharki-God** [comment]
Now open the request again

**Comment by Tharki-God** [comment]
Eyo, who gonna change the labels?

**Comment by Tharki-God** [comment]
Good boy

**Comment by TymanWasTaken** [comment]
For anyone stumbling across this nowadays (and for the author of this issue I suppose), I have made an improved ShowNames: https://github.com/TymanWasTaken/aliucord-plugins/raw/builds/RoleColorContrast.zip

**Comment by Yes-shua** [comment]
A plugin that when you type "/jj 1-10" or "/jj 4-30" - and others - sends the transcribed numbers ‐ one at a time - in full, in capital letters, with a space and exclamation mark, eg: 
ONE !
wait 0.6 seconds and send
TWO !
wait 0.6 seconds and send
THREE !
wait 0.6 seconds and send
...
and with support to language "portuguese brasil", e.g:
UM !
wait 0.6 seconds and send
DOIS !
wait 0.6 seconds and send
TRÊS !
...

I need this for something I'm doing on discord, although very specific - I think few or no one other than me will use it - I made the code and all the necessary files, however, compiling for dex is the problem...
