### ISSUE TITLE
Invite to listen

### ISSUE THREAD

**Issue by JBugelLOL** [Aliucord/plugin-requests#882]
### Discord Account

JBUGΞL#0812

### Plugin Description

Like on the desktop version!
it makes the invite and you should also get the chance to join such invites

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
This should be a request to [BetterSpotify](https://github.com/Vendicated/AliucordPlugins/tree/main/BetterSpotify) plugin
