### ISSUE TITLE
change save location

### ISSUE THREAD

**Issue by ghost** [Aliucord/plugin-requests#884]
### Discord Account

SexyYoda#1368

### Plugin Description

change the location downloads are saved to(images/videos/gifs/etc..)

### Request Agreement

- [x] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment]
As mentioned in #1097 (duplicate), [ChangeDownloadPath](https://gitlab.com/Grzesiek11/changedownloadpath-aliucord-plugin) is now available.
