### ISSUE TITLE
2 taps on send button to send a message

### ISSUE THREAD

**Issue by Likver** [Aliucord/plugin-requests#888]
### Plugin Description

ngl didnt search if this was alr requested but i think it would be good for ppl like me who the keyboard is small asf for their fingers (bcs of the phone screen) and usually type everything wrong lel

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
![piss](https://user-images.githubusercontent.com/70033559/165340583-954edb09-8adf-462a-b58f-bc36e63a9be3.jpg)

**Comment by JonathanSwatz10** [comment]
Sorry that's duplicate.
