### ISSUE TITLE
Full Support for Server Profiles on Mobile

### ISSUE THREAD

**Issue by Cinthinya** [Aliucord/plugin-requests#897]
### Discord Account

Nyacinth#0001

### Plugin Description

A plugin that allows full server profile editing; particularly the banner and bio(/about me).

### Go into more detail...

Currently (at least for me), mobile doesn't support full server profile editing. It used to, I don't know _what_ happened to it, but one day it was just gone. Now I have to go into the browser app which sucks on mobile and edit it there; which I also have a huge bug with the bio which replicates my last word like fifty times if I try making one. It's a hassle. (I'm not sure if other people have this issue though?)

It doesn't have to work exactly like the app did it beforehand, I dunno how hard some of the stuff is to code per se, like cropping an image banner or something.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment]
pretty sure its there just behind an experiment 

also dont expect them to add it fully to the native android version because it will never happen

**Comment by Cinthinya** [comment]
Should I ask how to get the experimental version here or like, in a support channel in the Discord somewhere?

**Comment by ItzOnlyAnimal** [comment]
just install the [Experiments plugin](https://github.com/Juby210/Aliucord-plugins/raw/builds/Experiments.zip)
and look for guild member profiel something along those lines
https://discord.com/channels/811255666990907402/811275162715553823/835554229484519484

**Comment by Cinthinya** [comment]
Yep, that worked. Thanks!
