### ISSUE TITLE
Hcaptha Solver 

### ISSUE THREAD

**Issue by Burstsam** [Aliucord/plugin-requests#898]
### Discord Account

Not here  

### Plugin Description

Please make a hcaptha solver plugin. I have to solve a hcaptha everytime i dm someone .

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
skill issue

**Comment by owovin** [comment]
is this you

https://user-images.githubusercontent.com/26679713/165578452-7781643b-6fe2-4746-b0a5-48c56aa5bbc3.mp4

**Comment by Tharki-God** [comment]
That's me

**Comment by Burstsam** [comment]
gg
