### ISSUE TITLE
Soft-block

### ISSUE THREAD

**Issue by funlennysub** [Aliucord/plugin-requests#9]
### Description
Plugin that allows you to soft-block specific user

### More info
Soft-blocked user will be able to do anything they could while not being blocked just all their messages will be marked as blocked. If possible make "block user" button have 2 options "default block" and "soft-block". And if it'll not get you banned auto-read dms from those users 🤔

---

- [x] I checked if this plugin wasn't already requested.

**Comment by vy-storm** [comment]
Kinda like shadow ban, I could see this being useful!

**Comment by ikeman2003** [comment]
I know this is an old thread but i would really like to see this happen i was able to dig up something that does this exact thing but for Better Discord which does mean that it is possible i dont know .dex formatting to do it though 

https://github.com/ikeman2003/BDAddons

**Comment by phanglette** [comment]
Okay this thread is old as hecc but another feature of soft block can also apply with the options of not seeing the user's: Pfp, description and status. If possible, your status can be invisible to them but in to users who are not soft blocked: they can see if you're idle, online etc. 

**OR**

It can work on the reverse end. And the soft blocked person won't be able to see your pfp, status or description.

**Comment by ItzOnlyAnimal** [comment]
server side changes aka tell discord to do it not us

**Comment by rushiiMachine** [comment]
just use regular block + not possible as push notifs would still go through
