### ISSUE TITLE
Remove width limit of the ping counter

### ISSUE THREAD

**Issue by abUwUser** [Aliucord/plugin-requests#90]
### Discord Account

A user#8169

### Plugin Description

The drawer button have a width limit on the counter, hiding some numbers depending of the length. My suggestion is to remove that limit.

![](https://user-images.githubusercontent.com/27961224/125488081-52312a31-a5ce-4c8e-b7ff-11811fe3cce4.jpg)

### Go into more detail...

There is also the individual server ping counter. This ond is actually length limited, so it actually hides numbers, replacing them with the `...`. It would also be cool to remove that limit.

![](https://user-images.githubusercontent.com/27961224/125489250-d75e94d1-bba7-4744-a5b4-2dc4be2f99e5.jpg)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Litleck** [comment]
Two ideas I have for this is either the number overflows the indicator or the text shrinks to fit inside of it

**Comment by abUwUser** [comment]
couldn't the wrapper just increase the height automatically!

**Comment by DiamondMiner88** [comment]
done: <https://github.com/DiamondMiner88/aliucord-plugins#nopingwidthlimit>
