### ISSUE TITLE
Message logger v2

### ISSUE THREAD

**Issue by Tharki-God** [Aliucord/plugin-requests#905]
### Discord Account

LoneWeebAllah@0480

### Plugin Description

Well I know message logger is already there but caches the messages. Can you make it so it download delete media and keep test saved in file. Idc about storage just let it do it. Same as message logger v2 in desktop 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

**Comment by taskylizard** [comment]
no

**Comment by ItzOnlyAnimal** [comment]
you will be patient and wait for all plugins to be rewritten :trollface:

**Comment by OmegaSunkey** [comment]
this is an obvious repetition

**Comment by Tharki-God** [comment]
do i care lol, thx for telling 🗡️

**Comment by catnamedmina** [comment]
bye bye fuckers
