### ISSUE TITLE
Select multiple messages at once

### ISSUE THREAD

**Issue by WiBJDOGKINGZ** [Aliucord/plugin-requests#908]
### Discord Account

WiB JDOG KINGZ#9000

### Plugin Description

A way to select multiple messages at once so you can delete them faster.

### Go into more detail...

I think it should work by holding down a message. Then have a button that says select messages and when pressed every message you press after highlights and when you're done selecting hold down any of the selected messages and have a button that says delete selected messages.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Deleting multiple messages at once would be selfbot behavior
