### ISSUE TITLE
Corner fixes

### ISSUE THREAD

**Issue by Diwang2001** [Aliucord/plugin-requests#909]
### Discord Account

Shoyou Hinata#5748

### Plugin Description

Whenever we use a theme all server's icons's corners changes into grey instead of transparent and it kills the vibe of any theme. I guess it should be fixed.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
You will request on Vens plugins repo
