### ISSUE TITLE
Custom background plugin

### ISSUE THREAD

**Issue by Spleens1** [Aliucord/plugin-requests#91]
### Discord Account

Spleens.exe#0002

### Plugin Description

This plugin would give you the ability to set a custom chat background without having to root your system

### Go into more detail...

I don't know if it is possible but the plugin should also be able to "see" when a image has the same color has the text so therefore it adds a bit of contrast to either the text or rejects the picture.
I think it would be a good thing to be able to change the boring chat background like on PC with BetterDiscord

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by WinstonSepruko** [comment]
Closed. Duplicate of #21.
