### ISSUE TITLE
Login As Bot On App

### ISSUE THREAD

**Issue by catnamedmina** [Aliucord/plugin-requests#910]
### Discord Account

Loggger#9148

### Plugin Description

I don't know if it's possible but will see.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Not possible

**Comment by catnamedmina** [comment]
Ok fuck you then
