### ISSUE TITLE
Make USRBG compatible for Aliucord

### ISSUE THREAD

**Issue by MatadorProBr** [Aliucord/plugin-requests#93]
### Discord Account

```Matador#0069```

### Plugin Description

A plugin that allows you to use the banners of Discord for free without nitro! Same as [USRBG](https://github.com/Discord-Custom-Covers/usrbg) BetterDiscord version, using the [GitHub Database](https://github.com/Discord-Custom-Covers/usrbg/blob/master/dist/usrbg.json).

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by WinstonSepruko** [comment]
Plugin already exists [here.](https://github.com/aa-aliucord/plugins) It is however, broken.

**Comment by Reinified** [comment]
plugin exists now, https://discord.com/channels/811255666990907402/845784407846813696/888162638612279297
