### ISSUE TITLE
Compact Mode

### ISSUE THREAD

**Issue by hyblocker** [Aliucord/plugin-requests#94]
### Plugin Description

Compact mode on mobile

### Go into more detail...

Self explanatory, compact mode from desktop but its on mobile

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Veis2015** [comment]
I'll try to do this

**Comment by hjroh0315** [comment]
actually you know what
this might just work with
1. remove pfp
2. remove a few margins in layout

**Comment by zt64** [comment]
Working on it now

**Comment by zt64** [comment]
Finished it, https://github.com/zt64/aliucord-plugins/raw/builds/CompactMode.zip

**Comment by Vendicated** [comment]
<img src="https://cdn.discordapp.com/emojis/896378284005289984.gif" height="44" width="44">

**Comment by ItzOnlyAnimal** [comment]
<img src="https://cdn.discordapp.com/emojis/896378284005289984.gif" height="44" width="44">
