### ISSUE TITLE
Role Badge

### ISSUE THREAD

**Issue by hjroh0315** [Aliucord/plugin-requests#95]
### Discord Account

CrO4 2-#0010

### Plugin Description

Appends highest role to name (after the customnicknameformat plugin)
better if configurable on whether it should display the top role of all or top role with color

Ex.
Fox  ->  Fox (theme developer)
Juby210    ->   Juby210 (dev)
fake rose (real swish) (Swishilicious#3200) -> fake rose (real swish) (Swishilicious#3200) (contributor)

### Go into more detail...

probably expansion of https://github.com/Aliucord/plugin-requests/issues/19#issue-905506752

### Request Agreement

- [x] I did indeed check to make sure my plugin request is original!

**Comment by DiamondMiner88** [comment]
I'm claiming this

**Comment by Vendicated** [comment]
would be cool if you made this some bubble that has the role colour as background colour (and white or black for text, should be dynamic based on the role colour so its readable no matter the colour)

**Comment by DiamondMiner88** [comment]
I give up, couldn't make the constraint layout work :skull:

**Comment by C10udburst** [comment]
added as a setting to [MoreTags](https://github.com/c10udburst-discord/aliucord-plugins/raw/builds/MoreTags.zip)
