### ISSUE TITLE
Translator plugin

### ISSUE THREAD

**Issue by Anarchydr** [Aliucord/plugin-requests#96]
### Discord Account

Anarchydr#0001

### Plugin Description

The plugin would basically translate messages to English, holding the message would open the menu as usual but there would be a "Translate" option. 

### Go into more detail...

It would use auto detect so it could translate every language

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Me-dot-exe** [comment]
why did you close this?

**Comment by keanuplayz** [comment]
Because it's a duplicate.

**Comment by fym35** [comment]
lol
