### ISSUE TITLE
Implement Code block Highlighting

### ISSUE THREAD

**Issue by TheRealGeoDash2019** [Aliucord/plugin-requests#98]
### Discord Account

TheRealGeoDash#1337

### Plugin Description

Basically the Plugin would bring the code blocks color instead of a grey color as default by mobile discord clients

### Go into more detail...

If possible to give them color. The user should have the ability to toggle if they want to have color on them or not

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hjroh0315** [comment]
proper title: Implement Code block highlighting

**Comment by luphoria** [comment]
this is now natively in Discord's mobile client
