### ISSUE TITLE
EditUserLocally

### ISSUE THREAD

**Issue by Imbwbl** [Aliucord/plugin-requests#981]
### Discord Account

bwbl#1284

### Plugin Description

Like EditServerLocally but you can modify your pp (with gif) your banner your name .....

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
We cant modify your body, sorry.

**Comment by OmegaSunkey** [comment]
(without jokes, this is duplicated lmao)
