### ISSUE TITLE
MessageLoggerV2

### ISSUE THREAD

**Issue by github59173** [Aliucord/plugin-requests#982]
### Discord Account

User580780456#1564

### Plugin Description

A message logger just like the one provided in the detailed part of this post.

### Go into more detail...

I saw that an attempt at a message logger was made in the  plugins list but it was a Beta/WIP. To give a better experience and overall better message logger I have provide the example of a well know message logger for betterdiscord which works very well. https://github.com/1Lighty/BetterDiscordPlugins/blob/master/Plugins/MessageLoggerV2/MessageLoggerV2.plugin.js

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
this is a duplicate request
