### ISSUE TITLE
Nitro spoof extended (is not so generical)

### ISSUE THREAD

**Issue by JeffKineiDOGE** [Aliucord/plugin-requests#983]
### Discord Account

Muteplayer#5659

### Plugin Description

Just a normal emoji nitro spoof but it checks if NQN are on actual server and the server form emoji u are picking, if yes besides you send a emoji link u send emoji code.

### Go into more detail...

I also want plugin check if you can send links on channel else (if nqn is not on server) emojis needs nitro get grayscaled, plugin check if you can send external emojis on channel and get grayscale if you can't send if nqn or links.
The plugin always will prefer nqn by default but you can change this on settings, on settings you will can change emoji link size.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by OmegaSunkey** [comment]
nitrospoof4nqn exists

**Comment by OmegaSunkey** [comment]
anyway nitrospoof is deprecated like months ago so nobody wants to add more features to it
