### ISSUE TITLE
GoogleSearch

### ISSUE THREAD

**Issue by danixx16** [Aliucord/plugin-requests#984]
### Discord Account

ダニイ#3830

### Plugin Description

A command to search Google quickly from discord uwu btw ily ven

### Go into more detail...

/search `query:[text]`

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jackmthws** [comment]
I made this for Enmity, will do it for Aliucord once AliucordRN is out

**Comment by rushiiMachine** [comment]
kind of like opening a web browser?
