### ISSUE TITLE
Text bubbles

### ISSUE THREAD

**Issue by qwerty9537** [Aliucord/plugin-requests#987]
### Discord Account

qwert#8769

### Plugin Description

I think a plugin that added text bubbles like telegram would be cool, for contrast and stuff 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Not possible without manifest modification, which can't be done through a plugin
