### ISSUE TITLE
[REUQEST] The ability to play audio files on discord

### ISSUE THREAD

**Issue by amazingdoggo** [Aliucord/plugin-requests#989]
### Plugin Description

you can only do it on the computer

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
I feel like the nations of the world guy
#105
#143 
#319
#415
#494
#607
#709
#753
"I did indeed check to make sure my plugin request is original!" - Sun Tzu, The Art f War
