### ISSUE TITLE
Command To List Plugins

### ISSUE THREAD

**Issue by hairyfred** [Aliucord/plugin-requests#99]
### Discord Account

hairyfred#9876

### Plugin Description

A command to list all your plugins, this could be useful to help people debug quicker.
Could even be part of Aliucord instead of a plugin

### Go into more detail...

It could also list the Aliucord Version , The Discord Version its based on and the plugin version

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
Added with https://github.com/Aliucord/Aliucord/commit/548251387887462605c7fc1fa8964cb60db2c8ed
