### ISSUE TITLE
Server hider

### ISSUE THREAD

**Issue by isahooman** [Aliucord/plugin-requests#991]
### Discord Account

isahooman#1110

### Plugin Description

Plugin will hide servers/folders from server list
Hide server button in server menu along with (mark as read and copy id) 
Simple settings menu just a list of hidden servers with option to unhide next to each server name/icon

### Go into more detail...

Hide all your shitty emote servers!

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by MeFinity** [comment]
dupe of [300](https://github.com/Aliucord/plugin-requests/issues/300)

 I did indeed check to make sure my plugin request is original!

**Comment by Dungeonscats** [comment]
Duplicate.

**Comment by rushiiMachine** [comment]
- #520
