### ISSUE TITLE
Spoiler command 

### ISSUE THREAD

**Issue by Diwang2001** [Aliucord/plugin-requests#993]
### Discord Account

Shoyou Hinata#5748

### Plugin Description

Spoiler Slash command that adds spoiler to all the text and media we send.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment]
Request this on the GitHub repo which has MoreSlashCommands plugin. Iirc tyman maintains it.
