### ISSUE TITLE
Font changer

### ISSUE THREAD

**Issue by TalkingBenStan** [Aliucord/plugin-requests#997]
### Discord Account

BigScriptus#0001

### Plugin Description

I think a plugin to change discords default fonts would be cool.

### Go into more detail...

Changing the font of the discord app.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment]
Use Themer https://github.com/Vendicated/AliucordPlugins/tree/main/Themer
